### ISSUE TITLE
Memory footprint is too large

### ISSUE THREAD

**Issue by qiuzi** [tatsuhiro-t/aria2#112]
1.7.1 After using the memory footprint 140% Here is my configuration:

1: aria2c -c -D --enable-rpc --rpc-listen-all=true --rpc-allow-origin-all --seed-time=525600 --conf-path=/etc/aria2/aria2.conf --dir=/mnt/sda1/Downloads --input-file=/mnt/sda1/.aria2/aria2file.gz --save-session=/mnt/sda1/.aria2/aria2file.gz --save-session-interval=60 --disk-cache=0 --dht-file-path=/mnt/sda1/.aria2/dht.dat --file-allocation=falloc --rpc-user=***** --rpc-passwd=***** --max-overall-download-limit=0 --max-overall-upload-limit=0 --bt-max-peers=25 --split=5 --max-connection-per-server=5 --max-concurrent-downloads=5 --listen-port=51413 --dht-listen-port=51413

2: /etc/aria2/aria2.conf :
continue
peer-id-prefix=-UT3000-
user-agent=uTorrent/3000(25756)
event-poll=epoll
disable-ipv6
check-certificate=false
min-split-size=5M
save-session-interval=60
force-save
max-download-result=5
enable-dht
enable-dht6=false
enable-peer-exchange
bt-enable-lpd
bt-seed-unverified
bt-save-metadata
bt-hash-check-seed
bt-remove-unselected-file
bt-stop-timeout=0
seed-ratio=10.0

Wrong place?

**Comment by tatsuhiro-t** [comment]
Are you still experiencing this issue?
