### ISSUE TITLE
coredump on SmartOS

### ISSUE THREAD

**Issue by jjlawren** [tatsuhiro-t/aria2#123]
I'm able to compile and run on SmartOS, but aria2c core dumps during any activity on the RPC socket. Here's a core stack:

fffffd7fffdfefe0 0x32d8dd()
fffffd7fffdff160 libc.so.1`_SUNW_Unwind_RaiseException+0x50(841f50)
fffffd7fffdff180 libstdc++.so.6.0.17`__cxa_throw+0x59()
fffffd7fffdff210 _ZN5aria219HttpHeaderProcessor5parseEPKhm+0x5b1()
fffffd7fffdff2f0 _ZN5aria210HttpServer14receiveRequestEv+0x6c()
fffffd7fffdff490 _ZN5aria217HttpServerCommand7executeEv+0x144()
fffffd7fffdff4d0 _ZN5aria212_GLOBAL__N_114executeCommandERSt5dequeIPNS_7CommandESaIS3_EENS2_6STATUSE+0x6f()
fffffd7fffdff510 _ZN5aria214DownloadEngine3runEb+0xa1()
fffffd7fffdff550 _ZN5aria219MultiUrlRequestInfo7executeEv+0x43()
fffffd7fffdff5b0 _ZN5aria24mainEiPPc+0x4f()
fffffd7fffdff600 main+0x2c()
fffffd7fffdff610 _start+0x6c()

**Comment by tatsuhiro-t** [comment]
OK, so this is toolchain related issue.  Closing.
