### ISSUE TITLE
--check-integrity doesn't prevent download from happening again

### ISSUE THREAD

**Issue by devicenull** [tatsuhiro-t/aria2#173]
This is with 1.17.1 (as it's the last version I can easily compile on CentOS).

I have a metalink file:

```
<?xml version="1.0" encoding="utf-8"?>
<metalink version="3.0" generator="test" xmlns="http://www.metalinker.org/">
<files>
        <file name="testfile">
                <size>104857600</size>
                <verification>
                        <hash type="md5">681025d06b3fec0117efcd5f1d1d8002</hash>
                </verification>
                <resources>
                        <url type="http" location="us" preference="50">http://speedtest.constant.com/100MBtest.bin</url>
                </resources>
        </file>
</files>
</metalink>
```
and I invoke aria2c:

aria2c --check-integrity=true --allow-overwrite=true --follow-metalink=mem big.metalink

The first time I run it, everything works properly.  The file is downloaded, and checksum verification takes place.  The second time I run it, 'testfile' is deleted, and redownloaded, even though the checksum already matches.

My next thought was to try with --continue, which corrects this problem, but introduces another problem.  If I replace 'testfile' with a smaller file, then try:

aria2c --check-integrity=true --allow-overwrite=true --follow-metalink=mem --continue big.metalink

I receive an error, and the file is corrupted (md5 doesn't match)
```
[#24c499 100MiB/100MiB(100%) CN:0] [Checksum:#24c499 99MiB/100MiB(99%)]
12/24 12:20:30 [ERROR] Checksum error detected. file=testfile

12/24 12:20:30 [NOTICE] Download GID#24c4994baedd709b not complete: testfile

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
24c499|ERR |   9.4MiB/s|testfile
```

So, there seems to be something wrong here.
* check-integrity overwrites the file without continue, even if the hash matches
* allow-overwrite doesn't actually overwrite the file in the event of a hash mismatch.

Ultimately, we're using aria2c to download a few files via metalink.  We periodically attempt to redownload the files to update them.  The files are not necessarily different each time we run aria2c, and we'd prefer to not redownload them if the hash is the same.  In the event of a hash mismatch, we'd expect aria2c to delete the existing file and redownload (which is not currently being done).

**Comment by AndCycle** [comment]
@tatsuhiro-t 
may I ask a question about how should I do it?

as you suggest allow-overwrite will truncate file first,
so if I only use check-integrity, will it update the file that exist but have different checksum?

the scenario here is I use aria2 as a content update program,
I need it to download content that been updated.

**Comment by tatsuhiro-t** [comment]
From http://aria2.github.io/manual/en/html/aria2c.html#cmdoption-V, it looks like YES.  Have you tried that?

**Comment by AndCycle** [comment]
@tatsuhiro-t 
tried on small file which is hardly confirm the behavior because it finish in secs, just wanna make sure.
