### ISSUE TITLE
aria2 can't create Settings folder in Win 8.1

### ISSUE THREAD

**Issue by sambul13** [tatsuhiro-t/aria2#229]
Current release aria2 at 1st run tends to create default folder with settings in c:\users\user\\.aria2. When started as a service via NSSM, in Win7 aria2 can create it only when run with User credentials, but not with service default Local System credentials. In Win8.1 it can't create .aria2 folder regardless of service or Cmd run credentials, probably since the app is portable. As a result, aria2 can start as a service only in Paused mode, and can't be Resumed. It gives the error in NSSM log:

"Specify at least one URL.
Usage: aria2c [OPTIONS] [URI | MAGNET | TORRENT_FILE | METALINK_FILE]...
See 'aria2c -h'"

I had to manually copy .aria2 folder from Win7 to Win8.1 c:\users\user\ , then added service startup string in NSSM GUI when creating aria2 service:
--conf-path=c:\users\user\\.aria2\aria2.conf

After that aria2 service started normally with Local System credentials, and could write logs to .aria2 folder. I didn't try, but the same issue is likely to occur when running aria2 from Cmd. Is it possible to fix that bug?

**Comment by tatsuhiro-t** [comment]
I close this issue since the point of this issue was fixed by --enable-rpc.  Credentials or permission is windows specific, and can be workarounded by --conf option.
