### ISSUE TITLE
Integrate with travis-ci

### ISSUE THREAD

**Issue by nmaier** [tatsuhiro-t/aria2#232]
It might be a good idea to run continuous integration tests using [Travis-CI](https://travis-ci.org/). It's free for open source after all. And would catch when I fail to add a header :p
It should be possible to do gcc-4.7, gcc-4.8 and mingw-w64 tests with some tweaking...
E.g. gcc-4.8 stuff
https://github.com/primordialmachine/machine/blob/4ab72f8d8f8fa521b52605d54cab846f097f0339/.travis.yml

There is also a [Coverity](https://scan.coverity.com/travis_ci) add-on...

**Comment by tatsuhiro-t** [comment]
I just landed travis integration.  To use container-based infrastructure on travis, we have to whitelist all the libraries we depend on.  I raised the issue to travis, and everything was resolved today.  Awesome.
Now I pushed .travis file to master branch, and integration completed.  Closing issue.

**Comment by Haocen** [comment]
Can you put build status icon in readme?
