### ISSUE TITLE
Very nice - possible for firefox addon for torrent?

### ISSUE THREAD

**Issue by Noitidart** [tatsuhiro-t/aria2#249]
This thing is very nice. I never trusted torrent applications. They always install all kinds of crap.

Is it possible to split the torrent part of this app to a firefox-addon? Would be super cool to see a simple/clean torrent client for firefox.

**Comment by tatsuhiro-t** [comment]
There is no plan to split torrent part to something else.

**Comment by Noitidart** [comment]
Aw dang

**Comment by tatsuhiro-t** [comment]
There is several C/C++ BitTorrent libraries.  They are meant to be reusable.  I think using it is better than making effort to split feature from aria2.

**Comment by Noitidart** [comment]
Thanks so much @tatsuhiro-t for the idea! :)
