### ISSUE TITLE
abnormal DNS resolution time

### ISSUE THREAD

**Issue by willemijns** [tatsuhiro-t/aria2#282]
Hello,

Since 1.17.1 on windows 7 , DNS resolves are too slow... whatever the DNS server used...

https://www.youtube.com/watch?v=j6LkHEPOKhY

The DNS async library has changed betwen 1.17.0 and 1.17.1, i suspect that...
tatsuhiro has the deep log about it, i wait his 1.18.8 specific version with old DNS library to confirm that ;)

ipconfig /flushdns
pause
70aria2c.exe -v
pause
71aria2c.exe -v
pause
88aria2c.exe -v
pause
del image*.*
70aria2c.exe http://test-debit.free.fr/image.iso --stop 13
del image*.*
71aria2c.exe http://test-debit.free.fr/image.iso --stop 13
del image*.*
88aria2c.exe http://test-debit.free.fr/image.iso --stop 13
pause

**Comment by voltagex** [comment]
Any update on this?

**Comment by tatsuhiro-t** [comment]
Are you still having this issue?
Latest aria2 binary release should work.

**Comment by voltagex** [comment]
Sorry, I didn't see the new release - confirming 1.18.10 works fine. You can close this now, thanks!

**Comment by tatsuhiro-t** [comment]
Thank you for confirming this is working. Closing.
