### ISSUE TITLE
Where can i find the Linux distributions?

### ISSUE THREAD

**Issue by AnselmD** [tatsuhiro-t/aria2#285]
Where can i find the Linux distributions?
Here http://aria2.sourceforge.net/ i can see:

We also have wiki page for additional download information including various Linux distributions.

But I can not find the wiki: http://sourceforge.net/apps/trac/aria2/wiki/Download

**Comment by tatsuhiro-t** [comment]
wiki is gone now.  I thin most linux distribution has aria2 package now.
