### ISSUE TITLE
Documentation on rpc secret token incorrect

### ISSUE THREAD

**Issue by erickok** [tatsuhiro-t/aria2#294]
Following https://github.com/tatsuhiro-t/aria2/blob/master/doc/manual-src/en/aria2c.rst#rpc-authorization-secret-token (and therefor the command line documentation), if --rpc-secret is supplied the secret token should be supplied in every RPC request encoded as "token::$$secret$$" as first parameter.

However, this seems incorrect as the Aria2 does not access this format (instead returning an 'Unauthorized' error), rather it accepts the "token:$$secret$$" format (with only one colon).

Incorrect:
```
curl  -H 'Content-Type: application/json' -H 'Accept:application/json' --data '{"jsonrpc":"2.0","method":"aria2.tellActive","params":["token::1234"],"id":1}' http://localhost:6800/jsonrpc
```
```json
{"id":1,"jsonrpc":"2.0","error":{"code":1,"message":"Unauthorized"}}
```
Correct:
```
curl  -H 'Content-Type: application/json' -H 'Accept:application/json' --data '{"jsonrpc":"2.0","method":"aria2.tellActive","params":["token:1234"],"id":1}' http://localhost:6800/jsonrpc
```
```json
{"id":1,"jsonrpc":"2.0","result":[]}
```
Note that at one place in the text the "token:" prefix is correctly used, but in other parts (like the example), it is not.

**Comment by sonnyp** [comment]
close this?

**Comment by tatsuhiro-t** [comment]
Yeah, close it now
