### ISSUE TITLE
RPC method to remove download and all downloaded files

### ISSUE THREAD

**Issue by farnoy** [tatsuhiro-t/aria2#299]
A common scenario for me is to seed a torrent until I need to reclaim the disk space. No UI I've seend has this option to remove the torrent along with the files downloaded. I looked into RPC documentation and saw only `purgeDownloadResult` and `removeDownloadResult` but it talks about removing from memory, I don't think that's what I'm after. Can we get an RPC call like `removeWithFiles([secret], gid)` or similar?

**Comment by farnoy** [comment]
I've actually written a bunch of scripts to help me with that. They look at the active `.torrent` files I have in a directory and generate the aria session file.

This declarative approach makes me not need this new RPC method, so you're free to close this I guess.

**Comment by ziahamza** [comment]
aah nice. thats good that you got it working. I will close this issue then

**Comment by tatsuhiro-t** [comment]
OK, closing now.
