### ISSUE TITLE
[SocketCore.cc:897] errorCode=1 SSL I/O error

### ISSUE THREAD

**Issue by vlavorini** [tatsuhiro-t/aria2#305]
Hello,

   in some of our GRID servers, while downloading i receive this error, while at most of them all works fine.
Do you have any hints to understand why?
Command i use:
aria2c --log=aria2c.log --ca-certificate=cabundle.pem --certificate=/tmp/x509up_u45324 --private-key=/tmp/x509up_u45324 --auto-file-renaming=false --continue --server-stat-of=aria2cperf.txt https://fal-pygrid-30.lancs.ac.uk:443/dpm/lancs.ac.uk/home/atlas/atlasscratchdisk/rucio/user/gangarbt/22/2a/user.gangarbt.1113151737.41980.3918.lib.tgz

Log file content:
(how can i upload it?)

**Comment by tatsuhiro-t** [comment]
Please reopen this issue if you still experience this issue.
