### ISSUE TITLE
Android 5.0 "error: only position independent executables (PIE) are supported."

### ISSUE THREAD

**Issue by ffallah** [tatsuhiro-t/aria2#321]
Version 1.18.8 doesn't run on Android 5.0+
More info on the issue :
http://stackoverflow.com/questions/24818902/running-a-native-library-on-android-l-error-only-position-independent-executab

**Comment by tatsuhiro-t** [comment]
Thank  you.  Looks like we need to build android binary with android-16.

**Comment by ffallah** [comment]
Yes. I also believe you need to compile using the latest android NDK.
If you had time to do that, I would be happy to test it and report back :)

**Comment by tatsuhiro-t** [comment]
Check latest 1.18.9 released just now.  We built android binary with NDK r10d and Android 16 API.

**Comment by ffallah** [comment]
It still gives this error :
error: only position independent executables (PIE) are supported.
I highly recommend you to read the stackoverflow link. may be some other changes are required for it to work on Android 5+

**Comment by tatsuhiro-t** [comment]
Thank you for testing.  I built another binary with -fPIE and -pie flags set.
https://sourceforge.net/projects/aria2/files/debug/gh-321/
Could you test it again?

**Comment by ffallah** [comment]
It works fine now. Good job :)

**Comment by tatsuhiro-t** [comment]
Thanks.  I'll upload new binary to proper download section.

**Comment by tatsuhiro-t** [comment]
Finally I upload PIE build to sf.net.

**Comment by PiotrPanasiuk** [comment]
Yep Maybe I shall open this topic once again, anyway my version is 2.0.3 and I have this issue also on 5.1.1 with cygeonmod 12.1. is there any hope to fix this?

**Comment by evildog1** [comment]
i want to use GDB debugger. is there a fix for Sony Xperia Z3 Comapct?
