### ISSUE TITLE
metalink v4 url priorities seem to be ignored

### ISSUE THREAD

**Issue by dfandrich** [tatsuhiro-t/aria2#326]
When downloading the file from the metalink at http://curl.haxx.se/metalink.cgi?curl=tar.lzma aria2c seems to ignore the url priorities when choosing hosts. With the default parameters (which causes it download the file from a single host), it seems to choose the last URL, no matter its priority. When performing a split download, it also seems to choose hosts regardless of the priority. I've determined that the priorities in the xml file are being parsed correctly.

**Comment by dfandrich** [comment]
I've discovered by dumping entry->resources immediately after the call entry->reorderResourcesByPriority(); in Metalink2RequestGroup::createRequestGroup that the URLs aren't actually sorted by priority. They don't have any obvious order that I can tell at that point.

**Comment by dfandrich** [comment]
I see the order not—except for the first, the remainder *are* sorted by priority (there are only 3 priorities). It's just that the first URL was specified with the highest priority (30) in the XML file, but somehow it got turned into -999969 by the time it reached the resources list (with an interesting equation being -999969=30-MetalinkResource::getLowestPriority()).

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  I'm now looking into this.

**Comment by tatsuhiro-t** [comment]
Did you specify --metalink-location and/or --metalink-preferred-protocol?
If they are given, those resources have precedence over others.
In metalink4 specification, 0 is the highest priority and lowest value is 999999.
If above options are given, priority of matched resources is subtracted by 999999 so that they have higher priority.

**Comment by dfandrich** [comment]
No, I didn't use those command-line options, but wouldn't you know it, I had a 6 year old ~/.aria2/aria2.conf file I had forgotten about with metalink-location set. One of the locations even matched that of the site that was promoted first. I did some more testing including changing that flag and aria2c seems to do the right thing here after all. Sorry about the noise. Some logging of the selection process would have helped in this case; the process is completely opaque in the logs right now.

**Comment by dfandrich** [comment]
I've created pr#327 to add a log of possible Metalink URLs and their final priority values.

**Comment by tatsuhiro-t** [comment]
Thank you for PR #327,which was merged just now.
