### ISSUE TITLE
--remote-time doesn't always work

### ISSUE THREAD

**Issue by tico-tico** [tatsuhiro-t/aria2#330]
For instance:

`aria2c -R http://www.voxengo.com/files/VoxengoTempoDelay_191_WinVST_setup.zip`

won't set correct time for the file, although *Last-Modified* exists in the header and **wget** works just fine.

aria2 v1.18.8, Win7 SP1.

**Comment by tatsuhiro-t** [comment]
HTTP date ending +0000 is rather rare and not preferred according to RFC7231, but anyway fixed in d5d21d2

**Comment by nmaier** [comment]
Are there servers returning `+0200` etc and is that handled?

**Comment by tatsuhiro-t** [comment]
I don't know.  RFC7231 says we expect GMT only.
