### ISSUE TITLE
Unable to build 1.18.9

### ISSUE THREAD

**Issue by akashihi** [tatsuhiro-t/aria2#334]
./.libs/libaria2.a(LibgcryptMessageDigestImpl.o): In function `make_hi<aria2::Adler32MessageDigestImpl>':
/home/chollya/aria2-1.18.9/src/MessageDigestImpl.h:59: undefined reference to `aria2::Adler32MessageDigestImpl::length()'
./.libs/libaria2.a(LibgcryptMessageDigestImpl.o): In function `make_unique<aria2::Adler32MessageDigestImpl>':
/home/chollya/aria2-1.18.9/src/a2functional.h:180: undefined reference to `aria2::Adler32MessageDigestImpl::Adler32MessageDigestImpl()'

./configure  CFLAGS="-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2" \
                             LDFLAGS="-Wl,-z,relro -Wl,-z,defs,--as-needed" \
                           --prefix=/usr \
                           --with-gnutls \
                           --without-openssl \
                           --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt

Debian wheezy.

**Comment by tatsuhiro-t** [comment]
Did you install zlib1g-dev? and configure found it correctly?

**Comment by akashihi** [comment]
dpkg -l zlib1g-dev

**Comment by tatsuhiro-t** [comment]
I compiled aria2 with the same configure options and build was successful.
Does Adler32MessageDigestImpl.cc exist under src directory?

**Comment by nmaier** [comment]
@akashihi  Sounds like you forgot to run `autoreconf -fiv` again after pulling...

**Comment by akashihi** [comment]
with 1.8.10 problem just disappeared.
