### ISSUE TITLE
Random file selection

### ISSUE THREAD

**Issue by imoverclocked** [tatsuhiro-t/aria2#335]
For large clouds with very little initial data and metalink-backed-by-local-cache content, aria2c is super slow since all clients ask for the same file based on the order of the torrent file list. Randomizing the next URL to download would drastically improve overall performance.

**Comment by tatsuhiro-t** [comment]
aria2 shuffles URLs with same priority value in metalink file.  What does your metalink file look like?

**Comment by imoverclocked** [comment]
On further inspection, I'm getting a torrent file with a base URL embedded into it so aria knows how to fallback to an http backend. It falls back for each file in the order listed in the torrent. So, this has nothing to do with metalink even though mentioned it previously.

**Comment by tatsuhiro-t** [comment]
So you have several base URLs in torrent file, want to shuffle them so that aria2 distributes load among them, right?

**Comment by tatsuhiro-t** [comment]
Fix committed via 4cf0bb742f079dcd75f676391a4e0af1bb176bdd
Could you test this?

**Comment by imoverclocked** [comment]
I tried it but it still seems to be the same order. I have only one base URL. Here is my scenario:

I have a torrent with (say) 10000 files and a single baseURL which is an http cache server that has a high latency connection to its source. If I start 100 aria2 clients and they all request the files in the same order then the cache server grabs a single file at a time from its source. Since it's latency bound, this takes a *really* long time.

If we randomize the order that aria2 requests the files (not the backend) then the cache server will get 100 different files at the same time. In the case of no overlapping requests, this will make the overall transfer roughly 100 times faster.

**Comment by tatsuhiro-t** [comment]
Thanks for additional information.
aria2 currently selects URL based on piece in entire torrent (in other words, contiguous space resulted in concatenating all files).
The possible enhancement is add new piece selection algorithm available to --stream-piece-selector, say "random", to randomize piece selection so that aria2 can pick up associated URL for selected piece.

**Comment by imoverclocked** [comment]
That sounds correct.

**Comment by tatsuhiro-t** [comment]
I added --stream-piece-selector=random option in https://github.com/tatsuhiro-t/aria2/tree/random-webseeding
Could you test it?  Use --stream-piece-selector=random to randomize the file to request.

**Comment by dignabbit** [comment]
Hey @tatsuhiro-t , I'd like to pick up the effort of testing this feature. Would you mind rebasing the branch `random-webseeding` onto master? That would be great! Thanks!

**Comment by tatsuhiro-t** [comment]
I've merged master into random-webseeding. It was clean merge actually.

**Comment by dignabbit** [comment]
@tatsuhiro-t 

I merged master (basically 1.19.2) into randomwebseeding and tested it with `--stream-piece-selector=random`.

Here are the results:

```
x.x.x.1 [05/Oct/2015:21:57:41 +0000] "GET /bigfile HTTP/1.1" 206 3475200  "aria2/1.19.2" bytes=195582624-229284543
x.x.x.1 [05/Oct/2015:21:57:43 +0000] "GET /bigfile HTTP/1.1" 206 524288   "aria2/1.19.2" bytes=3693216-4217503
x.x.x.1 [05/Oct/2015:21:57:47 +0000] "GET /bigfile HTTP/1.1" 206 524288   "aria2/1.19.2" bytes=5266080-5790367
x.x.x.1 [05/Oct/2015:21:57:56 +0000] "GET /bigfile HTTP/1.1" 206 857216   "aria2/1.19.2" bytes=12081824-14178975
x.x.x.1 [05/Oct/2015:21:57:58 +0000] "GET /bigfile HTTP/1.1" 206 524288   "aria2/1.19.2" bytes=220224160-220748447
x.x.x.1 [05/Oct/2015:21:58:01 +0000] "GET /bigfile HTTP/1.1" 206 23200    "aria2/1.19.2" bytes=0-23199

x.x.x.2 [05/Oct/2015:21:57:42 +0000] "GET /bigfile HTTP/1.1" 206 2974192  "aria2/1.19.2" bytes=25713312-229284543
x.x.x.2 [05/Oct/2015:21:57:52 +0000] "GET /bigfile HTTP/1.1" 206 1865024  "aria2/1.19.2" bytes=195058336-211311263
x.x.x.2 [05/Oct/2015:21:57:54 +0000] "GET /bigfile HTTP/1.1" 206 524288   "aria2/1.19.2" bytes=28859040-29383327
x.x.x.2 [05/Oct/2015:21:57:58 +0000] "GET /bigfile HTTP/1.1" 206 524288   "aria2/1.19.2" bytes=178805408-179329695
x.x.x.2 [05/Oct/2015:21:58:03 +0000] "GET /bigfile HTTP/1.1" 206 524288   "aria2/1.19.2" bytes=220224160-220748447
x.x.x.2 [05/Oct/2015:21:58:06 +0000] "GET /bigfile HTTP/1.1" 206 23200    "aria2/1.19.2" bytes=0-23199

x.x.x.3 [05/Oct/2015:22:17:52 +0000] "GET /bigfile HTTP/1.1" 206 27934752 "aria2/1.19.2" bytes=201349792-229284543
x.x.x.3 [05/Oct/2015:22:17:59 +0000] "GET /bigfile HTTP/1.1" 206 80216064 "aria2/1.19.2" bytes=121133728-201349791
x.x.x.3 [05/Oct/2015:22:18:02 +0000] "GET /bigfile HTTP/1.1" 206 33030144 "aria2/1.19.2" bytes=88103584-121133727
x.x.x.3 [05/Oct/2015:22:18:15 +0000] "GET /bigfile HTTP/1.1" 206 88103584 "aria2/1.19.2" bytes=0-88103583
```

So in general it works. But it doesn't seem to look very much different from this run with an old version:

```
x.x.x.1 [05/Oct/2015:22:18:26 +0000] "GET /bigfile HTTP/1.1" 206 6012096 "aria2/1.17.1" bytes=48820796-229223879
x.x.x.1 [05/Oct/2015:22:19:05 +0000] "GET /bigfile HTTP/1.1" 206 863008  "aria2/1.17.1" bytes=154202684-229223879
x.x.x.1 [05/Oct/2015:22:19:06 +0000] "GET /bigfile HTTP/1.1" 206 863008  "aria2/1.17.1" bytes=28897852-48820795
x.x.x.1 [05/Oct/2015:22:19:08 +0000] "GET /bigfile HTTP/1.1" 206 863008  "aria2/1.17.1" bytes=31519292-48820795
x.x.x.1 [05/Oct/2015:22:19:10 +0000] "GET /bigfile HTTP/1.1" 206 1361120 "aria2/1.17.1" bytes=38859324-48820795
x.x.x.1 [05/Oct/2015:22:19:11 +0000] "GET /bigfile HTTP/1.1" 206 48012   "aria2/1.17.1" bytes=229175868-229223879
x.x.x.1 [05/Oct/2015:22:19:11 +0000] "GET /bigfile HTTP/1.1" 206 62012   "aria2/1.17.1" bytes=0-62011
x.x.x.1 [05/Oct/2015:22:19:11 +0000] "GET /bigfile HTTP/1.1" 206 860112  "aria2/1.17.1" bytes=46199356-48820795

x.x.x.2 [05/Oct/2015:22:26:26 +0000] "GET /bigfile HTTP/1.1" 206 4494592 "aria2/1.17.1" bytes=48820796-229223879
x.x.x.2 [05/Oct/2015:22:26:54 +0000] "GET /bigfile HTTP/1.1" 206 5198320 "aria2/1.17.1" bytes=54063676-229223879
x.x.x.2 [05/Oct/2015:22:27:01 +0000] "GET /bigfile HTTP/1.1" 206 1375600 "aria2/1.17.1" bytes=143192636-229223879
x.x.x.2 [05/Oct/2015:22:27:03 +0000] "GET /bigfile HTTP/1.1" 206 860112  "aria2/1.17.1" bytes=177271356-229223879
x.x.x.2 [05/Oct/2015:22:27:17 +0000] "GET /bigfile HTTP/1.1" 206 3478096 "aria2/1.17.1" bytes=27324988-48820795
x.x.x.2 [05/Oct/2015:22:27:19 +0000] "GET /bigfile HTTP/1.1" 206 860112  "aria2/1.17.1" bytes=31519292-48820795
x.x.x.2 [05/Oct/2015:22:27:21 +0000] "GET /bigfile HTTP/1.1" 206 524288  "aria2/1.17.1" bytes=34665020-35189307
x.x.x.2 [05/Oct/2015:22:27:29 +0000] "GET /bigfile HTTP/1.1" 206 62012   "aria2/1.17.1" bytes=0-62011

x.x.x.3 [05/Oct/2015:22:26:56 +0000] "GET /bigfile HTTP/1.1" 206 8169616 "aria2/1.17.1" bytes=48820796-229223879
x.x.x.3 [05/Oct/2015:22:26:59 +0000] "GET /bigfile HTTP/1.1" 206 871696  "aria2/1.17.1" bytes=121696828-229223879
x.x.x.3 [05/Oct/2015:22:27:03 +0000] "GET /bigfile HTTP/1.1" 206 1002016 "aria2/1.17.1" bytes=123269692-229223879
x.x.x.3 [05/Oct/2015:22:27:12 +0000] "GET /bigfile HTTP/1.1" 206 1891088 "aria2/1.17.1" bytes=179892796-229223879
x.x.x.3 [05/Oct/2015:22:27:25 +0000] "GET /bigfile HTTP/1.1" 206 2525312 "aria2/1.17.1" bytes=19460668-48820795
x.x.x.3 [05/Oct/2015:22:27:28 +0000] "GET /bigfile HTTP/1.1" 206 62012   "aria2/1.17.1" bytes=0-62011
```

How does aria map a torrent block to a range request? It looks like it is grouping them together (with both the old and the new version)? Would be great if you could explain that process a bit.

Thanks!

**Comment by imoverclocked** [comment]
@dignabbit You might retry the tests with /bigfile1 ... /bigfileN because (AFAICR) the selector code chooses a random file rather than a random "block" from the torrent. In this case the old code would satisfy all blocks for /bigfile1 and then move onto /bigfile2 and so forth. The new code should choose a random file in the torrent to satisfy first.

**Comment by imoverclocked** [comment]
@tatsuhiro-t It seems this algorithm works well at scale. Thanks for the patch!

**Comment by dignabbit** [comment]
@tatsuhiro-t @imoverclocked

FYI, this was well tested on my side here now and yes, it does only randomize the files. But it does speed up our downloads by a significant percentage!

Maybe the randomizing block approach might be feasible in the future, given that it probably would speed up multiple concurrent downloads even more..

@tatsuhiro-t Do you think you can merge this into mainline?

**Comment by tatsuhiro-t** [comment]
OK, will do the merge.  We have merge conflict, probably due to clang-format thing, but not much a problem.

**Comment by tatsuhiro-t** [comment]
Merged. 88f20e4
