### ISSUE TITLE
comment downloaded links in input file

### ISSUE THREAD

**Issue by remitamine** [tatsuhiro-t/aria2#337]
is there any way to comment the downloaded link when aria2 complete downloading the file so when stop and resume the download from a long list of links it can directly continue from the last link it was downloading and don't try to download the already downloaded files.

**Comment by tatsuhiro-t** [comment]
You can use --save-session option to make aria2 save uncompleted file list in given file.
That file can be an input to next aria2 invocation using -i.

**Comment by remitamine** [comment]
i'm sorry i didn't know about it,thanks.
