### ISSUE TITLE
Split test/UtilTest.cc into mutliple files

### ISSUE THREAD

**Issue by nmaier** [tatsuhiro-t/aria2#338]
That file is getting huge... So huge in fact that the OOM killer sometimes kills the compiler in my kinda-low-memory linux VMs.

**Comment by tatsuhiro-t** [comment]
Agreed.  Maybe split it into half mechanically?

**Comment by nmaier** [comment]
Either that, or split it by (broad) topic.

**Comment by tatsuhiro-t** [comment]
I once consider that once.  For example, string_util which only contains string related functions.
But if only test is in our concern, then just splitting UtilTest.cc is low risk and quick.

**Comment by nmaier** [comment]
util.cc itself seems to compile fine for me for now. It's just UtilTest.cc, which additionally pulls in cppunit headers and has all that nifty test-code, ofc, that is a problem.

**Comment by tatsuhiro-t** [comment]
OK, just split UtilTest.cc into half *mechanically* and we are done.  Agreed?

**Comment by nmaier** [comment]
Sure

**Comment by tatsuhiro-t** [comment]
Fix committed via 9cbbe9f
