### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by pedropetz** [tatsuhiro-t/aria2#340]
[ppetz@petzMJ ~]$ aria2c http://softlayer-ams.dl.sourceforge.net/project/manjarolinux/release/0.8.12/xfce/manjaro-xfce-0.8.12-x86_64.iso
aria2c: SimpleRandomizer.cc:93: void aria2::SimpleRandomizer::getRandomBytes(unsigned char*, size_t): Assertion `rv >= 0 && (size_t)rv == len' failed.
Aborted (core dumped)

**Comment by tatsuhiro-t** [comment]
Duplicate of #336 and already fixed in master branch.
