### ISSUE TITLE
broken encondig of Russian man page

### ISSUE THREAD

**Issue by bacalit** [tatsuhiro-t/aria2#341]
Russian man page not displayed correctly.
Encoding UTF8 is correct,  but I think header of man page is incorrect, so user can't read this man

**Comment by tatsuhiro-t** [comment]
I cannot read Russian, so don't know it is displayed correctly or not, but comparing output with web page (http://aria2.sourceforge.net/manual/ru/html/aria2c.html), it looks like displayed correctly:
```
$ man -l doc/manual-src/ru/_build/man/aria2c.1
ARIA2C(1)                            aria2                           ARIA2C(1)



NAME
       aria2c - сверхбыстрая утилита загрузки

ОБЗОР
       aria2c     [<ПАРАМЕТРЫ>]    [<URI>|<MAGNET-ССЫЛКА>|<TORRENT-ФАЙЛ>|<MET‐
       ALINK-ФАЙЛ>] ...

ОПИСАНИЕ
       aria2 - это утилита  для  загрузки  файлов.  Поддерживаемые  протоколы:
       HTTP(S),  FTP,  BitTorrent  и  Metalink.  aria2  может загрузить файл с
       разных  источников/протоколов  и  пытается   максимально   использовать
       пропускную   способность  канала.  Есть  поддержка  загрузки  файла  по
       протоколам  HTTP(S)/FTP  и   BitTorrent   одновременно,   пока   данные
       загружаются  по  HTTP(S)/FTP,  они  тут  же могут выгружаться в BitTor‐
       rent-рой. Используя контрольные суммы блока данных для Metalink,  aria2
       автоматически проверяет части данных во время загрузки файла.

ПАРАМЕТРЫ
   Основные параметры
       -d, --dir=<DIR>
              Каталог для сохранения загруженных файлов.
```

**Comment by bacalit** [comment]
Yes, your output displayed correctly and http://aria2.sourceforge.net/manual/ru/html/aria2c.html looks very good.
But here is solution for my situation, need to put this line as first line of Russian man file:
.\" -*- mode: troff; coding: utf8 -*-

**Comment by tatsuhiro-t** [comment]
So in my environment, Russian man pages are displayed correctly but in your environment, it is not displayed correctly because your tool does not detect UTF-8 correctly, possibly old man page program?

**Comment by bacalit** [comment]
It's problem for all users of ALT Linux (Main Russian distribution), so I corrected aria2 rpm package for it.
Any other Russian and/or UTF8 man pages from other packages displayed  correctly. Maybe It's specific for ALT Linux only.

**Comment by tatsuhiro-t** [comment]
Right, it seems it does not harm the output, so I added following one liner to add encoding specifier (see above commit).

**Comment by bacalit** [comment]
Thank you!
