### ISSUE TITLE
RPC responses seem to be rate-throttled at about 50KB/s

### ISSUE THREAD

**Issue by i336** [tatsuhiro-t/aria2#345]
When I have quite a few downloads active in `aria2`, there is a small delay in returning responses to RPC requests.

Right now, I have 100 individual downloads active (with only 2-5% CPU usage on a 933MHz Pentium 3! :D) so `aria2.tellActive` returns quite a bit of output, which takes a couple of seconds to retrieve - even over localhost:

    Time     Retr  Speed
    00:01.0: 128KB (119KB/s)
    00:02.0: 256KB (118KB/s)
    00:02.3: 272KB (120KB/s)
    00:02.6: 350KB (154KB/s)

I'm grateful to be able to say that the modem part of my modem-router has never given me any grief, but I guess the router part could be upgraded; requesting RPC data over the LAN from another PC is slower still (because that PC's link is flooded with HTTP requests from `aria2`, presumably).

    Time     Retr  Speed
    00:01.0:  23KB (22KB/s)
    00:02.0:  81KB (39KB/s)
    00:02.5:  85KB (38KB/s)
    00:03.0: 158KB (50KB/s)
    00:04.0: 247KB (58KB/s)

I would like the RPC data to be returned as fast as aria2 can internally gather the data and serialize it to JSON or XML output. As such, the purpose of this ticket is primarily so I can learn why this slowdown is occuring: is this a bug, or does the RPC server deliberately implement throttling?

**Comment by tatsuhiro-t** [comment]
As I recall, we do not rate limit RPC response.  I'll look into this issue.

**Comment by nmaier** [comment]
We do not intensionally rate limit the rpc responses, except in the case the secret token is incorrect.

However, there is of course a natural limit, as the neither the CPU nor the network is infinite speed. Seeing that the rate drops for non-local requests suggests that the network equipment or configuration is at fault.

@i336 you didn't exactly tell us what kind of system you're using except for CPU... What kind of network card, OS, etc. And what version of aria2 you're using? And whether you're using plain http or https (`--rpc-secure`)

**Comment by tatsuhiro-t** [comment]
Yes, there is no throttling.
If the size of RPC response is a problem and your issue may be solved or eased by decreasing it, then consider to use key parameter of RPC request: http://aria2.sourceforge.net/manual/en/html/aria2c.html#aria2.tellActive
and only request the data you need.

**Comment by i336** [comment]
Thanks for following this up, and thanks for the update! :)

@nmaier: Yeah, I've noticed the rate throttling when an invalid secret token is used :) it's a good security feature!

I'll admit my setup is notably older than most people's but the PCs and router in question appear to be able to sustain 10.7MB/s network throughput so my LAN is definitely capable of handling this.

It's the 100-300KB/s local (loopback/`lo0`) speed that has me stumped. One might conclude that it's a hardware processing speed limit - the box I had `aria2c` running on (slowly leeching files from a remote server while my internet was shaped to unlimited 256kbps last month :P) was an old spare PC I cobbled together from random parts that were lying around, including 100MHz SDRAM - but **that said**, `aria2c` WAS only using 1-6% CPU time at the *most* (ie, I never saw it use 7%), and asking `aria2c` repeatedly for RPC data didn't push the figure any higher. And so when I saw the RPC response was being quite visibly, noticeably throttled, I immediately thought of software rate-limiting.

@tatsuhiro-t: I actually submitted this issue after learning how to use the `key` parameter, but finding the RPC reponse was still sufficiently large to trigger... whatever was happening here... because I needed to include the filename information (which of course lists the full path... repeatedly, for as many `split`s as have been configured); I found that if the RPC response was less than 10KB or so (IIRC) it returns instantaneously, but if it's over that it seems to throttle the output, leading me to believe some part of the code was implementing a form of response chunking.

I'll be away from the computer for the next couple/few days, but before I go, I'm happy to setup SSH access if poking around and testing on the actual hardware in question sounds like a constructive idea (it's always my own preference, at least). When I come back I'll probably do some further testing/analysis myself too.

Oh, and I was using `aria2c` Git revision `649c49dcc675a26dd2b7598c09fc3e3539b5ef88`, dated Feb 21 2015 - the old version of aria2c I'd installed via my package manager was segfaulting when I repeatedly executed `aria2.pauseAll` and `aria2.unpauseAll` for dozens of simultaneous downloads. The Git version had no such issues. :D

**Comment by tatsuhiro-t** [comment]
I reproduced this issue with two machines in same LAN. I created 5000 download entries which are all paused and when I query aria2.tellWaiting(1,5000), aria2 sends some chunk of data once per second.
I identified the offending code and fixed in cb5ccf6.  @i336 , could you test it?

**Comment by i336** [comment]
I figured I wouldn't be waiting *too* long to test aria2c under the exact same conditions of my original issue - downloading slowly from a remote machine over shaped internet - so I thought I'd hold for a couple extra days before I replied. (I'm switching ISPs soon. =P lol)

I just fired `aria2c` back up after verifying I had the latest checkout then rebuilding, and I now receive 1MB-4MB RPC responses over the LAN within 700ms-1 second, and over `lo` with equivalent speed as well. I'm guessing the remaining delay is caused by `aria2c` collecting the requisite data and compiling the JSON/XML response on the slow CPU in question - the output itself is delayless now, regardless of whether I query `aria2.tellWaiting(1,3000)` or `aria2.tellActive()`.

I consider this now fixed, and I've taken the liberty of closing it. Thanks very much! :)

<sup>(Also, I'm curious - I took a look at the committed code fragment... and if I understand it correctly, was the code responsible for sending RPC responses doing so with noticeable delays because the same process space was servicing all of the actual download requests in question, but without checking whether RPC response data was queued...?</sup>

**Comment by tatsuhiro-t** [comment]
Aria2 is single threaded application and event based, it polls socket
read/write readiness all the time.  RPC process takes time, other download
items are affected, but usually download is not so fast that it is not much
slowed down.
2015/03/17 15:59 "i336" <notifications@github.com>:
