### ISSUE TITLE
Can't build 1.8.10 (getrandom_linux.c error)

### ISSUE THREAD

**Issue by bacalit** [tatsuhiro-t/aria2#346]
Hello!
Unable to build 1.18.10  and  1.18.9:

...
CXX      MetalinkPostDownloadHandler.lo
  CXX      MetalinkResource.lo
  CXX      metalink_helper.lo
  CXX      PollEventPoll.lo
  CC       getrandom_linux.lo
getrandom_linux.c: In function 'getrandom_linux':
getrandom_linux.c:56:20: error: 'SYS_getrandom' undeclared (first use in this function)
     read = syscall(SYS_getrandom, p, buflen, 0);
                    ^
getrandom_linux.c:56:20: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [getrandom_linux.lo] Error 1

ALT Linux
System x86-64
gcc 4.9.2
zlib 1.2.8

**Comment by tatsuhiro-t** [comment]
Thank you!
