### ISSUE TITLE
Aria2-1.18.10 fails to compile

### ISSUE THREAD

**Issue by qiuzi** [tatsuhiro-t/aria2#347]
Compiled OpenWrt errors

depbase=`echo SimpleRandomizer.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
        /bin/bash ../libtool  --tag=CXX   --mode=compile mipsel-openwrt-linux-uclibc-g++ -DHAVE_CONFIG_H -I. -I..  -Wall -I../lib -I../intl -I./includes -I./includes -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H  -I../deps/wslay/lib/includes -I../deps/wslay/lib/includes -I/home/openwrt/trunk/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include  -I/home/openwrt/trunk/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include/libxml2 -I/home/openwrt/trunk/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include  -I/home/openwrt/trunk/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -I/home/openwrt/trunk/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/include -I/home/openwrt/trunk/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/openwrt/trunk/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/include   -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float  -pipe -std=c++11  -MT SimpleRandomizer.lo -MD -MP -MF $depbase.Tpo -c -o SimpleRandomizer.lo SimpleRandomizer.cc &&\
        mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  mipsel-openwrt-linux-uclibc-g++ -DHAVE_CONFIG_H -I. -I.. -Wall -I../lib -I../intl -I./includes -I./includes -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I../deps/wslay/lib/includes -I../deps/wslay/lib/includes -I/home/openwrt/trunk/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -I/home/openwrt/trunk/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include/libxml2 -I/home/openwrt/trunk/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -I/home/openwrt/trunk/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -I/home/openwrt/trunk/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/include -I/home/openwrt/trunk/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/openwrt/trunk/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/include -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -pipe -std=c++11 -MT SimpleRandomizer.lo -MD -MP -MF .deps/SimpleRandomizer.Tpo -c SimpleRandomizer.cc  -fPIC -DPIC -o .libs/SimpleRandomizer.o
SimpleRandomizer.cc: In member function 'void aria2::SimpleRandomizer::getRandomBytes(unsigned char*, size_t)':
SimpleRandomizer.cc:98:21: error: 'errno' was not declared in this scope
     if (rv != -1 || errno != ENOSYS) {
                     ^
SimpleRandomizer.cc:98:30: error: 'ENOSYS' was not declared in this scope
     if (rv != -1 || errno != ENOSYS) {
                              ^
make[7]: *** [SimpleRandomizer.lo] Error 1

**Comment by nmaier** [comment]
Might be enough to just explicitly include the errno headers, or else need to check `ENOTSUP` is actually defined at all. I got a tentative patch doing both, but haven't had the time to test it actually fixes the issue when building against uClibc

**Comment by qiuzi** [comment]
@nmaier  What patch?

**Comment by nmaier** [comment]
The one on my local disk only... Some patience please ;)
