### ISSUE TITLE
RPC notification not issued if torrent is already complete

### ISSUE THREAD

**Issue by mfischer-zd** [tatsuhiro-t/aria2#355]
Conditions:
* aria2 is running as a daemon with RPC enabled
* client is communicating with aria2 via JSON-RPC via websocket
* client issues aria2.addTorrent request (not tested: aria2.addUri)
   * options in request:
     * `rpc-save-upload-metadata: true`
     * `seed-ratio: 0`
     * `check-integrity: true`
* torrent is already fully downloaded on client (i.e. it's able to seed)

Expected behavior:
* aria2 fires aria2.onBtDownloadComplete notification (and, if conditions permit, aria2 fires aria2.onDownloadComplete notification)
* no upload metadata file is written to disk

Actual behavior
* aria2 sends no notifications
* upload metadata file (sha1.torrent) is written to disk

**Comment by mfischer-zd** [comment]
After re-issuing the request, aria2 seems to think there are no seeders:

Final status of initial download (immediately after we receive an aria2.onBtDownloadComplete notification):

```json
{
   "bitfield":"fffff0",
   "bittorrent":{
      "announceList":[
         [
            "http://10.0.0.133:6881/announce"
         ]
      ],
      "creationDate":1426936234,
      "info":{
         "name":"git-2.3.3.tar.gz"
      },
      "mode":"single"
   },
   "completedLength":"5187306",
   "connections":"1",
   "dir":"/home/centos",
   "downloadSpeed":"516406",
   "files":[
      {
         "completedLength":"5187306",
         "index":"1",
         "length":"5187306",
         "path":"/home/centos/git-2.3.3.tar.gz",
         "selected":"true",
         "uris":[

         ]
      }
   ],
   "gid":"222c1085fcbc7abe",
   "infoHash":"a34ed4d8817c5d0673c04b1e417ea38aabd5b373",
   "numPieces":"20",
   "numSeeders":"1",
   "pieceLength":"262144",
   "status":"active",
   "totalLength":"5187306",
   "uploadLength":"0",
   "uploadSpeed":"0"
}
```

Status of subsequent torrent request (which never makes progress, and for which a aria2.onBtDownloadComplete notification is never fired):

```json
{
   "bitfield":"fffff0",
   "bittorrent":{
      "announceList":[
         [
            "http://10.0.0.133:6881/announce"
         ]
      ],
      "creationDate":1426936234,
      "info":{
         "name":"git-2.3.3.tar.gz"
      },
      "mode":"single"
   },
   "completedLength":"5187306",
   "connections":"0",
   "dir":"/home/centos",
   "downloadSpeed":"0",
   "files":[
      {
         "completedLength":"5187306",
         "index":"1",
         "length":"5187306",
         "path":"/home/centos/git-2.3.3.tar.gz",
         "selected":"true",
         "uris":[

         ]
      }
   ],
   "gid":"09e061e7190a936d",
   "infoHash":"a34ed4d8817c5d0673c04b1e417ea38aabd5b373",
   "numPieces":"20",
   "numSeeders":"0",
   "pieceLength":"262144",
   "status":"active",
   "totalLength":"5187306",
   "uploadLength":"0",
   "uploadSpeed":"0"
}
```

Questions: 
1. Why is `numSeeders` still "1" after the initial download is complete?  The client is now a seeder; shouldn't the value be "2"?
2. Why is `numSeeders` "0" during the subsequent download?  The client is now a seeder, and the original seeder is still in the swarm; shouldn't the value be "2"?

**Comment by mfischer-zd** [comment]
aria2 logs during second download request:

```
2015-03-21 12:04:45.681800 [INFO] [AbstractHttpServerResponseCommand.cc:118] CUID#15 - HttpServer: all response transmitted.
2015-03-21 12:04:45.685483 [INFO] [rpc_helper.cc:102] Executing RPC method aria2.addTorrent
2015-03-21 12:04:45.685692 [INFO] [RpcMethodImpl.cc:299] Uploaded torrent data was saved as /home/centos/2240aca3b685f90196beb265fb0c72755dbdb71e.torren
t
2015-03-21 12:04:45.685893 [INFO] [DefaultBtProgressInfoFile.cc:393] The segment file /home/centos/git-2.3.3.tar.gz.aria2 does not exist.
2015-03-21 12:04:45.685905 [INFO] [DefaultBtProgressInfoFile.cc:393] The segment file /home/centos/git-2.3.3.tar.gz.aria2 does not exist.
2015-03-21 12:04:45.685938 [INFO] [CheckIntegrityDispatcherCommand.cc:60] CUID#3 - Dispatching CheckIntegrityCommand CUID#16.
2015-03-21 12:04:45.732696 [INFO] [rpc_helper.cc:102] Executing RPC method aria2.tellStatus
2015-03-21 12:04:45.793388 [NOTICE] [CheckIntegrityCommand.cc:77] Verification finished successfully. file=/home/centos/git-2.3.3.tar.gz
2015-03-21 12:04:46.734936 [INFO] [rpc_helper.cc:102] Executing RPC method aria2.tellStatus
2015-03-21 12:04:46.735129 [INFO] [TrackerWatcherCommand.cc:381] Creating tracker request group GID#1efcee11b16c14c8
2015-03-21 12:04:46.735143 [INFO] [BtSeederStateChoke.cc:150] Seeder state, 0 choke round started
2015-03-21 12:04:46.735176 [INFO] [HttpInitiateConnectionCommand.cc:130] CUID#20 - Connecting to 10.0.0.133:6881
2015-03-21 12:04:46.735939 [INFO] [HttpConnection.cc:116] CUID#20 - Requesting:
GET /announce?info_hash=%A3N%D4%D8%81%7C%5D%06s%C0K%1EA%7E%A3%8A%AB%D5%B3s&peer_id=A2%2D1%2D18%2D10%2DG%FC%3C%04%EA%2A%F6%D7%F6&uploaded=0&downloaded=0&left=0&compact=1&key=%FC%3C%04%EA%2A%F6%D7%F6&numwant=50&no_peer_id=1&port=6883&event=started&supportcrypto=1 HTTP/1.1
User-Agent: aria2/1.18.10
Accept: */*
Host: 10.0.0.133:6881


2015-03-21 12:04:46.736769 [INFO] [HttpConnection.cc:154] CUID#20 - Response received:
HTTP/1.1 200 OK
Date: Sat, 21 Mar 2015 12:04:46 GMT
Content-Length: 76
Content-Type: text/plain; charset=utf-8
Connection: close


2015-03-21 12:04:46.736843 [INFO] [DownloadCommand.cc:233] CUID#20 - The download for one segment completed successfully.
2015-03-21 12:04:46.736857 [INFO] [DefaultPieceStorage.cc:477] The download was complete.
2015-03-21 12:04:46.736918 [INFO] [DefaultBtAnnounce.cc:342] No peers6 received.
```

**Comment by mfischer-zd** [comment]
I've noticed that aria2 no longer writes the metadata file to disk if I change the value of the `rpc-save-upload-metadata` to `"false"` (string) instead of `false` (boolean).  That solves one problem, but it's not clear from the documentation what the expected value types for each option in the JSON-RPC request are.

**Comment by mfischer-zd** [comment]
I tried changing the values of `check-integrity` from `true` to `"true"` and `seed-ratio` from `0` to `"0"` but that didn't solve my problem.

**Comment by mfischer-zd** [comment]
Here are the options for the subsequent download, as reported by aria2.getOption:

```json
{
   "allow-overwrite":"false",
   "allow-piece-length-change":"false",
   "always-resume":"true",
   "async-dns":"true",
   "auto-file-renaming":"true",
   "bt-enable-lpd":"false",
   "bt-force-encryption":"false",
   "bt-hash-check-seed":"true",
   "bt-max-peers":"55",
   "bt-metadata-only":"false",
   "bt-min-crypto-level":"plain",
   "bt-remove-unselected-file":"false",
   "bt-request-peer-speed-limit":"51200",
   "bt-require-crypto":"false",
   "bt-save-metadata":"false",
   "bt-seed-unverified":"false",
   "bt-stop-timeout":"0",
   "bt-tracker-connect-timeout":"60",
   "bt-tracker-interval":"0",
   "bt-tracker-timeout":"60",
   "check-integrity":"true",
   "conditional-get":"false",
   "connect-timeout":"60",
   "continue":"false",
   "dir":"/home/centos",
   "dry-run":"false",
   "enable-http-keep-alive":"true",
   "enable-http-pipelining":"false",
   "enable-mmap":"false",
   "enable-peer-exchange":"false",
   "file-allocation":"prealloc",
   "follow-metalink":"true",
   "follow-torrent":"true",
   "force-save":"false",
   "ftp-pasv":"true",
   "ftp-reuse-connection":"true",
   "ftp-type":"binary",
   "hash-check-only":"false",
   "http-accept-gzip":"false",
   "http-auth-challenge":"false",
   "http-no-cache":"false",
   "lowest-speed-limit":"0",
   "max-connection-per-server":"1",
   "max-download-limit":"0",
   "max-file-not-found":"0",
   "max-resume-failure-tries":"0",
   "max-tries":"5",
   "max-upload-limit":"0",
   "metalink-enable-unique-protocol":"true",
   "metalink-preferred-protocol":"none",
   "min-split-size":"20971520",
   "no-file-allocation-limit":"5242880",
   "no-netrc":"false",
   "parameterized-uri":"false",
   "pause-metadata":"false",
   "piece-length":"1048576",
   "proxy-method":"get",
   "realtime-chunk-checksum":"true",
   "remote-time":"false",
   "remove-control-file":"false",
   "retry-wait":"0",
   "reuse-uri":"true",
   "rpc-save-upload-metadata":"false",
   "seed-ratio":"0",
   "split":"5",
   "stream-piece-selector":"default",
   "timeout":"60",
   "uri-selector":"feedback",
   "use-head":"false",
   "user-agent":"aria2/1.18.10"
}
```

**Comment by tatsuhiro-t** [comment]
Option values are all strings.
http://aria2.sourceforge.net/manual/en/html/aria2c.html#id3

We'll look into the remaining issues.

**Comment by mfischer-zd** [comment]
Thank you - looking forward to a fix.

**Comment by tatsuhiro-t** [comment]
As for numSeeders, it is the number of connected peers which are seeding torrent, excluding the local client itself.  I think the current display is correct.  First case, there is still 1 seed peer, so numSeeders=1 is corrent. Second case, since the number of connections is 0, numSeeders should be 0.

**Comment by mfischer-zd** [comment]
In the second case, shouldn't the number of connections also be 1?  My expectation is that the behavior when the second time the torrent is added (even though it's now just seeding) should be identical to the state after the first time the torrent has completed downloading and is seeding.

**Comment by tatsuhiro-t** [comment]
In this case, no, since number of connection is 0:
```
 "connections":"0",
```

We count number of seeders in connected peers, with no other knowledge involved.

**Comment by mfischer-zd** [comment]
I'm puzzled, then, because the number of connections after the peer transitioned to seeding mode on the first download was 1, not 0.

**Comment by tatsuhiro-t** [comment]
That depends on the situation and implementation of torrent client.  Some client may drop connection if peer gets seeder, some might not.

**Comment by mfischer-zd** [comment]
The only two peers in this test are both Aria2 clients (same version).

**Comment by tatsuhiro-t** [comment]
OK, aria2 drops connection if both local client and peer are seeder.
There are some delays this disconnection occurs (probably 1 second).
I tried some experiments, after download completion, with 1 second, numSeeders gets 0.
I now fully understand why you wrote https://github.com/tatsuhiro-t/aria2/issues/355#issuecomment-84325850, this thread is a bit convoluted.

**Comment by tatsuhiro-t** [comment]
And.. the delay is not always 1 second.  In other words, it is less than about 1 second.

I think the remaining issue is aria2 does not call the command specified in on-bt-download-complete, right?  I confirmed this behaviour. Since on-download-complete hook is invoked with -V option, I think on-bt-download-complete should be invoked too.

**Comment by mfischer-zd** [comment]
Correct.  Looking forward to a fix.

**Comment by tatsuhiro-t** [comment]
Fixed on-bt-download-complete issue.

Does my explanation of numSeeders make sense?  Then I think we can close this issue.

**Comment by mfischer-zd** [comment]
Yes - I only mentioned numSeeders as I suspected that its value and the lack of notification were related, but I was apparently incorrect.

I applied your patch to the CentOS 7 extras RPM.  It appears to resolve the problem.  Many thanks for the quick response.
