### ISSUE TITLE
an extra space in `usage_text.h`

### ISSUE THREAD

**Issue by Javran** [tatsuhiro-t/aria2#356]
I spotted an extra space in [usage_text.h](https://github.com/tatsuhiro-t/aria2/blob/master/src/usage_text.h#L153`) file (i.e. the space between `#` and `define`, please follow the link).
Technically this is not a bug, I'm writing a tool that parses this file to get info about valid command line options and removing that space will make life a little bit easier :)

**Comment by tatsuhiro-t** [comment]
Thank you for letting us know.  The source code was fixed just now.

**Comment by Javran** [comment]
Thanks!
