### ISSUE TITLE
not saving session 

### ISSUE THREAD

**Issue by ghostry** [tatsuhiro-t/aria2#363]
This version 1.18.7 can not save the download list on OpenWrt trunk. Even if I use the parameter

>save-session-interval=5
>force-save=true
>input-file=/mnt/sda1/.aria2/aria2.session
>save-session=/mnt/sda1/.aria2/aria2.session
>rpc-save-upload-metadata=true

I also tried version 1.18.9.

**Comment by tatsuhiro-t** [comment]
I could not reproduce this on my Debian box.
Do you see anything suspicious in log message?
aria2 shows error when it failed to save files.

**Comment by ghostry** [comment]
Diary of aria2 where to find?

**Comment by ghostry** [comment]
Sorry, because of lack of competence

**Comment by tatsuhiro-t** [comment]
You can use -l option to specify log file name.

**Comment by ghostry** [comment]
Sorry, because I did not write to the session file permissions, it can not be saved. You can turn off this issue.

**Comment by tatsuhiro-t** [comment]
OK.
