### ISSUE TITLE
aria2c use proxy for hostname lookups BT ?

### ISSUE THREAD

**Issue by qiuzi** [tatsuhiro-t/aria2#369]
How to use HTTP proxy BT trackers link ?

**Comment by tatsuhiro-t** [comment]
Use http://aria2.sourceforge.net/manual/en/html/aria2c.html?highlight=http-proxy#cmdoption--http-proxy
Or environment variables: http://aria2.sourceforge.net/manual/en/html/aria2c.html?highlight=http-proxy#environment
Please read manual about proxy

**Comment by qiuzi** [comment]
BT only use a proxy, http remain directly connected
Similar to uTorrent agent

**Comment by tatsuhiro-t** [comment]
I've never used uTorrent so don't know how its agent works.
You asked us how to use http proxy to connect BitTorrent tracker, and I showed you how to.
It seems it works from your saying "BT only use a proxy".
So I think this issue can be closed.  Does it work for you?

**Comment by tatsuhiro-t** [comment]
Closed since we have option to specify HTTP proxy.
