### ISSUE TITLE
When using like this: `-Vtrue --checksum=md5=96528defee417b3cf0d400eeb26d7df8', does the -Vtrue need or not for this case?

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#370]
Dear Tatsuhiro,
 
Firstly, thanks a lot for your powerful tool aria2c though I only know it sereral day ago.

Now, I have the following question when using the arguments of  `-Vtrue' and `--checksum' at the same time for http/https/ftp uris.

See the following example used by me for now to obtain some Debian's packages:

aria2c -c -x1 -s40 -k1M -j40 \
--async-dns-server=8.8.8.8,8.8.4.4 \
--lowest-speed-limit=512K --dir=aaa/bbb \
-Vtrue --checksum=md5=96528defee417b3cf0d400eeb26d7df8 \
--auto-save-interval=10 --file-allocation=falloc  \
`paste -sd' ' mDMCTodayHttp.list  `

In the above example, the content of file mDMCTodayHttp.list are a lot of uri of Debian's packages using the http/https/ftp protocols.

My question is as follows:

According to the manual of aria2c, I can find the following descriptions:

       --realtime-chunk-checksum[=true|false]
              Validate chunk of data by calculating checksum while downloading
              a file if chunk checksums are provided.  Default: true

So, considering that for my above example, I also used the  --checksum argument as follows:
 
--checksum=md5=96528defee417b3cf0d400eeb26d7df8

Does this mean the file's checksum checking will be doing while  downloading?

If so, the should I use the `-Vtrue' argument or not for my case?  I mean, if the `-Vtrue' is a redunant argument for my above usages and should be omitted from the arguments list of aria2c for my case?

Regards.
H.Zhao

**Comment by tatsuhiro-t** [comment]
--realtime-chunk-checksum works with chunk checksum, which are available via .torrent file or .metalink file.  The checksum specified by --checksum is not "chunk checksum", so --realtime-chunk-checksum is irrelevant.
Usually, --checksum is checked after transfer completed.
With -V option, validation will run, before the transfer, against the existing file, so that  if validation fails, aria2 will download the file again.
Without -V option, by default, if control file (*.aria2) does not exist, aria2 automatically rename the file appending "." + numeric value, and download the file and verify its integrity.  If control file exists, aria2 resumes download, and after completion, validate the checksum.

**Comment by hongyi-zhao** [comment]
Got it, thanks a lot.
My another confusion is on the differences and relationship among the terminologies of  piece/chunk/min-split-size used by aria2.  
I've tried to figure out them clearly based the manual, but still not-so-clearly on them.

Any hints?
Regards
H.Zhao

**Comment by tatsuhiro-t** [comment]
Usually, piece and chunk have the same meaning.  Originally, "piece" came from BitTorrent terminology, and it only used for BitTorrent download.  In early days, they may have different meanings, but aria2 unified BitTorrent and HTTP/FTP downloads, so mostly they are identical.

**Comment by hongyi-zhao** [comment]
Ok, thanks.

But I'm still not so sure about the following thing:

If I setting the following two arguments at the same time:

--piece-length=<LENGTH>
and
-k, --min-split-size=<SIZE>

From the manpage, I can find the following description:
------------
       --piece-length=<LENGTH>
              Set  a piece length for HTTP/FTP downloads. This is the boundary
              when aria2 splits a file. All splits occur at multiple  of  this
              length. 
[snip]
------------

So, it seems that the the following relation holds: <SIZE> = n*<LENGTH>

Am I right?

In addition, you didn't told that the value for  <LENGTH> of `--piece-length' must obey tha above relationship in the manual.  So if setting these two arguments not according to <SIZE> = n*<LENGTH>, then what will happen?

Regards

**Comment by hongyi-zhao** [comment]
Sorry for my not-using markdown.

I mean the  it seems that the the following relation holds: 
   SIZE_of_min-split-size   = n * LENGTH_piece-length

If I don't obey this relation to setting these two arumtents, then what will happen?

**Comment by tatsuhiro-t** [comment]
--min-split-size exists to prevent HTTP range request from being too small.
--min-split-size and --piece-length can be set independently.
The smallest HTTP range request becomes max(min-split-size, piece-length).
If piece-length < min-split-size, split still occurs in piece-length boundary, but aria2 does not make split smaller than min-split-size.

**Comment by hongyi-zhao** [comment]
Thanks for your hints.

As you mentioned in the manual, the default `--piece-length=1M',
and the also the default  `--min-split-size=1M' too.

But, according to your previous depiction, in fact, I can use any size for `--piece-length' theoretically  and use 1M -1024M size of `--min-split-size', am I right?
 
Regards

**Comment by tatsuhiro-t** [comment]
Yes, you can set arbitrary size for these options.  I think default value is good enough for most cases.

**Comment by hongyi-zhao** [comment]
By saying that `set arbitrary size for these options',    still they must first confirm to the possiable range you have setted in the default range, i.e., as follows:

  --piece-length=LENGTH
   [snip]
                                Possible Values: 1048576-1073741824
                              Default: 1M

   -k, --min-split-size=SIZE
   [snip]
                              Possible Values: 1048576-1073741824
                              Default: 20M
 I want to know why you let the miminal value of  `--piece-length' to 1M, instead of more little values, say, 64K, and so on?

Or ,why not let the user can setting a more flexiable range for  `--piece-length' below 1M?

Regards

**Comment by tatsuhiro-t** [comment]
Of course, you can do in the range you are allowed.
The reason why we put the this limitation is avoid misuse, e.g., too small segment to request web server, which degrades performance.

**Comment by hongyi-zhao** [comment]
But, considering the following case:

If I have a huge of lilltle files with the size ranges from 0-2M which I want to retrieve them from serveral mirrors. In this case, I must let the `--piece-length'  and `-k, --min-split-size' have the chances to be set  `<= 1M', so that I can parallelly using all of these sites will appropriate paralleziation performance.

Regards

**Comment by tatsuhiro-t** [comment]
May be or may be not.
1M is small enough these days, and splitting into smaller pieces is not necessarily faster; it is even slower due to several reasons, e.g., connection setup cost, and tcp slow start, etc.

**Comment by hongyi-zhao** [comment]
Thanks for your hints.

**Comment by sergeevabc** [comment]
``` console
$ aria2c https://domain.suffix/file.ext --checksum=sha-256=…
[ERROR] Checksum error detected.
```
Checksum is wrong, file might have been forged, yet it is already on the disk and tomorrow nobody will remember of it.
Question is, could we make Aria2c remove file if checksum is wrong? By means of extra switch or something like that?
