### ISSUE TITLE
About the separator for multiple URIs of a single entity in the input-file.

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#372]
Dear Tatsuhiro,

You said in the manual that:

       -i, --input-file=<FILE>
              Downloads  the  URIs  listed  in  FILE. You can specify multiple
              sources for a single entity by putting multiple URIs on a single
              line  separated by the TAB character.

Why it must use the TAB as the separator for multiple URIs of a single entity in the input-file?  I mean, why not let either SPACE or TAB as the separator to facilitate the preparation for the input-file? 

Regards

**Comment by tatsuhiro-t** [comment]
That's because file path can be specified there and it can contain spaces.  OTOH, tab is most likely not included there.
