### ISSUE TITLE
How can control the maximum number of concurrent connnections to a server from different instances of aria2.

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#373]
Hi Tatsuhiro,

See the following example:

   for i in `seq 1 100`; do
     aria2c -x1 -j1 http://ftp.cn.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz -l ${i}_log --log-level=warn &
  done

In the above case, the `-x1 -j1' only apply to the instance of aria2 from which it issued. 

As a result, I'll simultaneously run 100 concurrent connnections to the same server.  So, how can I control the maximum number of concurrent connnections to a server from different instances of aria2?

Regards

**Comment by tatsuhiro-t** [comment]
There is no way to control concurrent connections between multiple instance of aria2c.
One instance of aria2 can handle multiple downloads.  So if you want to control concurrency limit, you need to push all downloads into 1 aria2 instance.
