### ISSUE TITLE
About the algorithm for adaptive used in  `--uri-selector' argument.

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#374]
Dear Tatsuhiro,

I try to figure out the mechanism of `--uri-selector=adaptive', based on the description in the manual.  And I find the fllowing things on it:

       --uri-selector=<SELECTOR>
             [snip]
              If  adaptive  is given,  selects  one  of  the  best  mirrors  
              for  the first and reserved connections.  For supplementary ones,
              it  returns  mirrors  which  has  not  been  tested yet, and if
              each of them has already been tested, returns mirrors  which  has
              to  be  tested again.  Otherwise, it doesn't select anymore mirrors.
              Like feedback, it uses a performance profile of servers.

I've read serveral times on the above descrption, but still not-so-clearly understand it.

And then, I try to use the following options to do the testing on this argument:
        
        --server-stat-timeout=6000 \
        --server-stat-of=aaaa \
        --server-stat-if=aaaa  \
        --uri-selector=adaptive

Could you please give me some more hints on the  algorithm/mechanism for the  `--uri-selector=adaptive', say, for my above example?

Regards
H.Zhao

**Comment by tatsuhiro-t** [comment]
Basically, adaptive select fastest one first, just like feedback, but to discover better server from unused servers, it speculatively selects unused one as secondary URI.
