### ISSUE TITLE
Sometimes, aria2c will give a very slow speed for downloading.

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#375]
Hi Tatsuhiro,

See my following  aria2c console log:

	werner@debian:~/aria2-relative$ bash aria2-dmirror.sh

	05/03 21:16:58 [NOTICE] ServerStat file server-stat.log loaded successfully.
	[#2b8361 12MiB/39MiB(32%) CN:5 DL:0B]                                           
	05/03 21:17:10 [ERROR] CUID#11 - Download aborted. URI=http://debian.advalem.net/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz
	Exception: [AbstractCommand.cc:350] errorCode=3 URI=http://debian.advalem.net/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz
	  -> [HttpSkipResponseCommand.cc:215] errorCode=3 Resource not found
	[#2b8361 12MiB/39MiB(32%) CN:5 DL:0B]                                           
	05/03 21:17:14 [NOTICE] Lowering lowest-speed-limit since known max speed is too near (new:3174 was:524288 max:12696)
	[#2b8361 12MiB/39MiB(32%) CN:5 DL:241B ETA:31h50m17s]                           
	05/03 21:17:25 [NOTICE] Lowering lowest-speed-limit since known max speed is too near (new:3174 was:524288 max:12696)
	[#2b8361 12MiB/39MiB(32%) CN:5 DL:305B ETA:25h9m26s]                             
	05/03 21:17:26 [NOTICE] Lowering lowest-speed-limit since known max speed is too near (new:35 was:524288 max:141)
	[#2b8361 12MiB/39MiB(32%) CN:5 DL:579B ETA:13h15m7s]                             
	05/03 21:17:28 [NOTICE] Lowering lowest-speed-limit since known max speed is too near (new:35 was:524288 max:141)
	[#2b8361 12MiB/39MiB(32%) CN:5 DL:1.6KiB ETA:4h37m]                              
	05/03 21:17:30 [NOTICE] Lowering lowest-speed-limit since known max speed is too near (new:35 was:524288 max:141)
	[#2b8361 12MiB/39MiB(32%) CN:5 DL:215B ETA:35h41m18s]^C                          
	05/03 21:17:48 [NOTICE] Lowering lowest-speed-limit since known max speed is too near (new:35 was:524288 max:141)

	05/03 21:17:48 [NOTICE] Shutdown sequence commencing... Press Ctrl-C again for emergency shutdown.

	05/03 21:17:48 [NOTICE] Download GID#2b8361226e47e06c not complete: dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz

	05/03 21:17:48 [NOTICE] ServerStat file server-stat.log saved successfully.

	Download Results:
	gid   |stat|avg speed  |path/URI
	======+====+===========+=======================================================
	2b8361|ERR |     369B/s|dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz

	Status Legend:
	(ERR):error occurred.

	aria2 will resume download if the transfer is restarted.
	If there are any errors, then see the log file. See '-l' option in help/man page for details.

	05/03 21:17:48 [NOTICE] Serialized session to 'save-session.log' successfully.

As you can see, the speed is so slow.  And at the meanwhile, if I testing any of the uri used by aria2c via curl, I can see the speed is not-so-slow.

Any hints on this issue?

Regards

**Comment by tatsuhiro-t** [comment]
Some servers suddenly choke the transfer speed drastically, especially if several connections are made.
Could you give me URLs included in  aria2-dmirror.sh?

**Comment by hongyi-zhao** [comment]
Dear

The  aria2-dmirror.sh is a script which I used to generate the input-file for aria2c and then invoking the aria2c from this script.

For the URLs included for the above example, in fact, it's read in from another url.list file and assigned to each file to download by some rule of thume.  For my case, I assign the number of urls to each file according to its size, say, every 1M-2M giving a mirror-url for using.  

So, in this csae, the file to be downloaded has a size approximately 39MiB, and I assign 20 mirror urls for using by aria2c to downloading this file.

See the following for detail:
 http://artfiles.org/debian/
http://be.mirror.eurid.eu/debian/
http://buaya.klas.or.id/debian/
http://carroll.aset.psu.edu/pub/linux/distributions/debian/
http://cdimage.debian.org/debian/
http://debian.advalem.net/debian/
http://debian.anexia.at/debian/
http://debian.asis.io/debian/
http://debian.balt.net/debian/
http://debian.bhs.mirrors.ovh.net/debian/
http://debian.bjtu.edu.cn/debian/
http://debian.bononia.it/debian/
http://debian.bsnet.se/debian/
http://debian.c3sl.ufpr.br/debian/
http://debian.cabletel.com.mk/debian/
http://debian.carnet.hr/debian/
http://debian.cc.lehigh.edu/debian/
http://debian.cites.illinois.edu/pub/debian/
http://debian.co.il/debian/
http://debian.csail.mit.edu/debian/

I must also told you that, even with same urls, sometimes,  the speed of aria2c are good, but sometimes are so bad. It seems its so unstable.  And I cann't figure out debug it and told you the information for analysis.

Could you please give me some more hints?

Thanks.

**Comment by tatsuhiro-t** [comment]
Thank you for the info.
It is difficult to deal with this kind of problem.  Given the diversity of the server domain, it is sometime faster and sometimes slower.
aria2 just checks socket is readable, and if it is, aria2 reads it.
