### ISSUE TITLE
Unable to output to ~

### ISSUE THREAD

**Issue by Dialga** [tatsuhiro-t/aria2#377]
When running aria2c -o ~/Downloads url
I expected aria2c to save the output file into the Downloads folder in my home directory, but instead it
saves it recreates my home directory in the current directory and saves the downloaded file as Downloads. This is not the expected behavior of -o

**Comment by tatsuhiro-t** [comment]
Probably you should use -d option instead of -o in this case.

**Comment by quuiqueee** [comment]
@Dialga The parameter "-o" is for set the file name, if you want set the download directory you must use "-d". In this case, the correct command is the following:

$ aria2c [URL] -d ~/Downloads

If for example, you want download a file with the name "movie.avi" in "~/Downloads" directory, the command is the following:

$ aria2c [URL] -d ~/Downloads -o movie.avi

**Comment by Dialga** [comment]
Oh right, my mistake.
