### ISSUE TITLE
Mac OS X Artifact is missing (1.19.0)

### ISSUE THREAD

**Issue by tommyziegler** [tatsuhiro-t/aria2#396]
When I try to download the new Version 1.19.0 for Mac OS X I saw that the binary is missing.

Has that some reason or is it a mistake?

> aria2-1.19.0-osx-darwin.tar.bz2

Greets

Tommy

**Comment by tatsuhiro-t** [comment]
Usually @nmaier kindly offered us Mac OS X packages, and is probably busy now.  I don't have Mac, so I cannot help you here.  You may find aria2 in homebrew or other prepackaged registry.

**Comment by nmaier** [comment]
Yeah, I was off for a while...
Anyway, @tatsuhiro-t and @tommyziegler here is my darwin build, freshly compiled:
https://tn123.org/aria2/aria2-1.19.0-osx-darwin.dmg
https://tn123.org/aria2/aria2-1.19.0-osx-darwin.tar.bz2

**Comment by tommyziegler** [comment]
Thx a lot 

Is it possible that you can give your build script / manual?

I would Love to automate it when i habe more Details how.

Thx

Tommy

**Comment by nmaier** [comment]
It's in the repo already, see https://github.com/tatsuhiro-t/aria2/blob/master/makerelease-osx.mk

**Comment by tommyziegler** [comment]
But the problem is that there are no informations about the dependencies on a fresh Mac OS X 10.10.

I have the newest Xcode and I try to install the dependencies like Sphinx, autoreconf etc. via brew.

A description for a blank system would be great.


Thx

**Comment by tatsuhiro-t** [comment]
Thank you, and welcome back @nmaier.  I just uploaded 2 files to sf.net.
