### ISSUE TITLE
About the meaning of ``queue``.

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#397]
Hi Tatsuhiro,

I noticed that the terminology ``queue`` used serveral times in the manual of aria2c. Say the following one:

       -j, --max-concurrent-downloads=<N>
              Set the maximum number of parallel  downloads  for  every  queue
              item.  See also the --split option.  Default: 5

But, I still not so clear whether all of the  terminology ``queue`` used in the manual of aria2c are meaning the same thing or not.

Say, for example, the above one I mentioned here, I think it should mean that _one_ aria2c command will construct only _one_  ``queue`` for downloading, and each downloading file is a item of this ``queue``.  Am I right or not?

Regards
H.Zhao

**Comment by tatsuhiro-t** [comment]
Basically, yes.  Some download type may contain several files to download (e.g., multi-file torrent).

**Comment by hongyi-zhao** [comment]
So, do you mean, in this case, one queue item will corresponding to several files?

Regards

**Comment by tatsuhiro-t** [comment]
In that particular case, yes.
