### ISSUE TITLE
Conform to PEP 394

### ISSUE THREAD

**Issue by wasamasa** [tatsuhiro-t/aria2#398]
https://www.python.org/dev/peps/pep-0394/

More specifically, running mkapiref.py fails on an Archlinux system as the hashbang points to python which points to Python 3 instead of Python 2 on it and errors out as print is no longer a statement.

I can think of two ways of solving this. The easy way would be using python2 instead which should work on every platform worth supporting. The slightly harder way would be making the script work for both Python 2 and 3 which is simple enough, just insert `from __future__ import print` at the top and turn all print statements into function calls by using parentheses around the arguments (an empty string as argument can be just omitted). That way would work for all currently supported Python 2 versions (which would be 2.6 and 2.7).

Which of the two options do you prefer?

**Comment by tatsuhiro-t** [comment]
I prefer future import print to just sticking to python2.
Could you send us PR for this?

**Comment by wasamasa** [comment]
Closing in favour of the linked PR.
