### ISSUE TITLE
aria2c -x1 -j2 ...

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#402]
Hi Tatsuhiro,

See my following output of aria2c:

   $ aria2c -x1 -j2 -m1 -t60 --lowest-speed-limit=10K --download-result=full  http://ftp.uk.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz http://ftp.cn.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz
 *** Download Progress Summary as of Thu Jun  4 10:28:03 2015 ***              
  =======================================================
[#281497 17MiB/39MiB(44%) CN:1 DL:40KiB ETA:9m10s]

As you can see, I use  ``-x1 -j2`` in my case, which means:

    --max-connection-per-server=1
      and
     --max-concurrent-downloads=2

So, for my case, I should observed the  ``CN:2`` result in my Console Readout for the progress of the downloads.  Why I only see the ``CN:1`` for my case?

Regards
H.Zhao

**Comment by binux** [comment]
http://aria2.sourceforge.net/manual/en/html/aria2c.html#cmdoption-k

**Comment by hongyi-zhao** [comment]
Thanks for that hints.

Another issue:  

It seems the following two commands are equivalent:

$ aria2c -x2 -k1M "http://host/file.zip"
and
$ aria2c -x2 -k1m "http://host/file.zip"

But, the manal page only says the usage of  ``-k1M``.

Any hints?

Regards

**Comment by hongyi-zhao** [comment]
I do the further testing with the following commands:

  werner@debian:~$ aria2c -k1M -x5 -j1 -m1 -t60 --lowest-speed-limit=10K --download-result=full  http://ftp.uk.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz http://ftp.cn.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz http://ftp.us.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz http://ftp.kr.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz http://ftp.tw.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz http://ftp.jp.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz
[#cea971 14MiB/39MiB(37%) CN:5 DL:152KiB ETA:2m44s]^C                          
06/04 11:07:47 [NOTICE] Shutdown sequence commencing... Press Ctrl-C again for emergency shutdown.

06/04 11:07:47 [NOTICE] Download GID#cea971a0851ecfd7 not complete: /home/werner/boot.img.gz

Download Results:
gid   |stat|avg speed  |  %|path/URI
======+====+===========+===+===================================================
cea971|INPR|   145KiB/s| 28|/home/werner/boot.img.gz

Status Legend:
(INPR):download in-progress.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
werner@debian:~$ 

 Why this time I will obtian the ``CN:5``, I still cann't figure out this issue.

Any hints?

Regards

**Comment by binux** [comment]
Read the manual before ask.
http://aria2.sourceforge.net/manual/en/html/aria2c.html#cmdoption-s

**Comment by hongyi-zhao** [comment]
Thanks,

 Even so, the ``-k1m`` don't mentioned in the manpage, but it still can be used just as the same as ``-k1M``.

Regards

**Comment by tatsuhiro-t** [comment]
We accept both lower and upper M and K for convenience.  The official one is upper case ones here, so stick to them.
