### ISSUE TITLE
The large differences between the dl_speed and mc_avg_speed.

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#403]
Hi Tatsuhiro,

I use the following command with aria2c:

    aria2c -s30 -k1M -x2 -j5 -m1 -t60 -Vtrue --checksum=md5=96528defee417b3cf0d400eeb26d7df8 --lowest-speed-limit=16316 --server-stat-of=server-stat.log --server-stat-if=server-stat.log --uri-selector=feedback --download-result=full ftp://ftp.uk.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz ftp://ftp.cn.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz ftp://ftp.us.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz ftp://ftp.kr.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz ftp://ftp.tw.debian.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz

Then, in the server-stat.log, I obtian the following contents:

   host=ftp.cn.debian.org, protocol=ftp, dl_speed=213716, sc_avg_speed=0, mc_avg_speed=165326, last_updated=1433411588, counter=9, status=OK
host=ftp.kr.debian.org, protocol=ftp, dl_speed=62148, sc_avg_speed=0, mc_avg_speed=68107, last_updated=1433411588, counter=9, status=OK
host=ftp.tw.debian.org, protocol=ftp, dl_speed=38615, sc_avg_speed=0, mc_avg_speed=75449, last_updated=1433411588, counter=9, status=OK
host=ftp.uk.debian.org, protocol=ftp, dl_speed=37323, sc_avg_speed=0, mc_avg_speed=41737, last_updated=1433411588, counter=8, status=OK
host=ftp.us.debian.org, protocol=ftp, dl_speed=26992, sc_avg_speed=0, mc_avg_speed=31875, last_updated=1433411588, counter=9, status=OK

As you can see, for some servers, there are large differences between the dl_speed and mc_avg_speed.  Any hints on this issue?

Regards

**Comment by tatsuhiro-t** [comment]
We have different calculations when calculating mc_avg_speed from dl_speed.  It is a bit complex, this is due to the fact that it originates a well-known Linux distro's package manager integration code.  In short, mc_avg_speed is conservative to the new speed updates.

**Comment by hongyi-zhao** [comment]
But, it seems all of these speeds may be fluctuated in a very large range when I testing with a little file.

Regards
