### ISSUE TITLE
Should we get away from sf.net?

### ISSUE THREAD

**Issue by tatsuhiro-t** [tatsuhiro-t/aria2#407]
With the recent bad news, sf.net loses its credibility from OSS community.
I heard that curl project now completely transitioned into github.
Should we also consider this kind of move?
sf.net recently removes many functionality, including trac and its wiki, so we actually not depend on the unique feature of sf.net.  Perhaps, sf.net mirror system may be useful, but its file management UI is horrible, and slow.

**Comment by bagder** [comment]
That mirroring system is most likely not something you need very much anyway (I'm guessing). If you need help to host download files for aria2 I'm convinced you will find volunteers to help you. Just let us know!

And yes, the curl project finally moved the last service off SF a while ago. I think their services have degraded over the years and their site is mostly annoying to navigate, so it drove us away. Then this abuse case surfaces and I'm glad we already left them...

**Comment by tatsuhiro-t** [comment]
Thank you.  The download volume is not a lot nowadays, just less than 2,000 per week, which I think can be handled quite well in github release page.

**Comment by tatsuhiro-t** [comment]
The one publicly visible change is web site URL.  For years, we use aria2.sourceforge.net, we can redirect to our new home.  Using github pages could be handy.  Perhaps, we move aria2 repo to aria2 organization, and get aria2.github.io, which is nicer than put them under my account.

**Comment by scytalezero** [comment]
I think that you should move away from sf.net. Personally, I just don't trust them anymore and I always second-guess files I download from them.

**Comment by nmaier** [comment]
Yeah.
Also there are services like https://bintray.com/ which handle binary distribution quite well and are free for open source projects

**Comment by tatsuhiro-t** [comment]
Thank you all for comments.  No one want to stay with sf.net, so let's move to github.
From sf.net stats, we have 1000+ download/week, and it is not that big.  I think we can host files on github.  If we have any problem, then consider another, such as bintray.

We have used aria2.sourceforge.net as project web site, which is offline now due to sf.net maintenance.
On github, it will become https://tatsuhiro-t.github.io/aria2, or https://aria2.github.io/aria2 after creating aria2 organization.  Alternatively, we can move to under metalinker-dev org, and gets the address https://metalinker-dev.github.io/aria2.   Either is fine for me.

We don't migrate issues from sf.net to here, because it is too much manual labor.
We also don't migrate past downloads.  Perhaps, we can just add latest release here.

**Comment by nmaier** [comment]
If you get the org you can have https://aria2.github.io/ ;)

Regarding downloads, rehosting (most of) the old downloads here wouldn't be not much of a problem either, there is a release API so it can be scripted. But that isn't much of a concern, I agree.

**Comment by sonnyp** [comment]
@tatsuhiro-t I have created the organization and invited you as owner

https://github.com/aria2
http://aria2.github.io/

Feel free to remove me from owners once you're setup;

**Comment by tatsuhiro-t** [comment]
@sonnyp Thank you!
We'd like to limit the member of aria2 org for core developers only, so we are going to remove you.  Sorry about that.

**Comment by sonnyp** [comment]
@tatsuhiro-t no worry there is no reason for me owner of the project

**Comment by sonnyp** [comment]
Any news ? Ublock origin (and possibly others) now blocks sourceforge.net

**Comment by tatsuhiro-t** [comment]
Things are going a bit slow about this issue.
But recent downloads are already hosted in github.
I will do migration to aria2 org when I have time.
We also need the associated documentation updates.

**Comment by tatsuhiro-t** [comment]
I manged to move aria2 website to https://aria2.github.io/.
All useful contents are redirected to the corresponding new pages.

**Comment by tatsuhiro-t** [comment]
Now that we have moved all contents from sourceforge to github, let's close this issue.
Moving this repository to aria2 org is an another issue.

**Comment by sonnyp** [comment]
@tatsuhiro-t great! thanks, is there any way to close http://aria2.sourceforge.net/ or maybe notice about the change?

**Comment by tatsuhiro-t** [comment]
When it is accessed, client is redirected to new page.  We will add some notice in the next release.  Do you think it is not enough?

**Comment by sonnyp** [comment]
@tatsuhiro-t hmm index doesn't redirect, only links (documentation, ....) but I guess that's good enough

**Comment by sonnyp** [comment]
For the repository, a simple github move repository should do the trick easily, github will take care of all redirections.

**Comment by sonnyp** [comment]
@tatsuhiro-t can you change the repo website on https://github.com/tatsuhiro-t/aria2  ?

**Comment by tatsuhiro-t** [comment]
Done!
