### ISSUE TITLE
Obtain the Server Performance Profile for a lot of servers.

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#408]
Hi Tatsuhiro,

I've the following idea:

I've a lot of uris of the Debian mirror site, if I can obtian the Server Performance Profile for all of them before the downloading, then the subsequent downloading will be more efficient based on the pre-made Server Performance Profile.

For the above purpose, I first make a input-file which including the following contents ( thtere are 324 lines in it totally):

[content of the input-file]

  ftp://artfiles.org/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz
ftp://buaya.klas.or.id/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz
ftp://carroll.aset.psu.edu/pub/linux/distributions/debian/dists/jessie/main/installer-amd64/current/images/hd-media/boot.img.gz
[snip]

Then I use the following command to obtain the Server Performance Profile for all of these servers:

       aria2c -j324 -k1M --stop=60 --disable-ipv6 --server-stat-of=server-stat.log --file-allocation=none -iinput-file -d/tmp -x2

Then, after 60 seconds, I will obtain the Server Performance Profile for all of these servers which stored in the file named server-stat.log.

But, I'm not so sure about the correctness/accuracy on the Server Performance Profile obtained by the above method.  Any hints/suggestions on my above idea?

Regards
H.Zhao

**Comment by tatsuhiro-t** [comment]
We have no guarantee about correctness nor accuracy.  We record the value we just measured.
