### ISSUE TITLE
Downloading several files from different URIs, redirecting them to /dev/null, and don't gernerate the control file at all. 

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#409]
Hi Tatsuhiro,

I want to do testings on serveral URIs, so I want to doing the following thing:

Downloading several files from different URIs, redirecting them to /dev/null, and don't gernerate the control file at all. 

How to do it?

Regards

**Comment by tatsuhiro-t** [comment]
Use -d /dev -o null  for HTTP/FTP downloads.  You cannot achieve this in BitTorrent download.
Also you cannot disable control file creation in aria2.

You created lots of issues these days (which itself is valid and good), and if you satisfied with the answer, please close the issues.

**Comment by hongyi-zhao** [comment]
Thanks a lot, I'll check these issues, some of them has follow-ups which posted by me for still not-clear issues.  If not so, I will close them.

Regards
