### ISSUE TITLE
Obtain the information on the  completed split blocks and  partially completed split blocks in a file?

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#410]
Hi Tatsuhiro,

Considering that the aria2c using the *.aria2 for resuming the downloading, it must mean that the downloading-status information are stored  in that file, but it's not a human readable file.

So, how to obtain the status of the downloading for a file, especially the  completed split blocks and  partially completed split blocks in a file?

Regards

**Comment by tatsuhiro-t** [comment]
http://aria2.sourceforge.net/manual/en/html/technical-notes.html#control-file-aria2-format

**Comment by hongyi-zhao** [comment]
Thanks a lot, I've looked it, and some further things which I want to obtained are as follows based on your above technical-notes on control-file-aria2-format:

[1] It seems that the critical stuff for figuring out the real-time completedLength of a file is BITFIELD relative parts in the control-file.  But, the file itself is a binary one, even can be readout, I still must to do futher calculation for figure out the  real-time completedLength of a file based on the technical-notes.

So, is there some convenient method for me to obtain the real-time completedLength of a file?

[2] I've noticed that you mentioned the following thing in the manpage:

aria2.tellStatus([secret], gid[, keys])

and

aria2.getFiles([secret], gid)

Both of the above two methods can return the completedLength information.

I've tried to use of them but failed due to I'm lacking on the knowledge about python.

Could you please give me some more hints for my purpose: obtain the real-time completedLength of a file?

Regards

**Comment by tatsuhiro-t** [comment]
Using RPC method is a way to go.  It is XML or JSON based RPC, we just use Python language as an example.  Please read manual carefully.  I think we don't use advanced aspect of Python.
