### ISSUE TITLE
Is it possiable to use the libaria2 to readout the contents of *.aria2?

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#412]
Hi Tatsuhiro,

I've two issues relative to this topic：

[1] I still want to read out the  contents of *.aria2 by myself, I inspect the source codes  of aria2 and find the following files: 

src/SegmentMan.cc

But it seems that invoke so much header and functions for analysis and reading out the segment file. I'm lost in it ;-(

So, according to your technical notes, is it possiable to readout the *.aria2 by snippet of codes, say, by using fortran?

[2] From the following command,
 
$ ./configure --help

I can find the following things:

   --enable-libaria2       Enable libaria2 support.

And, also, I've configured and compiled the aria2c with the libaria2 support.  But how to use it, I cann't find any minimal example in the manpage for this thing?  Especially for my issue posted in this thread: is it possiable for me to  use the libaria2 to readout the contents of *.aria2?

Regards

**Comment by tatsuhiro-t** [comment]
> [1]

Actually, the code to save/load .aria2 file is https://github.com/tatsuhiro-t/aria2/blob/master/src/DefaultBtProgressInfoFile.cc

You can read .aria2 file by mostly any modern programming language.  I don't know fortran.

> [2]

libaria2 API is described in http://aria2.sourceforge.net/manual/en/html/libaria2.html
As far as I know, there is no dedicated API function to read/write *.aria2 file.
