### ISSUE TITLE
Which completedLength will be used by the resume?

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#414]
Hi Tatsuhiro,

In the manual, I can read the following descriptions:

    aria2.getFiles([secret], gid)
     [snip]
                  completedLength
                     Completed length of this file in bytes.  Please note that
                     it  is  possible that sum of completedLength is less than
                     the completedLength returned  by  the  aria2.tellStatus()
                     method.     This    is    because    completedLength   in
                     aria2.getFiles() only includes completed pieces.  On  the
                     other  hand,  completedLength  in aria2.tellStatus() also
                     includes partially completed pieces.

So, which completedLength will be used by the resume method based *.aria2?  From the log file, it seems that, somtimes, some partially completed pieces are discarded, sometimes are used for resuming the downloading.

Regards

**Comment by tatsuhiro-t** [comment]
For resume, the completedLength reported by aria2.tellStatus() is used.  We use 16 KiB block as  the smallest unit to keep track of downloaded data, so that is used for resuming.  Normally, you don't need to care about this.

**Comment by hongyi-zhao** [comment]
Thanks a lot, do you mean, for a specific partially completed piece, its size must be interger times of  16 KiB?  Otherwise, the block which has size little than 16 KiB in a partially completed piece must be treated as garbage and thus be discarded away from that piece?

Regards

**Comment by tatsuhiro-t** [comment]
Yes, if I understand correctly.  But don't rely on this, because this is aria2 internal mechanism, and subject to change without notice.  Again, you don't need to care about this.

**Comment by hongyi-zhao** [comment]
Got it, thanks a lot.

Regards
