### ISSUE TITLE
Obtain notifications of the the RPC server by aria2.onDownloadComplete(event) method.

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#415]
Hi Tatsuhiro,

I've figured out most of the examples in the manpage for the rpc-interface part.  But the for the Notifications part, I still not so clear how to use it. 

Say, for the following commands issued by me:

    $ python
    Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
    [GCC 4.7.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import xmlrpclib
    >>> s = xmlrpclib.ServerProxy('http://localhost:6800/rpc')    
    >>> s.aria2.onDownloadComplete('f368b876a2e8f74c')
   Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
    File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
     File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
     return self.single_request(host, handler, request_body, verbose)
     File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
      return self.parse_response(response)
      File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
     File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
    xmlrpclib.Fault: <Fault 1: 'No such method: aria2.onDownloadComplete'>
    >>> 

Any hints?

Regards

**Comment by tatsuhiro-t** [comment]
As clearly described in manual http://aria2.sourceforge.net/manual/en/html/aria2c.html#json-rpc-over-websocket, aria2.onDownloadComplete is notification, only available in JSON-RPC over WebSocket.

**Comment by hongyi-zhao** [comment]
Then, based on the example given in the manual, I tried like the following but still failed:

	$ python
	Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
	[GCC 4.7.2] on linux2
	Type "help", "copyright", "credits" or "license" for more information.
	>>> import urllib2, json
	>>> from pprint import pprint
	>>> jsonreq = json.dumps({'jsonrpc':'2.0', 'id':'', 'method':'aria2.onDownloadComplete("a1083f56cd243af5")'})
	>>> c = urllib2.urlopen('http://localhost:6800/jsonrpc', jsonreq)
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
	    return _opener.open(url, data, timeout)
	  File "/usr/lib/python2.7/urllib2.py", line 407, in open
	    response = meth(req, response)
	  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
	    'http', request, response, code, msg, hdrs)
	  File "/usr/lib/python2.7/urllib2.py", line 445, in error
	    return self._call_chain(*args)
	  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
	    result = func(*args)
	  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
	    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
	urllib2.HTTPError: HTTP Error 500: Internal Server Error
	>>> pprint(json.loads(c.read()))
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	NameError: name 'c' is not defined
	>>> 

I'm newbie on phthon/json/rpc, so sorry for bothering.

Regards

**Comment by tatsuhiro-t** [comment]
Your example is JSON-RPC over HTTP, not WebSocket.
And notification is just pushed from aria2 server, and you cannot request it like that.

To see how WebSocket RPC work, run aria2c with --enable-rpc, and open browser (e.g., chrome).
Then open page http://localhost:6800/, which only shows blank page, which is fine.
Then open developer console, and type the following to create WebSocket object:
```js
ws = new WebSocket('ws://localhost:6800/jsonrpc')
ws.onmessage = function(msg) { console.log(msg); }
```

Then from terminal, add some downloads, say, using aria2rpc under doc/xmlrpc.
Then you will see the incoming message in developer console like this:
```
MessageEvent {data: "{"jsonrpc":"2.0","method":"aria2.onDownloadStart","params":[{"gid":"1788293a61b65168"}]}"}
MessageEvent {data: "{"jsonrpc":"2.0","method":"aria2.onDownloadComplete","params":[{"gid":"1788293a61b65168"}]}"}
```

**Comment by hongyi-zhao** [comment]
Thanks a lot.
