### ISSUE TITLE
.aria2 file not deleted after downloading complete (v1.19 on raspberry pi)

### ISSUE THREAD

**Issue by rocdeng** [tatsuhiro-t/aria2#416]
I build aria2 v1.19 from source on raspberry pi by my self. The original version on pi is 1.15, after downloading complete, the control file .aria2 will be deleted automaticly, but in v1.19 doesn't. Is there any configure control this feature?

**Comment by tatsuhiro-t** [comment]
I could not reproduce it.  Did you use --force-save option?

**Comment by rocdeng** [comment]
Yes, I used the --force-save option, after disable it, control file could be deleted! Thanks a lot!
