### ISSUE TITLE
About the speed used in the aria2c: is the limit/result  based on per connection or per server?

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#417]
Hi Tatsuhiro,

I've the following issue:

In aria2c, there are server points where I can use/obtain the speed, say, the following places:

dl_speed, sc_avg_speed, mc_avg_speed 

and

--lowest-speed-limit

But, I want to know the following things about the speed evaluation standand, I mean,  are these speed limits/results  based on per connection of specific server or the total speed of per server which taken all the connections to the server into accounted?

Regards

**Comment by tatsuhiro-t** [comment]
It is per connection, so we could have several statistics for the same hosts.  In that case, we use fastest one.

**Comment by hongyi-zhao** [comment]
Thanks a lot.
