### ISSUE TITLE
Limit number of simultaneously used uris per one connection

### ISSUE THREAD

**Issue by hagrid-the-developer** [tatsuhiro-t/aria2#418]
Hello.
It seems that now aria2 can open N http/ftp connections for every download. If it has >N uris for the download, it will choose N uris, if it has less, it can open more than one connection to one uri. I would need aria2 to behave this way: Choose one uri from the list and open N connection to it. If download fails, then open N connections to another uri from the list. Is it possible to force aria2 to act this way now or would it give sense to add such functionality to aria2?

**Comment by hongyi-zhao** [comment]
The maximum concurrent download for different items/entries are controlled by -j ( --max-concurrent-downloads=<N> ); the  maximum concurrent download for each  item/entry are controlled by -s, -k, and -x.

It seems that you are want to obtian the following thing:

aria2c -jN -x1 uris

But, the -x has the default value of 1, in addition, the -s, -k, and -x are interactive aruments.  And the manual has said a lot of thing on the relationship on them.

Regards

**Comment by hongyi-zhao** [comment]
Oops, I misunderstand you, the thing you want is as follows:

aria2c -j1 -xN -sN  uris.

Of course, you also should set approriate -k value to let the N possible for that file.

But, I think this scheme using the uris is ineffecitve.  Aria2c's power is lies in the multiple uris/soureces with the most supplementary of performances / fault-tolerance among these uris. The uri-selector algorithm + speedlimit + timeout + other relative arguments can be used for selecting the uris for your case.  If you don't force the uris used that way.   

Regards

**Comment by tatsuhiro-t** [comment]
You can create download with 1 URI, and then it failed, issue new download item with another URI, and so on.  We don't have no facility to automate this.  Probably, you can hack around URISelector, but you have to track which URI is failed or not, so it could be complex.

**Comment by hongyi-zhao** [comment]
Even so, IMO, the effectiveness won't be high.

**Comment by hagrid-the-developer** [comment]
Thanks, so far I have been able to live with 1 URI solution. In the future I would like to try to hack URISelector, but it is not necessary now.
