### ISSUE TITLE
.

### ISSUE THREAD

**Issue by leandroong** [tatsuhiro-t/aria2#419]

**Comment by leandroong** [comment]
Using different folder, not assigned download directory, I was able to get file downloaded. Ff sample fails:
http://gateway.play44.net/videos/vids4/from_vegas_to_macau_ii_2015_-_part2.mp4?st=qjTyWoW3Thpp-BmCYmkFZQ&e=1433833451&server=videobug

http://gateway.play44.net/videos/vids4/from_vegas_to_macau_ii_2015_-_part3.mp4?st=6JWkcdDanBZXwWLpUSToBQ&e=1433833507&server=videobug

http://gateway.play44.net/videos/vids4/from_vegas_to_macau_ii_2015_-_part4.mp4?st=rt6kd81_HdsXo6t9Tjf-nw&e=1433833539&server=videobug

http://gateway.play44.net/videos/vids4/from_vegas_to_macau_ii_2015_-_part5.mp4?st=JCg226Soun2BLL6YDDRypw&e=1433833581&server=videobug

http://gateway.play44.net/videos/vids4/from_vegas_to_macau_ii_2015_-_part6.mp4?st=nVfSh-xnjulE21W-1cgc8A&e=1433833618&server=videobug

http://gateway.play44.net/videos/vids4/from_vegas_to_macau_ii_2015_-_part7.mp4?st=nmjJ-eaFoKaEocOlA3LkLw&e=1433833658&server=videobug

**Comment by tatsuhiro-t** [comment]
Why did you change title to just "." ?  That is unclear and not readable.  Can we close this issue?

**Comment by leandroong** [comment]
It turned out the problem is due to usb flash drive format (fat32) is the issue from my router FW. After changing it to ext4, issue writing is solved. 
I deleted the title, since it is not aria2 issue
