### ISSUE TITLE
Aria2 keeps freezing download

### ISSUE THREAD

**Issue by teknogeek** [tatsuhiro-t/aria2#420]
For some reason, whenever I have aria2 going and it's downloading a large torrent, it gets stuck periodically with a message like this:
```
2015-06-09 12:15:57.829863 [DEBUG] [DefaultBtMessageDispatcher.cc:154] CUID#1147 - Deleting request slot index=3068, begin=8372224, blockIndex=511
2015-06-09 12:15:57.829901 [DEBUG] [BtPieceMessage.cc:251] Calculating hash index=3068
```

I tried setting `check-integrity` and `realtime-chunk-checksum` to `false` but it still happened. Then I also tried setting `bt-seed-unverified` to `true` and it is still happening. Any help??

**Comment by tatsuhiro-t** [comment]
Platform?  Linux, Windows, or something else?
If you are using Windows version and your file system is legacy VFAT, and you don't use --file-allocation=prealloc, then aria2 may pause because it will write at the random location of file, and VFAT requires all bytes from beginning of the file to the writing position is zero filled, which could take a time.

**Comment by teknogeek** [comment]
I'm on Linux, Debian 7. As for the filesystem, it's actually writing to an
sshfs mounted folder from a different server with more space.

**Comment by teknogeek** [comment]
btw that file system is defined as `fuse.sshfs` in `mount` and `df -Th`

**Comment by tatsuhiro-t** [comment]
Thanks.  Are you using --file-allocation=prealloc?
Reading file from remote file system could be slow, due to network delay or overhead etc.
aria2 always performs disk I/O in synchronous manner, and it may not work well with slow disk drive.

**Comment by teknogeek** [comment]
now that I am using prealloc, it no longer seems to be freezing however it is not showing anything in the web-ui. blank speeds and downloaded amounts

**Comment by teknogeek** [comment]
just directly going to the remote server

**Comment by boywanders** [comment]
Remote server owner here:
In the current state, the remote server (boywanders) is receiving data from the server that is running aria2. However, as shown by the graph, the machine running aria2 (t3kn0), is not recieving the same volume of data it is apparently sending. Also, the web UI for aria2 displays that the current active torrent is not  downloading at all but is active.
![ss 2015-06-09 at 06 27 50](https://cloud.githubusercontent.com/assets/2262960/8064981/4f4cb542-0ed6-11e5-9032-5c1eeefd3040.png)

**Comment by boywanders** [comment]
Using prealloc caused the server to send data to the remote server and allocate disk space for it, after this, the torrent started to download and displayed the same error as mentioned in the original comment. ~Owner of the remote server

**Comment by tatsuhiro-t** [comment]
Thanks for detailed information.  We have never had an issue in checking piece hash, so probably it is because of the interaction between aria2 and remote file system.  Currently, I have no idea about this.  But I'm curious what's happening while aria2 is freezing.  Did it consuming lots of CPU?  Or just waiting for something, say, network I/O?

**Comment by teknogeek** [comment]
The CPU and memory usage did not get high. I will look to see whether it is
sending network data at that point in a bit.

**Comment by boywanders** [comment]
While aria2 is freezing, there is no network data being transferred to or from the download server. What we observe is the web panel graph running horizontally for the freeze period followed by a substantial dip. It is important to note that while the graph freezes at a particular speed, this speed is not accurate and not representative of any transfer speed (As previously mentioned, the actual interface on the download server and the remote filesystem server show no transfer of data). When frozen, the process appears to consume no more CPU resources or memory.

**Comment by tatsuhiro-t** [comment]
web-ui periodically queries aria2 to get statistics including download speed.  If aria2 was completely frozen, web-ui could not access to aria2.  I'm not sure how web-ui behaves in that case, possibly it could show the old data.  That explains the flat graph.  All aria2 does when calculating hash is reading data from file in random access mode.  If aria2 program execution really stopped, I think it may be beyond the problem of aria2 itself, but I'm not sure at this moment.

**Comment by teknogeek** [comment]
After some thought, I have fixed the issue! `disk-cache` was set to `0` therefore disabling it. This meant that aria2 was having to do a lot of I/O during hash calculation etc causing it to hang. By setting `disk-cache` to `16M` it fixed it immediately. I did not experiment with lower amounts but if anyone else experiences this problem, feel free to.

Cheers!
