### ISSUE TITLE
Can I use aria2c to do the things done by wget's recursively whole site downloading, i.e.,  ``wget -r -p -np -k http://xxx.com/abc/''?

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#421]
Hi Tatsuhiro, 

It's well known that wget can do the recursively whole site downloading as follows:

wget -r -p -np -k http://xxx.com/abc/

Can I use aria2c to do the similar things done by wget? 

Regards

**Comment by tatsuhiro-t** [comment]
No.
