### ISSUE TITLE
--max-download-limit=<SPEED> and --max-overall-download-limit=<SPEED>

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#422]
Hi Tatsuhiro,

For HTTP/FTP/SFTP Options, the speed control options are less than those for BitTorrent Specific Options.  Say, I can find the following things for comparison:

   HTTP/FTP/SFTP Options
   --lowest-speed-limit=<SPEED>
  
  BitTorrent Specific Options
  --bt-request-peer-speed-limit=<SPEED>
  --max-overall-upload-limit=<SPEED>
  -u, --max-upload-limit=<SPEED>

But, I also find the following options in the `advanced Options' section form the manual:
  
    --max-overall-download-limit=<SPEED>
    --max-download-limit=<SPEED>

About these two `advanced Options', I've the following questions want to be cleared out:

[1]  Are these two options effective all of the  HTTP(S)/FTP  /SFTP  and  BitTorrent downloadings?

[2]  Are these two options based on the per each download and all of the downloading items instead of per each connction to do the speed conrolling?

[3] Why not also give the following two options:

     --min-overall-download-limit=<SPEED>
     --min-download-limit=<SPEED>

If so, the speed control can be done in more aspects.

Regards

**Comment by tatsuhiro-t** [comment]
> [1] Are these two options effective all of the HTTP(S)/FTP /SFTP and BitTorrent downloadings?

Yes

> [2] Are these two options based on the per each download and all of the downloading items instead of per each connction to do the speed conrolling?

--max-overall-download-limit is per aria2 instance.
--max-download-limit is per download item.

> [3] Why not also give the following two options:

--min-overall-download-limit does not make sense, since each download is separate entity.
--lowest-speed-limit may be the alternative for --min-download-limit.

**Comment by hongyi-zhao** [comment]
The issue is: --lowest-speed-limit evaluate the speed based on per each connection.  When I download a file with several connections, it will drop these connections when they are observed with low speed than the limit. But still I maybe  wait the download with the total low speed with the last one connection which just has the speed higher than the speed limit.  This is what I want to obtain.  I want to abort the downloading when the total speed is lower that some limit, so that I can restart the downloading with more good connections instead of waiting for the downloading using the few connections which have the speed higher then speed limit.

Regards

**Comment by tatsuhiro-t** [comment]
Thanks. I understood your issue, and it is a feature request.
I cannot promise this feature will be implemented, but it is better to open new issue for this specific feature request, and close this thread.
