### ISSUE TITLE
Using --save-session, --server-stat-of, and --server-stat-if in the daemon mode.

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#423]
Hi Tatsuhiro,

When I starting the aria2c in the daemon mode with `-D' option, I cann't find the generated files for server-stat and save-session.

Then I try to use the rpc method to generate the save-session file, and it give me the following errors:

$ ./aria2rpc saveSession --secret '$$secret$$'
/usr/lib/ruby/1.9.1/xmlrpc/client.rb:414:in `call': Failed to serialize session to 'save-session.log'. (XMLRPC::FaultException)
	from ./aria2rpc:340:in `client_call'
	from ./aria2rpc:415:in `<main>'

Another issue: why not also give the saveServerStat mthod via the rpc method, as you have give the saveSession method for the rpc mode.

Any hints?

Regards

**Comment by hongyi-zhao** [comment]
I've tried some more, it seems that in the daemon mode, all of the files must be use the absolute path, otherwise they may not be gererated.

Regards

**Comment by tatsuhiro-t** [comment]
> Another issue: why not also give the saveServerStat mthod via the rpc method, as you have give the saveSession method for the rpc mode.

Probably, because no one cared it.

> I've tried some more, it seems that in the daemon mode, all of the files must be use the absolute path, otherwise they may not be gererated.

Generally, yes.  When aria2 entered daemon mode, pwd is set to /, in order to not hold current directly.
You have to use absolute path for everything in daemon mode.
