### ISSUE TITLE
 When downloading to an external storage

### ISSUE THREAD

**Issue by dark1256** [tatsuhiro-t/aria2#428]
2015-06-22 20:08:47.466089 [ERROR] [FileAllocationCommand.cc:93] CUID#71 - Exception caught while allocating file space.
Exception: [AbstractDiskWriter.cc:515] errNum=95 errorCode=17 fallocate failed. cause: Operation not supported

When downloading to an external storage

**Comment by hongyi-zhao** [comment]
From the manpage:
  
falloc may not be available if your system doesn't have  posix_fallocate(3)  function.

Regards

**Comment by tatsuhiro-t** [comment]
If falloc is used with --file-allocation, and got this error,then file system does not support fallocate.
In Linux, --file-allocation=prealloc is recommended, since it automatically detects that fallocate can be used for the target file system, and if not, fallback to zero fill method.

**Comment by dark1256** [comment]
Found another way "trunc" works
