### ISSUE TITLE
Metalink download with --dry-run and response 403 make aria2 hang

### ISSUE THREAD

**Issue by Mjar13** [tatsuhiro-t/aria2#430]
I'm trying to verify if metalink content is downloadable using aria2c.

If server responds with HTTP 403 then aria2c hangs forever. But only when using the --dry-run switch, with normal download aria2c goes properly over the links responding with 403 and downloads rest of the files.

aria2c.exe --dry-run --max-file-not-found=1 --max-tries=1 --summary-interval=0 --show-console-readout=false -M _20150626_094000_GMT.metalink

The files are located on Amazon S3 cloud.
Test made on:
- Windows - aria2 version 1.16.4
- Windows - aria2 version 1.18.9
- Linux - aria2 version 1.16.4

Part of logs
06/26 13:46:55 [ERROR] CUID#10 - Download aborted. URI=http://url.cloudfront.net/file?Policy=ENCODEDPOLICY&Signature=YRt3S-W2QZSbv5DJxKX225M3XoEwwb4xeJfRWw9FdEtzDZrrqALQR~hwNlGJllLcLAeubUzAWJStbzrz
-u2UHUZLOj1D6tdrGQuaaQRrHfLN1aUe3yhi2d5iuWbRFACbxpeUTnjt4eR1rUt9w70X50PQrvrJBtY3aUjutYpHJl4_&Key-Pair-Id=APKAIX4EFWBC3T4PUOOA
Exception: [AbstractCommand.cc:350] errorCode=22 URI=http://url.cloudfront.net/file?Policy=ENCODEDPOLICY&Signature=YRt3S-W2QZSbv5DJxKX225M3XoEwwb4xeJfRWw9FdEtzDZrrqALQR~hwNlGJllLcLAeubUzAWJStbzrz
-u2UHUZLOj1D6tdrGQuaaQRrHfLN1aUe3yhi2d5iuWbRFACbxpeUTnjt4eR1rUt9w70X50PQrvrJBtY3aUjutYpHJl4_&Key-Pair-Id=APKAIX4EFWBC3T4PUOOA
  -> [HttpSkipResponseCommand.cc:228] errorCode=22 The response status is not successful. status=403

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  Fix committed via 7e3d82c
