### ISSUE TITLE
resume download / using --input-file

### ISSUE THREAD

**Issue by AnselmD** [tatsuhiro-t/aria2#431]
I have an input-file with a list of files to download with http.

If one of them finished, the .aria2 file is removed. If the download is cancelled and started again, the finished files are renamed and starts again.

Isn't it useful not to remove the .aria2 files until all files are finished?

**Comment by tatsuhiro-t** [comment]
Have you tried --save-session option?  aria2 saves unfinished download items in the file specified with --save-session in the format --input-file option can accept.  So next time, you can supply the new file to aria2 with --input-file option to resume unfinished ones.

**Comment by AnselmD** [comment]
Thank you very much, this helps. Is it allowed to take the same name for the --save-session and the  --input-file?
I think yes, because the serialized session is stored  as a last action.

**Comment by tatsuhiro-t** [comment]
Yes
