### ISSUE TITLE
option --select-file max is 65535

### ISSUE THREAD

**Issue by etmatrix** [tatsuhiro-t/aria2#432]
I have a torrent with more of 65535 files, I can't select file over 65535, I think max value should be the max return by --show-files

Thank you

**Comment by tatsuhiro-t** [comment]
c3b89d37e12ee69cd7968c048ffc30fafbf46049 increased the upper limit to ~1,000,000

**Comment by etmatrix** [comment]
Well with this patch now I can select without problems.

Thank you
