### ISSUE TITLE
Registering port forwards

### ISSUE THREAD

**Issue by farnoy** [tatsuhiro-t/aria2#433]
Hi,

Does aria2 register any port mappings with the local router to forward the listen ports if it's not accessible for the tracker?

**Comment by tatsuhiro-t** [comment]
I'm not sure I understand the issue correctly, probably, --bt-external-ip is what you are looking for.
http://aria2.sourceforge.net/manual/en/html/aria2c.html#cmdoption--bt-external-ip

**Comment by farnoy** [comment]
I've seen libtorrent do it (<https://github.com/libtorrent/libtorrent/blob/master/src/upnp.cpp>) and was wondering if aria does it too.

I haven't forwarded ports for aria and it doesn't seem to have any problems seeding. How is that possible though, if peers can't initiate a connection to me?

**Comment by tatsuhiro-t** [comment]
aria2 does not support upnp.  I'm not sure specific router settings, but in seeding, aria2 can actively connect to the peer, so it can work.

**Comment by farnoy** [comment]
I read up on the protocol, thanks for the information. If I understand correctly, the situation is: I'm unreachable on my listen ports from the outside, so the tracker does not give out my IP+port to other peers. Every `interval` seconds aria queries the tracker and initiates the connection to them (and serves them data if they still need it). The only true solution would be to obtain a public IP so people can reach me.
