### ISSUE TITLE
RPC method to get list of methods/notifications

### ISSUE THREAD

**Issue by sonnyp** [tatsuhiro-t/aria2#437]
Would be awesome to have a new RPC method to get list of RPC methods/notifications.

This would help RPC clients who do not have the possibility to catch functions call and have to manually declare a function for each aria2 method/notification for example: https://github.com/sonnyp/aria2.js/blob/master/src/index.js#L243

```rpc.``` namespace could be use for this http://www.jsonrpc.org/specification#extensions

**Comment by sonnyp** [comment]
additionally it would be very helpful to return a description of the method and its signature (accepted arguments and types)

**Comment by tatsuhiro-t** [comment]
d0ccb39 adds `system.listMethods` which just returns the available RPC method names.
This is an existing extension for XML-RPC which is supported by many RPC server implementations.

**Comment by sonnyp** [comment]
@tatsuhiro-t thanks, that's useful

**Comment by sonnyp** [comment]
aria2 rpc cli https://github.com/sonnyp/aria2.js/blob/master/bin/README.md if it's of any help to you / the project

**Comment by sonnyp** [comment]
the methods description/signature is an other story, will open a new issue if needs be.

**Comment by sonnyp** [comment]
@tatsuhiro-t could you make a new release including the listMethods method?

**Comment by tatsuhiro-t** [comment]
We'll do the next release in the next month.

**Comment by sonnyp** [comment]
:+1:
