### ISSUE TITLE
Please suggest me how to use SimpleDLNA

### ISSUE THREAD

**Issue by luvrajind** [tatsuhiro-t/aria2#442]
I have installed the SimpleDLNA and able to run it.
I created new server and added directory to it as well.
When i am starting it, Its launching a ssdp server and hosting description.xml

its also saying in logs that thumbnails are failed to load.

Main thing is i am not able to see the server in my android phone allShare app.
How to use it?

**Comment by nmaier** [comment]
Two things, you're in the wrong bug tracker mate, and SimpleDLNA is no-support ware, and since I do not know the answer to your problem, I cannot commit time finding out what is going on.
