### ISSUE TITLE
Can't build dll by using Dockerfile.mingw

### ISSUE THREAD

**Issue by hackwaly** [tatsuhiro-t/aria2#443]
I toggle the options --enable-libaria2 and AIRA2_STATIC=no in mingw-config file according the document. But it only produce an aria2c.exe (20kb, not working) after make/make install.

**Comment by eyalfishler** [comment]
same problem here. 
mingw-config:

test -z "$HOST" && HOST=i686-w64-mingw32
test -z "$PREFIX" && PREFIX=/usr/local/$HOST

./configure \
    --host=$HOST \
    --prefix=$PREFIX \
    --without-included-gettext \
    --disable-nls \
    --with-libcares \
    --without-gnutls \
    --without-openssl \
    --with-sqlite3 \
    --without-libxml2 \
    --with-libexpat \
    --with-libz \
    --with-libgmp \
    --with-libssh2 \
    --without-libgcrypt \
    --without-libnettle \
    --with-cppunit-prefix=$PREFIX \
    --enable-libaria2 \
    --enable-static \
    ARIA2_STATIC=no \
    ENABLE_LIBARIA2=yes \
    CPPFLAGS="-I$PREFIX/include" \
    LDFLAGS="-L$PREFIX/lib" \
    PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"
root@25420fd9dc48:/aria2#

**Comment by tatsuhiro-t** [comment]
We have the following text in README:

>If you want libaria2 dll with `--enable-libaria2`, then don't use
> `ARIA2_STATIC=yes` and prepare the DLL version of external
> libraries.

This means that you need all .dll for third party libraries, and effectively you cannot create static binary.

**Comment by eyalfishler** [comment]
as u can see from the mingw-config file 
--enable-libaria2 
ARIA2_STATIC=no 
ENABLE_LIBARIA2=yes 
i tried also removing 
--enable-static 

also tried in the Dockerfile.mingw to remove the disable-shared (for all the projects of course) as by default it builds both static and shared files
- Didn't help. 
RUN cd gmp-6.0.0 && \
    ./configure \
    --prefix=/usr/local/$HOST \
    --host=$HOST \
    --disable-cxx \
    --enable-fat \
    CFLAGS="-mtune=generic -O2 -g0" && \
    make install

**Comment by tatsuhiro-t** [comment]
I managed to build libaria2-0.dll with docker.
Here is the part of modified Docker script:
```
RUN tar xf gmp-6.0.0a.tar.lz
RUN cd gmp-6.0.0 && \
    ./configure \
    --enable-shared \
    --disable-static \
    --prefix=/usr/local/$HOST \
    --host=$HOST \
    --disable-cxx \
    --enable-fat \
    CFLAGS="-mtune=generic -O2 -g0" && \
    make install

RUN tar xf expat-2.1.0.tar.gz
RUN cd expat-2.1.0 && \
    ./configure \
    --enable-shared \
    --disable-static \
    --prefix=/usr/local/$HOST \
    --host=$HOST \
    --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` && \
    make install

RUN tar xf sqlite-autoconf-3080803.tar.gz
RUN cd sqlite-autoconf-3080803 && \
    ./configure \
    --enable-shared \
    --disable-static \
    --prefix=/usr/local/$HOST \
    --host=$HOST \
    --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` && \
    make install

# RUN tar xf zlib-1.2.8.tar.xz
# RUN cd zlib-1.2.8 && \
#     CC=$HOST-gcc \
#     AR=$HOST-ar \
#     LD=$HOST-ld \
#     RANLIB=$HOST-ranlib \
#     STRIP=$HOST-strip \
#     ./configure \
#     --prefix=/usr/local/$HOST \
#     --libdir=/usr/local/$HOST/lib \
#     --includedir=/usr/local/$HOST/include && \
#     make install

RUN tar xf c-ares-1.10.0.tar.gz
RUN cd c-ares-1.10.0 && \
    ./configure \
    --enable-shared \
    --disable-static \
    --without-random \
    --prefix=/usr/local/$HOST \
    --host=$HOST \
    --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
    LIBS="-lws2_32" && \
    make install

RUN tar xf libssh2-1.5.0.tar.gz
RUN cd libssh2-1.5.0 && \
    ./configure \
    --enable-shared \
    --disable-static \
    --prefix=/usr/local/$HOST \
    --host=$HOST \
    --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
    --without-openssl \
    --with-wincng \
    LIBS="-lws2_32" && \
    make install
```

I commented zlib build because it seems we need to use win32/Makefile.gcc to build zlib dll.
```
$ export BINARY_PATH/$HOST/bin
$ export INCLUDE_PATH/$HOST/include
$ export LIBRARY_PATH/$HOST/lib
$ make install -f win32/Makefile.gcc PREFIX=$HOST- SHARED_MODE=1
```
$HOST should be the same value we use in Dockerfile.

Now I use the following mingw configuration to configure aria2 build script:
```
test -z "$HOST" && HOST=i686-w64-mingw32
test -z "$PREFIX" && PREFIX=/usr/local/$HOST

./configure \
    --host=$HOST \
    --prefix=$PREFIX \
    --without-included-gettext \
    --disable-nls \
    --with-libcares \
    --without-gnutls \
    --without-openssl \
    --with-sqlite3 \
    --without-libxml2 \
    --with-libexpat \
    --with-libz \
    --with-libgmp \
    --with-libssh2 \
    --without-libgcrypt \
    --without-libnettle \
    --with-cppunit-prefix=$PREFIX \
    --enable-libaria2 \
    CPPFLAGS="-I$PREFIX/include" \
    LDFLAGS="-L$PREFIX/lib" \
    PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"
```

**Comment by eyalfishler** [comment]
@tatsuhiro-t thanks for the elaborate response,

i was able to build the DLL, the output dll file is 120MB
is that correct?
https://dl.dropboxusercontent.com/u/36645939/libaria2-0.dll.gz

tried also running it with the flag 
--without-bittorrent
and that deceased the size to 78MB

i must be doing something wrong here...
i'v followed your instructions 
(one change was 
export BINARY_PATH=$HOST/bin
export INCLUDE_PATH=$HOST/include
export LIBRARY_PATH=$HOST/lib 
just a typo)

**Comment by tatsuhiro-t** [comment]
Did you strip debug symbol?
i686-w64-mingw32-strip or x86_64-w64-mingw32-strip do this depending on OS.

**Comment by tatsuhiro-t** [comment]
I think stripping debug symbol fixes the issue.  Please reopen this if it is not a fix.

**Comment by Tu5039** [comment]
> I managed to build libaria2-0.dll with docker.
> Here is the part of modified Docker script:
> 
> ```
> RUN tar xf gmp-6.0.0a.tar.lz
> RUN cd gmp-6.0.0 && \
>     ./configure \
>     --enable-shared \
>     --disable-static \
>     --prefix=/usr/local/$HOST \
>     --host=$HOST \
>     --disable-cxx \
>     --enable-fat \
>     CFLAGS="-mtune=generic -O2 -g0" && \
>     make install
> 
> RUN tar xf expat-2.1.0.tar.gz
> RUN cd expat-2.1.0 && \
>     ./configure \
>     --enable-shared \
>     --disable-static \
>     --prefix=/usr/local/$HOST \
>     --host=$HOST \
>     --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` && \
>     make install
> 
> RUN tar xf sqlite-autoconf-3080803.tar.gz
> RUN cd sqlite-autoconf-3080803 && \
>     ./configure \
>     --enable-shared \
>     --disable-static \
>     --prefix=/usr/local/$HOST \
>     --host=$HOST \
>     --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` && \
>     make install
> 
> # RUN tar xf zlib-1.2.8.tar.xz
> # RUN cd zlib-1.2.8 && \
> #     CC=$HOST-gcc \
> #     AR=$HOST-ar \
> #     LD=$HOST-ld \
> #     RANLIB=$HOST-ranlib \
> #     STRIP=$HOST-strip \
> #     ./configure \
> #     --prefix=/usr/local/$HOST \
> #     --libdir=/usr/local/$HOST/lib \
> #     --includedir=/usr/local/$HOST/include && \
> #     make install
> 
> RUN tar xf c-ares-1.10.0.tar.gz
> RUN cd c-ares-1.10.0 && \
>     ./configure \
>     --enable-shared \
>     --disable-static \
>     --without-random \
>     --prefix=/usr/local/$HOST \
>     --host=$HOST \
>     --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
>     LIBS="-lws2_32" && \
>     make install
> 
> RUN tar xf libssh2-1.5.0.tar.gz
> RUN cd libssh2-1.5.0 && \
>     ./configure \
>     --enable-shared \
>     --disable-static \
>     --prefix=/usr/local/$HOST \
>     --host=$HOST \
>     --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
>     --without-openssl \
>     --with-wincng \
>     LIBS="-lws2_32" && \
>     make install
> ```
> 
> I commented zlib build because it seems we need to use win32/Makefile.gcc to build zlib dll.
> 
> ```
> $ export BINARY_PATH/$HOST/bin
> $ export INCLUDE_PATH/$HOST/include
> $ export LIBRARY_PATH/$HOST/lib
> $ make install -f win32/Makefile.gcc PREFIX=$HOST- SHARED_MODE=1
> ```
> 
> $HOST should be the same value we use in Dockerfile.
> 
> Now I use the following mingw configuration to configure aria2 build script:
> 
> ```
> test -z "$HOST" && HOST=i686-w64-mingw32
> test -z "$PREFIX" && PREFIX=/usr/local/$HOST
> 
> ./configure \
>     --host=$HOST \
>     --prefix=$PREFIX \
>     --without-included-gettext \
>     --disable-nls \
>     --with-libcares \
>     --without-gnutls \
>     --without-openssl \
>     --with-sqlite3 \
>     --without-libxml2 \
>     --with-libexpat \
>     --with-libz \
>     --with-libgmp \
>     --with-libssh2 \
>     --without-libgcrypt \
>     --without-libnettle \
>     --with-cppunit-prefix=$PREFIX \
>     --enable-libaria2 \
>     CPPFLAGS="-I$PREFIX/include" \
>     LDFLAGS="-L$PREFIX/lib" \
>     PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"
> ```

But what should I do to build zlib dll in my docker?
