### ISSUE TITLE
Failed to parse JSON-RPC request

### ISSUE THREAD

**Issue by bindiry** [tatsuhiro-t/aria2#444]
Raspberry pi 2 model B
system: RASPBIAN(2015-05-05)

```
2015-08-15 00:43:09.171187 INFO - [HttpServerBodyCommand.cc:206]CUID#7 - Failed to parse JSON-RPC request
Exception: [json.cc:450] errorCode=30 JSON decoding failed: Unexpected EOF in term context.
```

config file

```
dir=/mnt/sda1/downloads
disable-ipv6=true
enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-all=true
continue=true
input-file=/root/.aria2/aria2.session
save-session=/root/.aria2/aria2.session
max-concurrent-downloads=3
log=/var/log/aria2.log
log-level=info
```

http://raspberrypi_ip:6800/jsonrpc?jsoncallback=1

```
1({"error":{"code":-32700,"message":"Parse error."},"id":null,"jsonrpc":"2.0"})
```

**Comment by bindiry** [comment]
may be need to install `libxml2-dev` package

**Comment by bindiry** [comment]
source code compiling...

**Comment by bindiry** [comment]
find 2.17.0 from [here](https://launchpad.net/ubuntu/+source/aria2/1.17.0-1/+build/4553589)

**Comment by tatsuhiro-t** [comment]
What does the rpc request URI look like?
aria2 requires specific query parameters encoded, and they are described in http://aria2.sourceforge.net/manual/en/html/aria2c.html#json-rpc-using-http-get

**Comment by bindiry** [comment]
@tatsuhiro-t 
like `http://raspberrypi_ip:6800/jsonrpc?jsoncallback=1`
my aria2 version is : 1.15.1

**Comment by bindiry** [comment]
i installed it use `apt-get install aria2` command.

**Comment by tatsuhiro-t** [comment]
The request "http://raspberrypi_ip:6800/jsonrpc?jsoncallback=1" does not work.  Please read documentation.
http://aria2.sourceforge.net/manual/en/html/aria2c.html#json-rpc-using-http-get

**Comment by tatsuhiro-t** [comment]
I think this issue is fixed by following manual cited above.  If you still experience the issue even after following the manual, please reopen it.

**Comment by renweibo** [comment]
update with latest manual link
https://aria2.github.io/manual/en/html/aria2c.html
