### ISSUE TITLE
tls handshake failure

### ISSUE THREAD

**Issue by Yamakaky** [tatsuhiro-t/aria2#445]
[ERROR] CUID#8 - Download aborted. URI=http://edt.univ-nantes.fr/chantrerie-gavy/g1630.ics
Exception: [AbstractCommand.cc:350] errorCode=1 URI=https://edt.univ-nantes.fr/chantrerie-gavy/g1630.ics
-> [SocketCore.cc:975] errorCode=1 SSL/TLS handshake failure: L’algorithme de signature n’est pris en charge.

I tried running it with debug log level, but nothing conclusive. I have no problem with wget or firefox. Could [this](https://www.ssllabs.com/ssltest/analyze.html?d=edt.univ-nantes.fr&s=193.52.104.60) be the problem ?

**Comment by tatsuhiro-t** [comment]
If you are using GNUTLS, then v1.19.0 disables SHA1 signature, and handshake with some servers fail.
We relaxed the implementation to allow SHA1 signature in dd277b33af2a5a58c39142097c3ede5df7f5655d, which will be included in the next release.
If you are in a hurry, building aria2 with openssl does not have this problem.

**Comment by Yamakaky** [comment]
Ok, thanks. Do you know when it will be released ?

**Comment by tatsuhiro-t** [comment]
Next month.  I don't have much time in August.

**Comment by Yamakaky** [comment]
Ok, thanks
