### ISSUE TITLE
An extension of Firefox for aria2

### ISSUE THREAD

**Issue by zendalee** [tatsuhiro-t/aria2#448]
Nowadays, many download actions are web browsers driven. Therefore, an integration of aria2 in web browsers is very necessary. Up to now,  there does not exist a good one. Though [Flashgot](https://flashgot.net/) is that one, it only supports single task. For example, if I want to download seven files in a webpage with [Flashgot](https://flashgot.net/)+aria2, then seven aria2c processes will run. This is unacceptable in a desktop environment, [Flashgot](https://flashgot.net/) does not make use of the adding URIs feature of RPC. Another shortcoming of [Flashgot](https://flashgot.net/) is that it does not support downloading all files in a webpage with aria2, certainly, file type filter is more impossible. Thus, could somebody create an extension of Firefox for aria2 to overcome these shortcomings? It is better that if this extension can support the set of download path, because we always need to download files to different directories.

**Comment by tatsuhiro-t** [comment]
We have no plan to create Firefox extension in this project.

**Comment by matiffeder** [comment]
@zendalee I think maybe this [program](https://github.com/matiffeder/aria2m/releases/tag/1.0.0) include some feature you want.
