### ISSUE TITLE
HTTPS unavailable on Android 4.0+

### ISSUE THREAD

**Issue by amtlib-dot-dll** [tatsuhiro-t/aria2#450]
The CA certificates shipped with Android are stored in separated files in `/etc/security/cacerts/`, however aria2c supports only one CA certificate file. I'm not sure whether any single file of them is in PEM format and thus can be recognized by aria2.

Is it legal to bundle some CA certificates with aria2 distribution? Thence this problem would be certainly solved. Thank you very much!

**Comment by tatsuhiro-t** [comment]
I think this could be solved by building openssl with default ca location /etc/security/cacerts/.

**Comment by amtlib-dot-dll** [comment]
Thank you!

By the way, is there any temporary solution by adjusting the command-line parameters or environment variables?

**Comment by tatsuhiro-t** [comment]
I think the workaround is extract all contents between -----BEGIN CERTIFICATE----- and -----END CERTIFICATE-----, including these lines, from files under /etc/security/cacerts/ and concatenate all of them in one file, and give it to aria2 using --ca-certificate option.

**Comment by amtlib-dot-dll** [comment]
That's very nice of you.

The workaround looks like this `cat /etc/security/cacerts/* | aria2 --ca-certificate=/proc/self/fd/0 $@`

**Comment by tatsuhiro-t** [comment]
I compiled openssl with the parameter to load certificates under /etc/security/cacerts, but it did not work.  The debug was too much painful.
So I think your workaround is better than my idea.

**Comment by amtlib-dot-dll** [comment]
OwO

**Comment by amtlib-dot-dll** [comment]
There are [extra data][1] after the `-----END CERTIFICATE-----` statement, and thus although it doesn't matter when simply passing the concatenated files as a command-line argument, would it affect the OpenSSL source code or the complier or something else? Only a guess

[1]: https://android.googlesource.com/platform/libcore/+/master/luni/src/main/files/cacerts/00673b5b.0

**Comment by tatsuhiro-t** [comment]
Not sure about openssl's parser, but your workaround worked for me just fine.  So probably it does not matter.

**Comment by amtlib-dot-dll** [comment]
OwO
