### ISSUE TITLE
SFTP examples

### ISSUE THREAD

**Issue by pyed** [tatsuhiro-t/aria2#453]
I failed to use aria2 for `SFTP`.

It is not clear how one could download using `SFTP` should my URI starts with `FTP` ? is it possible to use my key in `~/.ssh` for authentication ? what's about `ports` ? should I include that in the URI ?

**Comment by tatsuhiro-t** [comment]
Use ftps://...

Currently, we have no functionality to use user's key.
The only option we have is validate server's public key: http://aria2.sourceforge.net/manual/en/html/aria2c.html#cmdoption--ssh-host-key-md

**Comment by pyed** [comment]
I tried `ftps` and `sftp` both are giving me the `is not supported yet` error.

here's what i am doing
```bash
~/Desktop $ aria2c --ftp-user=user --ftp-passwd=pass ftps://122.2.222.226:34432/home/user/files/hello

08/30 12:08:19 [ERROR] CUID#6 - Download aborted. URI=ftps://122.2.222.226:34432/home/user/files/hello
Exception: [AbstractCommand.cc:350] errorCode=1 URI=ftps://122.2.222.226:34432/home/user/files/hello
  -> [InitiateConnectionCommandFactory.cc:90] errorCode=1 ftps is not supported yet.

08/30 12:08:19 [NOTICE] Download GID#339b13b99182dd54 not complete:

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
339b13|ERR |        n/a | ftps://122.2.222.226:34432/home/user/files/hello

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
```

**Comment by tatsuhiro-t** [comment]
I was wrong, it should be "sftp" not "ftps".

**Comment by pyed** [comment]
Aha, I see now, I didn't compile it with `--with-libssh2`, I recompiled it and it is working now, and yes it is `sftp` of course.

Thanks

**Comment by hardhub** [comment]
@pyed I have compiled it as you said. And now it supports SFTP. It is sad that by default distros do not support it.

But I have another issue now. Is it possible to use private key when password authentication is disabled on server.
