### ISSUE TITLE
Add option to ignore output file name for metalink

### ISSUE THREAD

**Issue by yurikoles** [tatsuhiro-t/aria2#462]
It will be very useful for scripts. For example, I have string like this in my ```/etc/makepkg.conf``` on ArchLinux: ```'http::/usr/bin/aria2c %u -o %o -s16 -x16'```. And it's very problematic to download files from download.gnome.org since they are use metalinks. aria2c just saves metalink with name supplied by ```-o``` option. I'm willing to propose some kind of ```--ignore-explicit-name-if-metalink```. 

Or please advice me some option (e.g. modify UA) to force server to return file instead of metalink.

**Comment by tatsuhiro-t** [comment]
I think --follow-metalink=mem does the job in this case.
http://aria2.sourceforge.net/manual/en/html/aria2c.html?highlight=#cmdoption--follow-metalink
download.gnome.org returns `content-type: application/metalink4+xml`, then aria2c processes the response as metalink file in memory, and continues to download the content it describes.

**Comment by tatsuhiro-t** [comment]
Please reopen this if --follow-metalink=mem does not fix this issue.

**Comment by bartoszek** [comment]
test
