### ISSUE TITLE
aria2 1.19.1 doesn't show 'download progress summary'

### ISSUE THREAD

**Issue by clamsawd** [tatsuhiro-t/aria2#463]
I have compiled aria2 1.19.1 on Windows 10 and Debian. Now, the program never show the output of download progress summary. I set the interval with "--summary-interval=" but it doesn't work. That's normal in the current version or is a bug?

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this bug.  Yes, this is a bug.
The fix was committed via 85faafc

**Comment by clamsawd** [comment]
@tatsuhiro-t Thanks for fix the bug!
