### ISSUE TITLE
Version 1.19.1 still checking only $HOME/.aria2 for dht.dat

### ISSUE THREAD

**Issue by endormos** [tatsuhiro-t/aria2#464]
Hi, I just compiled aria2 v1.19.1 from source on Debian Wheezy and noticed some strange behavior.
According to the release notes, from now on aria2 should look for aria2.conf in $XDG_CONFIG_HOME/aria2/ and for dht.dat in $XDG_CACHE_HOME/aria2/, but that's still not quite the case. The program does indeed look for aria2.conf in the XDG directory, but dht.dat is still being searched for only in the old config dir, $HOME/.aria2, even though I moved it into $XDG_CACHE_HOME/aria2/, where it seems not to be able to find it.
Here's a snippet from strace output:
```
munmap(0x7f29e89d4000, 4096)            = 0
open("/usr/local/share/locale/en_US/LC_MESSAGES/aria2.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/local/share/locale/en/LC_MESSAGES/aria2.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/home/cleaver/.aria2/aria2.conf", 0x7ffc5ef19690) = -1 ENOENT (No such file or directory)
getcwd("/home/cleaver", 2048)           = 14
stat("/home/cleaver/.aria2/dht.dat", 0x7ffc5ef19680) = -1 ENOENT (No such file or directory)
stat("/home/cleaver/.aria2/dht6.dat", 0x7ffc5ef19680) = -1 ENOENT (No such file or directory)
stat("/home/cleaver/.config/aria2/aria2.conf", {st_mode=S_IFREG|0644, st_size=139, ...}) = 0
open("/home/cleaver/.config/aria2/aria2.conf", O_RDONLY) = 4
ioctl(4, SNDCTL_TMR_TIMEBASE or TCGETS, 0x7ffc5ef19f70) = -1 ENOTTY (Inappropriate ioctl for device)
fstat(4, {st_mode=S_IFREG|0644, st_size=139, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f29e89d4000
read(4, "listen-port=6890\nseed-ratio=0.0\n"..., 4096) = 139
read(4, "", 4096)                       = 0
close(4)                                = 0
```

**Comment by tatsuhiro-t** [comment]
$XDG_CACHE_HOME defaults to $HOME/.cache.  What happens if you place dht.dat file under $HOME/.cache/aria2/ ?

**Comment by tatsuhiro-t** [comment]
Looking up old directory is done for compatibility reason.  If we found files at old location, we use them.
If not, we check new locations.

**Comment by endormos** [comment]
Yes, I know that aria2 is looking in the old dir for compatibility reasons. The problem is that, when looking for dht.dat, it never checks $HOME/.cache/aria2/. It only checks the old dir.
When the strace output above was captured, I had already put my dht.dat in $HOME/.cache/aria2/ and it is there. But aria2 doesn't look for it there. Or at least strace doesn't show aria2 trying to stat the file in the new dir.
That's why I thought this behavior might be a bug. :)

**Comment by tatsuhiro-t** [comment]
OK, let me check more..

**Comment by tatsuhiro-t** [comment]
In my environment, dht.dat is correctly loaded:
```
2015-09-29 23:47:45.632894 [INFO] [DHTRoutingTableDeserializer.cc:79] Loading DHT routing table from /home/alpha/.cache/aria2/dht.dat.
```

**Comment by endormos** [comment]
OK, you're right, it works correctly. I just weren't looking for it the right way. I now realized that aria2 doesn't stat dht.dat until a torrent download is requested. My bad :)
