### ISSUE TITLE
max-connection not working

### ISSUE THREAD

**Issue by TonyStark** [tatsuhiro-t/aria2#465]
I installed aria2 (1.18.1) in my ubuntu. but the problem is it can not increase download connection.

```
aria2c -x 10 http://mirror.sg.leaseweb.net/speedtest/100mb.bin
[#fe34b4 2.1MiB/95MiB(2%) CN:4 DL:233KiB ETA:6m49s
```
by default it only download from 4 connection not 10 (as i given). i even try with another sites, but default 4 connection carried out while downloading

**Comment by nmaier** [comment]
There are multiple options that influence the behavior:
- `--split` `-s` Maximum number of concurrent splits (connections) per download. Defaults to 5, so unless you changed it, you will get max 5 connections for a single download no matter what `-x`.
- `--min-split-size` `-k` A split should only be initiated when the split would be bigger than this. Defaults to 20M, meaning that when you download a 100M file, the time the download is split some data is already retrieved which means less slightly less than 100MB is remaining, meaning 4 splits (5 splits would create splits slightly less than 20MB).

There you have it. Please check out the manual for more information on the various options.

```
$ aria2c -k 1M -s 10 -x 10 http://mirror.sg.leaseweb.net/speedtest/100mb.bin
[#1325f1 7.4MiB/95MiB(7%) CN:10 DL:1.2MiB ETA:1m8s]
```

**Comment by tatsuhiro-t** [comment]
Thank you @nmaier !

**Comment by TonyStark** [comment]
:+1:  @nmaier
