### ISSUE TITLE
Proxy for BitTorrent downloading

### ISSUE THREAD

**Issue by edtechd** [tatsuhiro-t/aria2#470]
Hello,

Is it possible to configure aria2 that it connects to trackers / dht via proxy? My server infrastructure blocks some udp / p2p packets so torrent client can't scrape peers directly. But peer-to-peer connections work well.

Thanks.

**Comment by tatsuhiro-t** [comment]
aria2 can connect to tcp tracker via HTTP proxy.  There is no proxy support for UDP traffic.

**Comment by jeisoncg** [comment]
https://www.npmjs.com/package/udp-proxy

**Comment by edtechd** [comment]
OK, thanks guys for your advice, I will try to implement a proxy-tracker and add it to each link, It seems to be the easiest way of organizing proxy for UDP trackers.
