### ISSUE TITLE
aria2c never retries 404 or other http errors

### ISSUE THREAD

**Issue by iongion** [tatsuhiro-t/aria2#471]
Using `aria2 version 1.19.2` on windows 64
I have a local server with which I test download behavior under errors:

I have a simple php script that simulates 4xx, 5xx and so on:
```
<?php
http_response_code(404);
exit;
?>
```

I call aria2c like bellow:
```
aria2c --async-dns=false \
  --auto-file-renaming=false \
  --check-certificate=false \
  --conditional-get=true \
  --allow-overwrite=true \
  --always-resume=true \
  --http-no-cache=true \
  --max-file-not-found=0 \
  --max-tries=20 \
  --retry-wait=5 \
  http://localhost/script.php -o stat.dwn
```

I expect aria2c to sleep 5 seconds and retry 20 times before quiting.
The behavior that I get is that aria2c *never retries downloading*, 404 or any other different error code.
Am I doing something wrong, is this the expected behavior ?

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this.
I committed 4bbc71c to fix this.  But you need to specify --max-file-not-found > 0 to retry on getting 404.
Note that --max-tries is generally for timeout.

**Comment by iongion** [comment]
This was awesome! Thank you!
I will build it asap, did not dedicate too much time, but on my old Ubuntu 12.04, the build complaints:
```
In file included from AbstractAuthResolver.cc:37:0:
a2functional.h:193:38: error: expected type-specifier before string constant
```

Don't worry, will try to fix it myself and come back with report.

**Comment by tatsuhiro-t** [comment]
Recent version of aria2 requires newer versions of gcc >= 4.8.3 or clang >= 3.4.
I'm afraid Ubuntu 12.04 is a bit too old.
Alternatively, you may patch the old version of aria2 with the diff.

**Comment by futuretechmag** [comment]
I don't mean to necro an old thread but:

aria2c --auto-file-renaming=false --max-file-not-found=1000 --http-no-cache=true --retry-wait=5 --max-connection-per-server=16 -s20 --allow-overwrite=true --always-resume=true http://file

Doesn't seem to retry the 404?

**Comment by tatsuhiro-t** [comment]
@futuretechmag Thank you for telling me that. 029d689 fixes it.

**Comment by futuretechmag** [comment]
@tatsuhiro-t  Just to make sure, 'aria2c  --max-file-not-found=100 --retry-wait=5 -Z URI1 UR2 UR3' would then try getting each of those 3 URI's 100 times, waiting 5 seconds between attempts?

**Comment by futuretechmag** [comment]
I "fixed" it by doing which I BELIEVE always retries 404 infinitely, waiting --retry-wait seconds between retries. At least from the looks of it that is exactly what happens anyway.

     } else if(statusCode == 404) {
       `if(getOption()->getAsInt(PREF_RETRY_WAIT) > 0) {
         throw DL_RETRY_EX2(fmt(EX_BAD_STATUS, statusCode),
                            error_code::HTTP_SERVICE_UNAVAILABLE);
     } else if(statusCode == 503) {`

**Comment by futuretechmag** [comment]
Just to make sure, 'aria2c --max-file-not-found=100 --retry-wait=5 -Z URI1
UR2 UR3' would then try getting each of those 3 URI's 100 times, waiting 5
seconds between attempts? I "fixed" it by doing which I BELIEVE always
retries 404 infinitely, waiting --retry-wait seconds between retries. At
least from the looks of it that is exactly what happens anyway.

 } else if(statusCode == 404) {
   `if(getOption()->getAsInt(PREF_RETRY_WAIT) > 0) {
     throw DL_RETRY_EX2(fmt(EX_BAD_STATUS, statusCode),
                        error_code::HTTP_SERVICE_UNAVAILABLE);
 } else if(statusCode == 503) {

On Fri, Dec 18, 2015 at 9:05 AM, Tatsuhiro Tsujikawa <
notifications@github.com> wrote:

> @futuretechmag <https://github.com/futuretechmag> Thank you for telling
> me that. 029d689
> <https://github.com/tatsuhiro-t/aria2/commit/029d6897f2b0d7d2f2bad904dd145cc33f6d35cf>
> fixes it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tatsuhiro-t/aria2/issues/471#issuecomment-165785277>.
>



-- 
-Chris A. Gilroy

**Comment by tatsuhiro-t** [comment]
Yes, mostly they are the same.  The difference is that error code value.

I think you also need to specify --max-tries=100 in this case.

**Comment by tatsuhiro-t** [comment]
Closing, since original issue was fixed.
