### ISSUE TITLE
Corrupted file download

### ISSUE THREAD

**Issue by tarioch** [tatsuhiro-t/aria2#473]
This was reported by a user and I'm able to reproduce the same behavior.:

aria2c http://files.easy2boot.com/200001415-a420da51ca/Easy2Boot_v1.73.7z

results in a different file on each download and is also different than

wget -c http://files.easy2boot.com/200001415-a420da51ca/Easy2Boot_v1.73.7z -O Easy2Boot_v1.73.7z_wget.7z

I also tried

aria2c --max-concurrent-downloads=1 --force-sequential=true http://files.easy2boot.com/200001415-a420da51ca/Easy2Boot_v1.73.7z

and it still had the same issue

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this.  It looks like the server sends both Content-Length and Transfer-Encoding: chunked, which is prohibited by RFC 7230.  In anyway, aria2 should ignore Content-Length in this case.  There could be a bug somewhere handling this situation.

**Comment by tatsuhiro-t** [comment]
Fix committed via 5ccd5b6
