### ISSUE TITLE
Compile git version under raspbian jessie

### ISSUE THREAD

**Issue by hungaborhorvath** [tatsuhiro-t/aria2#479]
Somehow I cannot compile the cloned git version under raspbian jessie. 

I have the following packages installed:

libgnutls28-dev 3.3.8-6+deb8u3
nettle-dev 2.7.1-5
libgmp-dev 2:6.0.0+dfsg-6+rpi1
libssh2-1-dev 1.4.3-4.1
libc-ares-dev 1.10.0-2
libxml2-dev 2.9.1+dfsg1-5
zlib1g-dev 1:1.2.8.dfsg-2
libsqlite3-dev 3.8.7.1-1+deb8u1
pkg-config 0.28-1
libcppunit-dev 1.13.2-2
autoconf 2.69-8
autopoint 0.19.3-2

1.19.2 compiles without any problems. I saw in the README that I need to type 

autoreconf -i 

before I will be able to compile the git source. However, I get the following error message: 

lib/Makefile.am:30: error: Libtool library used but 'LIBTOOL' is undefined
lib/Makefile.am:30:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
lib/Makefile.am:30:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
lib/Makefile.am:30:   If 'LT_INIT' is in 'configure.ac', make sure
lib/Makefile.am:30:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

If I now run ./configure, then I obtain the following error message: 

configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

I could not find in the manual what else I should do.

**Comment by hungaborhorvath** [comment]
Never mind, I figured it out. After I installed the

libtool

package, autoconf -i worked, and I could run ./configure. I am waiting for the end of the compilation. 

It might be worth to write about the libtool package into the README, though..... Then this issue can be closed.

**Comment by tatsuhiro-t** [comment]
OK, e934f177fff09dd74ae418b4fd623d82dada2f13 will add couple of packages required to build aria2 from git repository.
