### ISSUE TITLE
Aria2 on Gentoo is Masked

### ISSUE THREAD

**Issue by donly** [tatsuhiro-t/aria2#484]
and version is

> Latest version available: 1.19.0

**Comment by tatsuhiro-t** [comment]
What do you mean "Masked"?

**Comment by donly** [comment]
"Masked" from Gentoo emerge search shows

> net-misc/aria2 [ Masked ]

> Any attempt to install such a package results in the warning from Portage that additional changes are needed before it will proceed

https://wiki.gentoo.org/wiki/Knowledge_Base:Unmasking_a_package

**Comment by tatsuhiro-t** [comment]
Thank you.  I'm not sure why aria2 is masked and how to solve this.  You're better to ask gentoo developers.

**Comment by donly** [comment]
I'll do that, thanks!
