### ISSUE TITLE
on-bt-download-complete fired twice when pause/unpause torrent

### ISSUE THREAD

**Issue by amirotin** [tatsuhiro-t/aria2#485]
Hi. When bt-hash-check-seed=true and check-integrity=true command in on-bt-download-complete is called twice.

When torrent is downloaded on-bt-download-complete is called first time. In my command torrent is paused and unpaused. Then it is called second time. And so on until i stop aria2.

Is it bug or what?

**Comment by tatsuhiro-t** [comment]
check-integrity=true triggers on-bt-download-complete, and it is by design.

**Comment by amirotin** [comment]
Maybe it is possible to add some additional argument to on-bt-download-complete which will determine is it integrity check or realy download complete?
usually on complete event is used to do something with files (move, rename and etc). And if on each start/stop it will be fired - this can damage data.

**Comment by tatsuhiro-t** [comment]
I think it is possible to add additional parameter, but there may be some scripts or programs that strictly check the number of arguments.  If they do, we are breaking them.

BTW, this on-bt-download-complete invocation was added in #355

**Comment by tatsuhiro-t** [comment]
Another workaround is add option not to call on-bt-download-complete after verification success.

**Comment by amirotin** [comment]
Yeap, option will be better solution!

**Comment by tatsuhiro-t** [comment]
The option was added via commit 35f08f0
