### ISSUE TITLE
Feature request: make local file get the same timestamp from the remote timestamp if available

### ISSUE THREAD

**Issue by firstrose** [tatsuhiro-t/aria2#486]
Would you add an option to do it? Just like -R of curl? Thanks in advance

**Comment by tatsuhiro-t** [comment]
We have had this feature quite some time: http://aria2.sourceforge.net/manual/en/html/aria2c.html#cmdoption-R

**Comment by tatsuhiro-t** [comment]
Please reopen this if -R option does not fix this issue.
