### ISSUE TITLE
Any plans for uTP protocol?

### ISSUE THREAD

**Issue by amirotin** [tatsuhiro-t/aria2#489]
Sorry for duplicating question, but since december 2014 there is no information. Do You have any plans for uTP protocol in aria2? At this moment it is widespread protocol in bittorrent.

**Comment by tatsuhiro-t** [comment]
I don't say uTP support is not coming.  But we have no progress at the moment in this regard.
For myself, I don't have urgent need for uTP at the moment.

**Comment by amirotin** [comment]
It is sad to hear, hopefully in the near future you will have time to make it.
