### ISSUE TITLE
Torrents added with "waiting" status

### ISSUE THREAD

**Issue by amirotin** [tatsuhiro-t/aria2#490]
Situation:
I've downloaded 10 torrents. They are completed and now seeding. When i add new torrent - it stucks in state "waiting".

In config i've
```
check-integrity=false
bt-request-peer-speed-limit=100K
bt-max-peers=130
bt-max-open-files=100
max-download-result=10000
bt-detach-seed-only=true
...
```

When i restart aria2 - all torrents in "waiting" state starts downloading.

in what cases torrent can be in "waiting" status?

**Comment by tatsuhiro-t** [comment]
"waiting" state means it is waiting in queue, and download has not started yet.
Seeding torrents are treated as active downloads, and it is counted toward maximum concurrent downloads (-j option).  You might be interested in --bt-detach-seed-only

**Comment by amirotin** [comment]
`But be aware that seeding item is still recognized as active download in RPC method.` it means if i add torrent via rpc - it will not start if queue is full?

**Comment by tatsuhiro-t** [comment]
The statement in manual just means that "status" contains "active" label in aria2.tellStatus RPC method.

> And some offtop - it is possible to place control and torrent files in separate folder.

files downloaded and control files are written under the same directory given in -d option.

**Comment by amirotin** [comment]
If it is olny status, than something in my config is wrong.
```
# rpc
rpc-secret=zzz
enable-rpc=true
rpc-listen-all=true
rpc-allow-origin-all=true
rpc-listen-port=6800
rpc-save-upload-metadata=true

# session
continue=true
input-file=D:\Soft\aria2\main_list.gz
save-session=D:\Soft\aria2\main_list.gz
save-session-interval=60
deferred-input=true

# general
dir=T:\Finished
log=D:\Soft\aria2\aria.log
log-level=warn
disk-cache=256M
enable-mmap=false
file-allocation=trunc
disable-ipv6=true
#peer-id-prefix=-UT2210-
#user-agent=uTorrent/2210(25130)

# connection
max-connection-per-server=5
max-concurrent-downloads=5
max-download-result=10000
min-split-size=1M
split=5
max-overall-download-limit=8M
max-overall-upload-limit=8M
check-certificate=false

# torrents
bt-enable-lpd=true
bt-max-peers=130
bt-max-open-files=100
bt-request-peer-speed-limit=100K
enable-peer-exchange=true
enable-dht=true
enable-dht6=false
dht-file-path=D:\Soft\aria2\dht.dat
follow-torrent=true
follow-metalink=true
force-save=true
bt-detach-seed-only=true
#bt-seed-unverified=true
bt-save-metadata=true
#bt-hash-check-seed=true
#bt-stop-timeout=900
#check-integrity=true
seed-ratio=0.0
bt-exclude-tracker=http://retracker.local/announce
on-bt-download-complete=D:\Soft\aria2\oncomplete.bat

# console
enable-color=false
show-console-readout=false
summary-interval=0
```

With this configuration i still get new torrents in status "waiting". Maybe i miss something?

**Comment by tatsuhiro-t** [comment]
--bt-detach-seed-only works for me.  Not sure which option prevents your aria2 from doing things correctly.

**Comment by amirotin** [comment]
Is there any information why torrent is in waiting status if i'll enable debug logs?

**Comment by amirotin** [comment]
Update:
Even after torrent is completed it moves in waiting status.

**Comment by amirotin** [comment]
Still getting problem with waiting status. a little bit annoying to restart aria2 to start new downloads that are in waitnig status.
Still can not determine what is wrong with the settings.

**Comment by tatsuhiro-t** [comment]
Do you have easy reproduction steps?

**Comment by amirotin** [comment]
OK. I finally found what happens!
My config is in above comment.

Steps to reproduce:
1. Add torrents more than max-concurrent-downloads. To speed up testing i set max-concurrent-downloads=2. I use 10 torrent files. It does not matter what size, type (single, multi).
2. When first 2 torrents are downloaded aria2 start next 2.
3. While downloading next torrents - pause, unpause first 2 torrents (or what count you set in max-concurrent-downloads). They got waiting status.
4. After aria2 downloads current torrents it does not start next uncompleted torrents. It starts previously unpaused torrents. And thats all. No new torrents are downloaded until i restart.

It other words: if we have some unpused torrents - they use download slots (and does not free them) instead of uncompleted torrents.

I got this situation becouse my on-bt-download-complete command is moving files after download. And to move them it needs to pause/unpause torrent.

**Comment by tatsuhiro-t** [comment]
Thank you.
I followed your steps.  Only difference was I used 5 torrents.

1. add 5 torrents using -i list option, and -j2 and --bt-detach-seed-only
2. pause 2 active torrents, and then unpause them
3. let downloads go.

First 2 torrents were done, then unpaused 2 torrents were started, which is expected behaviour.
Then last 1 torrent was started.
All downloads went fine; Because I used --bt-detach-seed-only, all 5 downloads got SEED state.

Still could not reproduce this issue.

**Comment by amirotin** [comment]
Torrents you have paused was active and completed? Or downloading?

In my case i paused active and completed torrents.
2 дек. 2015 г. 4:44 PM пользователь "Tatsuhiro Tsujikawa" <
notifications@github.com> написал:

**Comment by tatsuhiro-t** [comment]
I paused 2 active torrents, which were started at startup.

**Comment by amirotin** [comment]
What do you mean under "active"? The problem accurs only if you paused
completed torrents, that are seeding only.
2 дек. 2015 г. 4:58 PM пользователь "Tatsuhiro Tsujikawa" <
notifications@github.com> написал:

**Comment by tatsuhiro-t** [comment]
active means it is being downloaded, not seeding.
So you paused/unpased torrent in seeding state?  Re-reading your comment, I think that is the case.
Will try again..

**Comment by amirotin** [comment]
Yeap. Torrents was in seeding state.

**Comment by tatsuhiro-t** [comment]
Thanks.  I successfully reproduced this bug.

**Comment by amirotin** [comment]
In my case torrents are paused by oncomplete command. In most cases they are seeding in moment of pause.

**Comment by amirotin** [comment]
Hooray! :)

**Comment by tatsuhiro-t** [comment]
The above commit should fix this issue.

**Comment by amirotin** [comment]
Tested! Thx!
