### ISSUE TITLE
[Question] Is not using check-integrity the correct way to resume a torrent?

### ISSUE THREAD

**Issue by txtsd** [tatsuhiro-t/aria2#491]
Only asking because the man page isn't clear about it.
Is it sufficient to use `realtime-chunk-checksum`?

**Comment by tatsuhiro-t** [comment]
If control file (*.aria2 file) is present, you don't have to do anything, just run aria2 with the same arguments.
If control file is missing, use -V option.

**Comment by txtsd** [comment]
What is the switch to create a control file? I'd like to add it to my conf because there's no control file being created in the torrent's top level directory.

**Comment by amirotin** [comment]
You must set force-save=true
```
Save download with --save-session option even if the download is completed or removed. This option also saves control file in that situations. This may be useful to save BitTorrent seeding which is recognized as completed state.
```

**Comment by txtsd** [comment]
@amirotin It still rechecks the entire torrent when I use `force-save=true`

**Comment by amirotin** [comment]
Is check-integrity eneabled? If yes - it will recheck torrents.

**Comment by txtsd** [comment]
Ah! So `realtime-chunk-checksum` is the only flag it needs to check pieces while downloading?
And I should only use `check-integrity` when I want to verify the entire torrent?

**Comment by amirotin** [comment]
realtime-chunk-checksum - checksum of file part while downloading
check-integrity - checks entire file/torrent after download

**Comment by txtsd** [comment]
Great! Thanks for clearing this up!
