### ISSUE TITLE
Some magnets aren't recognized

### ISSUE THREAD

**Issue by clamsawd** [tatsuhiro-t/aria2#492]
For some reason, the magnets-links of certain web pages don't work or are recognized by aria2. For example, the following magnet show this message:

> $ aria2c "magnet:?xt=urn:btih:4qf3dxhtmsfhzbnvnzopiepbgzt5bcon"

> Exception caught
> Exception: [download_helper.cc:417] errorCode=1 Unrecognized URI or unsupported protocol: magnet:?xt=urn:btih:4qf3dxhtmsfhzbnvnzopiepbgzt5bcon

The magnet works fine in other bittorrent clients. However the following magnet works correctly in aria2:

> $ aria2c "magnet:?xt=urn:btih:b827183faa50cc8dcacba93eadbbec4e9a4e1923"

**Comment by tatsuhiro-t** [comment]
It looks like aria2 only supported uppercase letters in base32 decoding.
d0b6a88 fixes this issue.

**Comment by clamsawd** [comment]
Wow!, quick response and quick solution as usual in you, thanks @tatsuhiro-t
