### ISSUE TITLE
Provide some information in logs about trackers

### ISSUE THREAD

**Issue by amirotin** [tatsuhiro-t/aria2#494]
Hi. Sometimes i get this error in logs
```
2015-11-30 00:23:37.734301 [ERROR] [TrackerWatcherCommand.cc:130] Exception caught
Exception: [DefaultBtAnnounce.cc:289] errorCode=1 Tracker returned null data.
```

As i understand - it is about error accessing some trackers eg ```retracker.local```
Or if torrent is not registred in tracker?

Could you add some more information in log (level warn). Tracker name, tracker answer, torrent id (i.e. gid) or something else.

**Comment by tatsuhiro-t** [comment]
Done 8fbfb3ac84f53839de486a9748679bdf21e010ac

**Comment by amirotin** [comment]
Thx!
