### ISSUE TITLE
C# graphical wrapper to Aria2c

### ISSUE THREAD

**Issue by andrea-bigi** [tatsuhiro-t/aria2#497]
hello everyone,

i'm creating a small graphical interface to show the download progress from our ftp site during a setup procedure (through an installer created using Inno Setup).

![2015-11-30 18_07_52-downloading](https://cloud.githubusercontent.com/assets/10382312/11478617/5e339aee-978e-11e5-976a-204bfb6bb7ce.png)

i've parsed the console output to catch statistics...

Everything is ok since the number of files to download is small.
if the number increases, the console doesn't show all the files' download info.

is there an easy way to get the total file size to download ? (so I can show a correct progress bar)

thanks
Andrea

**Comment by BeketovOleksii** [comment]
hi,

i've used .aria2 control files for that purpose. They contain info on the whole file's size and a bitfield section which active bits represents downloaded fragments of file, that gives possibility to count out the download progress.

sincerely,
Oleksii

**Comment by andrea-bigi** [comment]
Ok, but it seems that .aria2 control files keep track of the download of the single file.

The question is: is there a pre-download-start-phase that computes how many total bytes are requested for the download of all the files specified in the input-file ?

Bye
Andrea


Da: BeketovOleksii [mailto:notifications@github.com]
Inviato: martedì 1 dicembre 2015 14:32
A: tatsuhiro-t/aria2 <aria2@noreply.github.com>
Cc: Bigi Andrea <abigi@ferrettogroup.com>
Oggetto: Re: [aria2] C# graphical wrapper to Aria2c (#497)


hi,

i've used .aria2 control files for that purpose. They contain info on the whole file's size and a bitfield section which active bits represents downloaded fragments of file, that gives possibility to count out the download progress.

sincerely,
Oleksii

**Comment by tatsuhiro-t** [comment]
Does --truncate-console-readout help?
http://aria2.sourceforge.net/manual/en/html/aria2c.html#cmdoption--truncate-console-readout

If you want all active downloads, you have to use RPC.

**Comment by andrea-bigi** [comment]
I’ve seen --truncate-console-readout option, and I set it to false to show all the data about active download.

The matter is “active download”, I’d like to see the total size of ALL the files to download.

But I’ve understood that Aria2 doesn’t compute this before starting downloading (this is not a disapproval….aria2 is a great software !!!)

Thanks
Andrea Bigi


Da: Tatsuhiro Tsujikawa [mailto:notifications@github.com]
Inviato: martedì 1 dicembre 2015 16:12
A: tatsuhiro-t/aria2 <aria2@noreply.github.com>
Cc: Bigi Andrea <abigi@ferrettogroup.com>
Oggetto: Re: [aria2] C# graphical wrapper to Aria2c (#497)


Does --truncate-console-readout help?
http://aria2.sourceforge.net/manual/en/html/aria2c.html#cmdoption--truncate-console-readout

If you want all active downloads, you have to use RPC.

**Comment by tatsuhiro-t** [comment]
Thanks.  Can we close this issue?

**Comment by andrea-bigi** [comment]
Sure


Inviato da Samsung Mobile



-------- Messaggio originale --------
Da: Tatsuhiro Tsujikawa <notifications@github.com>
Data: 02/12/2015 15:00 (GMT+01:00)
A: tatsuhiro-t/aria2 <aria2@noreply.github.com>
Cc: Bigi Andrea <abigi@ferrettogroup.com>
Oggetto: Re: [aria2] C# graphical wrapper to Aria2c (#497)



Thanks. Can we close this issue?
