### ISSUE TITLE
--on-download-complete performs on download start either

### ISSUE THREAD

**Issue by Spellenger** [tatsuhiro-t/aria2#499]
Hello,

it appears that if aria2 being ran with command line using --on-download-complete=command flag, the specified command performs both on download start and download complete.

I've tried binaries 1.19.2 x64 win, 1.13.0 lin, 1.17.1 x32 win, all behaviored the same.

Please clarify how to make aria2 to execute a command not until download completion.

Thanks,
Oleksii

**Comment by tatsuhiro-t** [comment]
It should run on download has completed.
If you download .torrent file, aria2 run --on-download-complete when it is done, and then continues to download torrent itself.  This may be viewed as command is executed twice.

**Comment by Spellenger** [comment]
I've got the point. The first execution takes place in case if the .meta4 file is being loaded first.

Thx!

**Comment by tatsuhiro-t** [comment]
OK, let's close the issue.
