### ISSUE TITLE
aria2c doesn't exit after BT download

### ISSUE THREAD

**Issue by cykerway** [tatsuhiro-t/aria2#507]
aria2c doesn't exit after a BT download even if `--seed-time=0` is specified. Adding
`--enable-dht=false` will make it exit instantly after download. So I guess it's doing something
related to DHT. What is exactly happening and how to fix it? Thank you.

Here's the log:

    .[#043b6f SEED(0.0) CN:0 SD:0]
    12/17 18:10:44 [DEBUG] Updating periodicTaskQueue1
    12/17 18:10:44 [DEBUG] Executing 0 Task(s). Queue has 0 task(s).
    12/17 18:10:44 [DEBUG] Updating periodicTaskQueue2
    12/17 18:10:44 [DEBUG] Executing 0 Task(s). Queue has 0 task(s).
    12/17 18:10:44 [DEBUG] Updating immediateTaskQueue
    12/17 18:10:44 [DEBUG] Executing 0 Task(s). Queue has 0 task(s).
    12/17 18:10:44 [DEBUG] 0 dht messages remaining in the queue.

**Comment by tatsuhiro-t** [comment]
Probably, it waited for the response from UDP tracker.  UDP tracker is only enabled when DHT is enabled.

**Comment by cykerway** [comment]
Yes I'm using UDP trackers. But I think aria2c can feel free to disconnect when the download is complete given that I explicitly set `--seed-time=0`. So this waiting seems to be unnecessary.

I'm using aria2c to download multiple files one by one interactively and this kind of waiting is not acceptable. What I currently do is to use a hook script to kill aria2c on the `-on-bt-download-complete` event. It works but adds additional code complexity. Therefore I'm interested in why this waiting is necessary and how to avoid it. Thank you.

**Comment by tatsuhiro-t** [comment]
It is a common behaviour of bittorrent client to report tracker when it exits from swarm.
We have 15 seconds reset UDP packet timeout, and 1 minute "give up" timeout.  Probably, we can reduce these numbers.

**Comment by cykerway** [comment]
If you use it as a daemon then these timeouts don't really matter. But if you use it as an interactive tool then any non-trivial timeout doesn't look nice. Think about downloading 100 files and each file requires 10 seconds to download. If we add another 10 seconds timeout then it doubles the total time.

**Comment by tatsuhiro-t** [comment]
Probably, bittorrent is not suitable for super responsive interactive tool you imagine.  It has a protocol that client should obey.
Anyway, reduced timeout should improve the situation.

**Comment by cykerway** [comment]
All right, I'll just use the trick to finish my task at hand. But if you are interested in offering users an option to exit when download completes, then you an always do it in a future version - and it won't break compatibility if not set as default. Issued closed since the story is clear. Thank you for explanation.
