### ISSUE TITLE
input file error in multi http source?

### ISSUE THREAD

**Issue by kennel209** [tatsuhiro-t/aria2#508]
When I use input file(-i), where there is multi source in url line, ERROR report on URL.

Seems it translate SPACE to %20

for example:

file.input:
```
http://some.xxx.com/1.iso?src=111 http://some.yyy.com/1.iso?src=kkk
    out=a/1.iso
```

it requests "URL=http://some.xxx.com/1.iso?src=111%20http://some.yyy.com/1.iso?src=kkk"
```
aria2c -i file.input
```
Failed.

When call for shell directly, it request normally. Works fine.
```
aria2c --out a/1.iso http://some.xxx.com/1.iso?src=111 http://some.yyy.com/1.iso?src=kkk
```

**Comment by tatsuhiro-t** [comment]
Please use TAB to split URIs in the same line when using input file.

**Comment by kennel209** [comment]
@tatsuhiro-t  Thanks. It works. Sorry for misunderstanding for the manual. I only use TAB to split options.
