### ISSUE TITLE
Support --continue in bt downloads

### ISSUE THREAD

**Issue by cykerway** [tatsuhiro-t/aria2#510]
I found this in `man aria2c`:

> -c, --continue[=true|false]
> Continue downloading a partially downloaded file.  Use this option to resume a download started by a
> web browser or another  program  which downloads  files sequentially  from the beginning.  Currently
> this option is only applicable to HTTP(S)/FTP downloads.

Does this mean `-c` doesn't work in bt downloads? Or is this man page outdated on this? Domo arigado.

**Comment by tatsuhiro-t** [comment]
You don't need -c option for BitTorrent.
In generally, if you have corresponding control file (*.aria2 file), then you don't need -c option.
If you don't have one, use -V option for BitTorrent to validate current downloaded file, and then aria2 continues to download the missing pieces.

**Comment by cykerway** [comment]
I did some experiments.

If I have `.aria2` file, then aria2c can resume from last download. Good.

If I don't have `.aria2` file, then I have two options:

1.  Without `-V` options, aria2c restarts from the very begining.

2.  With `-V`, it can resume from last download. However, it displays an error message:

        [ERROR] Checksum error detected. file=...

    This is confusing since I don't know whether the resume is successful or not. If the resume is guaranteed to be correct, knowing how to disable the error message will be helpful.

    By the way, my torrent file doesn't have piece hash.

**Comment by tatsuhiro-t** [comment]
I don't know the torrent file without piece hash.
aria2 shows error and does not process such broken torrent file.

**Comment by cykerway** [comment]
OK I recreated another torrent file and double checked the piece hash. It looks OK and I can download using this torrent with both aria2c and deluge. However, aria2c still outputs an error message when resuming a partial download without the help of `*.aria2` file. I don't understand where it comes from. For all completed chunks, it can verify using piece hash. If the last chunk is incomplete, then its hash is of course not the same as in the torrent file. Is this where the error comes from?

**Comment by tatsuhiro-t** [comment]
It is OK to see "Checksum error detected" with -V.  It tells that aria2 found some missing pieces (missing piece will emit checksum error), and aria2 is going to resume the download.
I agree that the message could be improved in this case.
The thing is the functionality is shared in multiple code path, and in some code path, error message is appropriate. Will see how to improve this.

**Comment by cykerway** [comment]
Thank you for acknowledgement. I think it may be helpful if you use `cerr` for log messages so that users can write `2>/dev/null` if not interested. Created a patch for it: <https://github.com/tatsuhiro-t/aria2/pull/511>.
