### ISSUE TITLE
Unable to download file, error 24

### ISSUE THREAD

**Issue by Immortalin** [tatsuhiro-t/aria2#512]
I am trying to [download a file](http://sriramiyer.net/blog/2015/03/28/wget/) from [here](http://www.sammobile.com/firmwares/database/GT-I9506/), after logging in, I passed the download url to aria2 together with the cookie file. However, I am getting `errorCode=24 Authorization failed`.  How do I fix this?

**Comment by tatsuhiro-t** [comment]
"Authorization failed" means usually basic authorization is required and failed.  Did you set username/password?
