### ISSUE TITLE
clang-format

### ISSUE THREAD

**Issue by tatsuhiro-t** [tatsuhiro-t/aria2#513]
Let's introduce clang-format, so that we can say good-bye to scattered code formatting style.
Using uniformed style is good for maintainability, and clang-format gives us good productivity boost since we don't have to manually adjust styles.

cc @nmaier

**Comment by tatsuhiro-t** [comment]
0a63a7e adds proposed .clang-format file, and `make clang-format`. (set git config --add clangformat.binary to clang-format executable).

@nmaier Any recommendations for .clang-format file?

**Comment by nmaier** [comment]
Seems to closely resemble the `.clang-format` I've been using.

**Comment by tatsuhiro-t** [comment]
Good, so if you are ok, then I'll perform `make clang-format` and push.
Note that we use clang-format-3.6 until ubuntu gets 3.7 as default (clang-format formats code differently between versions unsurprisingly).

**Comment by nmaier** [comment]
>Note that we use clang-format-3.6 until ubuntu gets 3.7 as default (clang-format formats code differently between versions unsurprisingly).
eek.... I'll manage.. somehow

**Comment by tatsuhiro-t** [comment]
Which version are you using?

**Comment by tatsuhiro-t** [comment]
The slight formatting deviation is not critical, and we can manage that.
I'll `make clang-format` and push them into master.

**Comment by tatsuhiro-t** [comment]
Done.
