### ISSUE TITLE
Doc Error: example for -i / -d has the wrong filename

### ISSUE THREAD

**Issue by allo-** [tatsuhiro-t/aria2#514]
`` If  aria2  is  executed  with  -i  uri.txt  -d  /tmp  options,  then  file.iso  is  saved  as  /iso_images/file.img ``

I think the ``.img`` should be a ``.iso``

**Comment by tatsuhiro-t** [comment]
The documentation is correct, since `out=file.img` is given, the output file name becomes file.img.

**Comment by allo-** [comment]
ah, sorry the uri.txt contains the filename in the example. I overlooked that it is .img there as well.
