### ISSUE TITLE
Using multiple interfaces breaks Local Peer Discovery

### ISSUE THREAD

**Issue by Domini** [tatsuhiro-t/aria2#523]
@sarim, @tatsuhiro-t, thank you for adding multiple interfaces support in #364. The feature mostly works and finally allows to utilize whole bandwidth. ;)

Unfortunately it has also introduced a bug. 

When you enable both multiple interfaces and Local Peer Discovery the latter ceases to work with following output

```
$ aria2c --bt-enable-lpd=true --multiple-interface=eth0,eth1 *.torrent
01/06 16:17:21 [NOTICE] IPv4 DHT: listening on UDP port 6909
01/06 16:17:21 [NOTICE] IPv6 DHT: listening on UDP port 6909
01/06 16:17:21 [NOTICE] IPv4 BitTorrent: listening on TCP port 6913
01/06 16:17:21 [NOTICE] IPv6 BitTorrent: listening on TCP port 6913
01/06 16:17:21 [ERROR] Failed to initialize LPD message receiver.
Exception: [SocketCore.cc:327] errorCode=1 Failed to bind a socket, cause: Given address and resolved address do not match.
01/06 16:17:21 [ERROR] Failed to initialize LPD message receiver.
Exception: [SocketCore.cc:327] errorCode=1 Failed to bind a socket, cause: Given address and resolved address do not match.
```

Setting either --bt-lpd-interface=eth0 or eth1 does not help. 

Could you look into this?

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this bug.
I think this probably caused by the fact that BitTorrent LPD requires IPv4 address.  With multiple interfaces, IPv6 may be wrongly used.

**Comment by tatsuhiro-t** [comment]
The above commit should fix this issue.
