### ISSUE TITLE
Check Content-MD5 HTTP header

### ISSUE THREAD

**Issue by zingaburga** [tatsuhiro-t/aria2#524]
I couldn't find any info on it, so I assume that the feature doesn't exist.
It would be nice if one could supply a flag to aria2 to check the [Content-MD5 HTTP header](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.15) if a server gives it.
It would be similar to if the user supplied an MD5 checksum directly to aria2.  Slight difference is that Content-MD5 is affected by Content-Encoding.

The value should be 'saved' (similar to Content-Length) in case ranged requests don't return a Content-MD5.
The header could also appear in a HTTP trailer, so that should be checked too.

Thanks for the excellent download utility! :)

**Comment by tatsuhiro-t** [comment]
Content-MD5 is not supported.  Instead, aria2 supports Digest header field (https://tools.ietf.org/html/rfc3230).
Also aria2 does not support trailer fields at all.

**Comment by zingaburga** [comment]
Ah, I didn't know about that header.  Thank you for the information!
