### ISSUE TITLE
(Win)I can't select other drive

### ISSUE THREAD

**Issue by inoue64** [tatsuhiro-t/aria2#525]
C:\Users\username>aria2c -o d:\d\160110.txt http://www.example.com

01/10 09:44:50 [ERROR] CUID#6 - Download aborted. URI=http://www.example.com
Exception: [AbstractCommand.cc:399] errorCode=18 URI=http://www.example.com
  -> [RequestGroup.cc:714] errorCode=18 Download aborted.
  -> [util.cc:1486] errNum=22 errorCode=18 Failed to make the directory C:/Users/username/d:/d, cause: Invalid argument

01/10 09:44:50 [NOTICE] Download GID#03fc6b1ce396cd16 not complete: C:/Users/username/d:/d/160110.txt

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
03fc6b|ERR |       0B/s|C:/Users/username/d:/d/160110.txt

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

C:\Users\username>

**Comment by tatsuhiro-t** [comment]
Use -d option to set directory (without filename).  Then, use -o option to set file name relative to -d option.

**Comment by tatsuhiro-t** [comment]
Please reopen this issue if -d and -o options do not work as I expected.
