### ISSUE TITLE
Failed to cross compile for ARM.

### ISSUE THREAD

**Issue by Haocen** [tatsuhiro-t/aria2#526]
It seemed c-ares have some machine specific header named: ares_build.h that can only be generated dynamically while compiling. Since I'm not compiling on ARM so this file is missing, preventing me from further operation. I wonder if there is a way to get around this, because c-ares doesn't seemed to be optional.
I'm compiling on Ubuntu 14.04 LTS
What I get after running ./configure --host=arm-linux-gnueabi :
>Build:          x86_64-unknown-linux-gnu
>Host:           arm-unknown-linux-gnueabi
>Target:         arm-unknown-linux-gnueabi
>Install prefix: /usr/local
>CC:             arm-linux-gnueabi-gcc
>CXX:            arm-linux-gnueabi-g++
>CPP:            arm-linux-gnueabi-gcc -E
>CXXFLAGS:       -g -O2 -pipe -std=c++11 
>CFLAGS:         -g -O2 -pipe
>CPPFLAGS:       -I$(top_builddir)/deps/wslay/lib/includes -I$(top_srcdir)/deps/wslay/lib/includes         
>LDFLAGS:        
>LIBS:           -lcares   -lssl -lcrypto   -lsqlite3   -lz   
>DEFS:           -DHAVE_CONFIG_H
>LibUV:          
>SQLite3:        yes
>SSL Support:    yes
>AppleTLS:       
>WinTLS:         no
>GnuTLS:         no
>OpenSSL:        yes
>CA Bundle:      
>LibXML2:        
>LibExpat:       
>LibCares:       yes
>Zlib:           yes
>Libssh2:        no
>Epoll:          
>Bittorrent:     yes
>Metalink:       no
>XML-RPC:        
>Message Digest: openssl
>WebSocket:      yes
>Libaria2:       no
>bash_completion dir: ${datarootdir}/doc/${PACKAGE_TARNAME}/bash_completion
>Static build:

**Comment by tatsuhiro-t** [comment]
I can cross-compile Android ARM build using Android NDK and c-ares statically compiled for that architecture.
c-ares is not required library.  Pass --without-libcares to configure.

**Comment by Haocen** [comment]
Thank you, I tried --without-libcares but some redefinition error turned up instead, I'll keep looking into it.

**Comment by Haocen** [comment]
For anybody interested in this topic please see:
> https://github.com/lancethepants/aria2-arm-musl-static
