### ISSUE TITLE
hope support partly download (http).

### ISSUE THREAD

**Issue by sickHamm** [tatsuhiro-t/aria2#529]
Is it possible to support partly download, similar to the option "--rang" in  curl : "--range <range> Retrieve a  byte  range".
------------------------------------------------
simple add http header option like --header "Range: 0-1024" couldn't work;
aria2 will raise an error, because the response  Range not equal to aria2 expected;
In other words, aria2 don't understand the range  specified  in "--header", so it also couldn't fill the allocated file correct;

**Comment by tatsuhiro-t** [comment]
This is rather intentional.  aria2 has segmented downloading feature, and it relies on the exact calculation of range header field.  aria2 is a bit higher level application for download files.
If you are interested in lower level HTTP tools, curl is the best.

**Comment by sickHamm** [comment]
As as my primary downloader, please understand me want aria2 do everything, because aria2 use file pre-allocation, I could play the partly video file, although the video file is  downloading and not completely. but if want seek forward,aria2 will behind of player, so if aria2c support range option, I could manual select the range that I want download,
when i want seek play video.

Sure, it may a too special  feature request;

-------------------------
Sorry , My English is poor. I don't know is I  expression clearly what I want.

**Comment by tatsuhiro-t** [comment]
Thank you for explaining the use case.  I fully understood what you mean.

**Comment by xderoche** [comment]
I have the same need ! aria2 helps me a lot handling my recurrent download batches. The lack of partial download support force me to write everything from scractch for some of them.
It would be very useful to have this feature.
