### ISSUE TITLE
Client Certificate not working

### ISSUE THREAD

**Issue by haodong** [tatsuhiro-t/aria2#534]
## scene 1
I wrote __aria2.conf__ with `certificate=/path/to/client.p12`, which have a blank passphrase, and got this error.
```
01/17 11:01:54 [ERROR] Failed to import PKCS12 file. If you meant to use PEM, you'll also have to specify --rpc-private-key. See the manual.
```

## scene 2
I wrote __aria2.conf__ with `certificate=/path/to/client.pem` and `private-key=/path/to/client.key` and got another error.
```
01/17 11:05:35 [ERROR] Failed to load certificate from /path/to/client.pem and private key from /path/to/client.key. Cause: ASN1 parser: Error in DER parsing.
```

## my query
Does the manual of aria2 mean to use client's certificate files in the settings above?
Or, is it not my misuse but something else?

PS: I've dug the whole internet with my ability and found nothing except dozens of duplicated manuals.

Please help, thanks! :)

**Comment by tatsuhiro-t** [comment]
With scene1 and scene2, they work for me just fine.  I tested with both gnutls and openssl version.

For scene1, make sure that it has empty passphrase for pkcs12 file itself.
For scene2, make sure that they are really in PEM format.

**Comment by haodong** [comment]
@tatsuhiro-t Thanks! I redeployed the server and everything fine now. :+1:

**Comment by haodong** [comment]
Hi @tatsuhiro-t, error made again. This time, however, I got the point. Here it is.

When using RSA as private/public key algorithm, the .key, .pem and .p12 can be recognized.
When using EC(Elliptic Curve) as the key algorithm, those files would not be recognized.

If my assumption was true, I hope aria2 could support the advanced algorithm. Thank you!

**Comment by tatsuhiro-t** [comment]
ECDSA key pair works well in my aria2.

**Comment by haodong** [comment]
Hi @tatsuhiro-t . I solved it with recompile aria2.

`./configure --prefix=/usr --without-gnutls --with-openssl --with-openssl-prefix=/usr/local/ssl`

**Using OpenSSL** is very important. :)

Aria2 is really powerful! :+1:
