### ISSUE TITLE
Change references to sourceforge

### ISSUE THREAD

**Issue by kkartaltepe** [tatsuhiro-t/aria2#539]
Considering the mass exodus from sourceforge and the fact that it looks like this project has migrated to https://aria2.github.io/ as its main page, all references to http://aria2.sourceforge.net/ should probably be changed.

**Comment by tatsuhiro-t** [comment]
I did that in some extent.  Did you find the remnants?

**Comment by kkartaltepe** [comment]
I just noticed in the help text (1.19.3) it mentions
```
Report bugs to https://github.com/tatsuhiro-t/aria2/issues
Visit http://aria2.sourceforge.net/
```

**Comment by tatsuhiro-t** [comment]
Yes.  We finally moved to github after that release.  It has been corrected.

**Comment by kkartaltepe** [comment]
I see the place i happened upon in the code base were
https://github.com/tatsuhiro-t/aria2/blob/f57947d236aae0e8bf9e42f8e6e802b52d14a287/src/libaria2.pc.in#L38
https://github.com/tatsuhiro-t/aria2/blob/f57947d236aae0e8bf9e42f8e6e802b52d14a287/po/Makevars#L37
https://github.com/tatsuhiro-t/aria2/blob/f57947d236aae0e8bf9e42f8e6e802b52d14a287/doc/xmlrpc/README.txt#L3

Of these im not sure if any actually show up somewhere else, but these are the ones that seemed like they might have needed to be changed. If they are all fine you can go ahead and close the issue.

**Comment by tatsuhiro-t** [comment]
Thank you for spotting them.  They are fixed now.

**Comment by kkartaltepe** [comment]
Thanks ill go ahead and close this as I never found any more references.

**Comment by tatsuhiro-t** [comment]
Thank you!
