### ISSUE TITLE
Auto reconnect when connection is dropped

### ISSUE THREAD

**Issue by roooneey** [tatsuhiro-t/aria2#541]
I'm using aria2 over a high latency satellite connection. With the max number of parallel connections it's doing a great job so far, however after some time connections are dropped. With a low number of connections, downloads are getting slow. Sometimes even the last connection is dropped and the download gets stuck. Is there a way to force a auto reconnect? Couldn't find anything in the docs. 

Running with those params: 

* continue=true
* always-resume=true
* daemon=false
* file-allocation=falloc
* log-level=warn
* max-connection-per-server=16
* max-concurrent-downloads=3
* max-overall-download-limit=0
* min-split-size=1M
* split=20
* enable-http-pipelining=false
* stream-piece-selector=inorder

**Comment by tatsuhiro-t** [comment]
Have you tried --max-tries option?

**Comment by roooneey** [comment]
No, I didn't notice that option, but I gonna try, thanks. Does the HTTP status make a difference, or it's retrying anyway? I saw the command line output was full auf 504 errors, but also a lot of 403.

**Comment by roooneey** [comment]
I tested with *--max-tries=0* and so far there were 5 connections dropped and in the output I see this message 5 times: 
```
01/25 19:36:00 [ERROR] CUID#26 - Download aborted. URI=***
Exception: [AbstractCommand.cc:350] errorCode=22 URI=***
  -> [HttpSkipResponseCommand.cc:228] errorCode=22 The response status is not successful. status=504
```

So I guess there is no retry on http 504, or do I have to set *--retry-wait* as well?

**Comment by tatsuhiro-t** [comment]
ad6d799 enables retry for 504 status code.  --retry-wait may help depending on server.  We have --timeout option, but it probably does not help, since the timeout happens on backend of server side.

**Comment by roooneey** [comment]
Thanks for your update. I have difficulties to build it on os x, so I guess I have to wait for a release.
