### ISSUE TITLE
OS X 10.11.2 --zsh: command not found: aria2c

### ISSUE THREAD

**Issue by Chen-Sir** [tatsuhiro-t/aria2#543]
I installed the aria2-1.19.3-osx-darwin.dmg,and the path is  /usr/local/aria2.  But when i use the "aria2c" command, it happens "zsh: command not found: aria2c". 
How to solve it?

**Comment by Chen-Sir** [comment]
It should be “how do you fix it” but not "how dose you fix it " .         haha     
不好意思，这是好久之前解决的问题了，我也忘了怎么处理的。不过这里有一篇博客，https://zhuanlan.zhihu.com/p/20563721 <https://zhuanlan.zhihu.com/p/20563721>，博客下面的评论里说明了解决的办法：

“	安装 aria2 后，没有貌似没有自动软链到 /usr/local/bin 下，直接运行 aria2c 会提示 command not found
	看了下aria2c的文件位置，运行以下命令可以解决：
	cd /usr/local/bin; 
	sudo ln -s ../aria2/bin/aria2c aria2c

	希望能对遇到同样问题的朋友有帮助。
”

**Comment by Art2Cat** [comment]
Mac version: 10.13
Aria2 version: 1.32.0
use soft link:
sudo ln -s /usr/local/aria2/bin/aria2c aria2c

**Comment by ZeRuTian** [comment]
您好，我按照您上面给出的解决办法，仍旧提示command not found ，请问您知道是什么原因吗？

**Comment by WuHarry** [comment]
> 您好，我按照您上面给出的解决办法，仍旧提示command not found ，请问您知道是什么原因吗？

可能的原因是，现在brew安装aira2之后的路径是在 /usr/local/Cellar/ 底下，你可能得修改一下命令的路径
