### ISSUE TITLE
Use Cookie STRING for each single file

### ISSUE THREAD

**Issue by sky93** [tatsuhiro-t/aria2#545]
How can I use cookie string (Not file) for a single file download?

For example something like this:

`aria2c --cookie='session=3f543ac31fc092bd' http://example.com/1.zip`

**Comment by luokar** [comment]
@sky93 
You could use header for this propose:
`aria2c --header="Cookie:session=3f543ac31fc092bd" http://example.com/1.zip`

**Comment by yxliang01** [comment]
I think it would be nicer to have an option for it.

**Comment by eladkarako** [comment]
<strong>First</strong> You are missing a <strong>single-space</strong> character after <code>Cookie:</code>,  it's very important.
<code>aria2c --header="Cookie: session=3f543ac31fc092bd" http&#x003A;&#x002F;&#x002F;example.com/1.zip</code>

Also,  everything should be <strong>escaped</strong> before putting it into a cookie header,  
you can use JavaScript's <del><code>escape</code></del> <code>encodeURIComponent("your text here")</code> method (for example open a browser, then the developer-panel, then go to console and type there, or use nodejs from your command-line).

Finally,  you can not use the value of <code>document.cookie</code> from the browser (for example) as is in aria2,  
You only use the key=value part, and you need to split each key=value into its own <code>--header="Cookie: ..."</code> argument.  

For example <code>"_ga=GA1126152; _octo=GH15463; tz=New%20York"</code>,  
will be: <code>aria2c --header="Cookie: _ga=GA1126152" --header="Cookie: _octo=GH15463" --header="Cookie: tz=New%20York" http&#x003A;&#x002F;&#x002F;example.com/1.zip</code>.

**Comment by lfitzpatrick** [comment]
I have just spent some time trying to resolve this issue for myself. After a lot of trial an error the most reliable approach for Chrome was to use the Network tab to read the Request Header.
Copying the "cookie: " section of the request header and pasting after --header="Cookie: (including a single space between the : and the pasted section, has worked for multiple sites without issue.

Target selection area starts at "adl=" and ends at %7D in the image below. (Sorry for the messy edits, not sure what data could be leaked if left)

![image](https://user-images.githubusercontent.com/5046143/97107066-78f11080-1693-11eb-9df8-6186cbf47ba7.png)
