### ISSUE TITLE
Session won't be saved when aria2 exit due to INT signal or with --stop option.

### ISSUE THREAD

**Issue by luokar** [tatsuhiro-t/aria2#553]
platfrom:     windows7
file system: NTFS
version:      latest build from github
How to reproduce this problem: Start downloading something and press control+c when the file is unfinished.

Is this an expected behavior or a configuration error?
I leave save-session-interval to be default 0 which "file will be saved only when aria2 exits". Session should be saved no matter what exit status returned. Is that correct?

**Comment by luokar** [comment]
Sorry it is a configuration error. I accidently set max-download-result=0, but why unfinished task won't be serialized into session when max-download-result=0?

**Comment by tatsuhiro-t** [comment]
This is because incomplete downloads first get stopped, and counted toward max-download-result limit.
