### ISSUE TITLE
[question] cannot download video

### ISSUE THREAD

**Issue by yagami1234** [tatsuhiro-t/aria2#554]
i'm using aria for openwrt and i have some issue

so far i tested aria to download file i have no problem,but when i try download video suddenly error message appear

for example video like this
https://r6---sn-npo7zn7r.googlevideo.com/videoplayback?id=763956725112ed16&itag=18&source=webdrive&begin=0&requiressl=yes&mm=30&mn=sn-npo7zn7r&ms=nxu&mv=m&nh=IgpwcjAzLnNpbjAxKgkxMjcuMC4wLjE&pl=24&mime=video/mp4&lmt=1454256682499994&mt=1454403587&ip=180.214.232.80&ipbits=8&expire=1454432498&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,nh,pl,mime,lmt&signature=6C6371CBFD19295A4E9274C3F048FF390512E81A.9DB7884C1A8F6CDE9774C32C100D71171FB063C4&key=ck2

when i try download video not from webui aria and instead i try from PuTTY more specific error written:
**errorCode=1 SSL/TLS handshake failure: unable to get local issuer certificate**
so i'm trying to bypass it by using syntax *--check-certificate=false*
but when i try it,it's still error with message 
**errorCode=1 Unrecognized URI or unsupported protocol: Use**
what should i do to fix this error and i can download video?

**Comment by tatsuhiro-t** [comment]
Did you quote your URI with single quotes (') or double quotes (") when you entered it in terminal?  Since your URI includes "&", which has special meaning in shell, it must be quoted.

**Comment by yagami1234** [comment]
no,i'm not quote my url with single quotes/double quotes
but after try it just now,the download is working right now :D thank you so much for your help
