### ISSUE TITLE
tellStatus should return "Seeding"

### ISSUE THREAD

**Issue by kkartaltepe** [tatsuhiro-t/aria2#557]
Just like how I can see the status is "SEED" in the aria2c display. It would be helpful for the various ui's built around the RPC interface I would imagine. And for myself in particular.

**Comment by tatsuhiro-t** [comment]
25615fcb1744e94f4774aaee24ed4db172af397f adds "seeder" key to tellStatus response.  It becomes "true" if the local endpoint is seeder, otherwise "false".

**Comment by gerases** [comment]
I was just going to ask for that. Currently I'm comparing the length of the file and the downloaded length.

**Comment by kkartaltepe** [comment]
Thanks, that was amazingly quick!

**Comment by gerases** [comment]
Whoot!

**Comment by tatsuhiro-t** [comment]
OK, let's close the issue.
