### ISSUE TITLE
build aria2

### ISSUE THREAD

**Issue by roulis2844sasha** [tatsuhiro-t/aria2#563]
Здравствуйте.
Не могли бы Вы компилировать под архитектуры арм и х86.
А не только для Windows ;)
Дело в том что я пользуюсь Гугл Хром ОС.
Спасибо.

Hello.
Could you compile for x86 and ARM architectures.
And not only for Windows;)
The fact that I use the Google Chrome OS.
Thank you.

**Comment by clamsawd** [comment]
Chrome OS uses the Linux kernel, maybe the following static packages works on x86 architectures:

* [aria2-1.20.0-linux-gnu-32bit-build1.tar.bz2](https://github.com/clamsawd/aria2-static-builds/releases/download/v1.20.0/aria2-1.20.0-linux-gnu-32bit-build1.tar.bz2)
* [aria2-1.20.0-linux-gnu-64bit-build1.tar.bz2](https://github.com/clamsawd/aria2-static-builds/releases/download/v1.20.0/aria2-1.20.0-linux-gnu-64bit-build1.tar.bz2)

As well, the android package maybe works on ARM architecture:

* [aria2-1.20.0-android-build1.zip](https://github.com/tatsuhiro-t/aria2/releases/download/release-1.20.0/aria2-1.20.0-android-build1.zip)

Try it and tell us if really works, xD

**Comment by roulis2844sasha** [comment]
Thanks, it works
