### ISSUE TITLE
error when set the config file path

### ISSUE THREAD

**Issue by gky99** [tatsuhiro-t/aria2#564]
gky$ aria2c --conf-path=/Users/gky/.aria2/aria2.conf

Exception caught
Exception: [../../../src/download_helper.cc:528] errorCode=1 Failed to open the file /etc/aria2/aria2.session, cause: No such file

on MacOS El captain
installed via the package

**Comment by tatsuhiro-t** [comment]
The error indicates that file /etc/aria2/aria2.session is missing.  Create the file, and try again.

**Comment by gky99** [comment]
thank you a lot!

**Comment by succezlijunyi** [comment]
这里最好是下载别人配置好的通用的，太麻烦了
