### ISSUE TITLE
Impossible to use GID when downloading a torrent

### ISSUE THREAD

**Issue by Edo78** [tatsuhiro-t/aria2#571]
When I set a GID for a torrent download (I'm passing the URL) then aria use my GID for the METADATA and the real download got an automatically generated GID.
This way when the download is completed the hook return a GID different from the one I set.

You can test by yourself `aria2c --gid=0123456789abcdef http://cdimage.debian.org/debian-cd/8.3.0/amd64/bt-cd/debian-8.3.0-amd64-netinst.iso.torrent` 

The result would be something like
```
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
012345|OK  |   266KiB/s|/tmp/debian-8.3.0-amd64-netinst.iso.torrent
db980a|OK  |   824KiB/s|/tmp/debian-8.3.0-amd64-netinst.iso
```

So if I try to use the `--on-bt-download-complete` I got the automatically generate GID.

If this is the intended behaviour it pretty frustrating because I cannot know exactly which download is completed while using the JSON-RPC interface.

**Comment by tatsuhiro-t** [comment]
aria2.tellStatus RPC method has `followedBy` attribute.
https://aria2.github.io/manual/en/html/aria2c.html#aria2.tellStatus

GID 012345 has followedBy attribute which includes db980a.

Perhaps, it is better to add reverse link from generated download item to make getting producer easier.

**Comment by Edo78** [comment]
A reverse link should make it a lot easier but I'll try to use the followedBy attribute.
Thank you very much

**Comment by tatsuhiro-t** [comment]
We added `folloing` key as a reverse link for followedBy via commit 21754fa
