### ISSUE TITLE
Gaining privilege SeManageVolumePrivilege failed

### ISSUE THREAD

**Issue by clamsawd** [tatsuhiro-t/aria2#574]
Since version 1.20.0, aria2 displays an error when I run the binary on Windows 10 (64-bit). The error is the following:

> C:\Users\clamsawd>aria2c
> 
> 02/18 15:19:10 [WARN] Gaining privilege SeManageVolumePrivilege failed.
> 
> 02/18 15:19:10 [WARN] --file-allocation=falloc will not work properly.
> Specify at least one URL.
> Usage: aria2c [OPTIONS] [URI | MAGNET | TORRENT_FILE | METALINK_FILE]...
> See 'aria2c -h'.
> 
> C:\Users\clamsawd>

The error is displayed with my own build ([aria2-1.20.0-win-64bit-build1.7z](https://github.com/clamsawd/aria2-static-builds/releases/download/v1.20.0/aria2-1.20.0-win-64bit-build1.7z)) and with your build ([aria2-1.20.0-win-64bit-build1.zip](https://github.com/tatsuhiro-t/aria2/releases/download/release-1.20.0/aria2-1.20.0-win-64bit-build1.zip)) too. 
If I run the 32-bit binary the error is displayed  too, but If I run the the binary with WINE under Debian 8 is not displayed.

Could be an error of Windows 10 or an error of aria2?

**Comment by tatsuhiro-t** [comment]
Run console as adminitrator privilege.  This warning is harmless if you don't use --file-allocation=falloc.
In other words, adminitrator privilege is required to make --file-allocation=falloc work properly on Windows.

**Comment by clamsawd** [comment]
Exactly, aria2 works correctly if don't use 'falloc' allocation. I tried run console as administrator privilege and effectively has disappeared the error message.

Thanks @tatsuhiro-t !
