### ISSUE TITLE
build will fail if SSL not enabled

### ISSUE THREAD

**Issue by Twilight** [tatsuhiro-t/aria2#576]
https://github.com/tatsuhiro-t/aria2/blob/cf2fa33fe0d73f7001d262beee5e8aba03544126/src/SocketCore.cc#L1329-L1333

these should be enclosed in a `#ifdef ENABLE_SSL` block

**Comment by tatsuhiro-t** [comment]
Thank you for telling me that.  Fix committed via 8985d66e71f980e7d2765753800078f47761f1ba
