### ISSUE TITLE
SeManageVolumePrivilege failed on Win7x64/NTFS

### ISSUE THREAD

**Issue by haikubox** [tatsuhiro-t/aria2#579]
I have upgraded from **1.18.8**x32 to **1.20.0**x64. When starting program in **non**-elevated prompt I receive below warning. Even when I put `file-allocation=none` to my `~\.aria2\aria2.conf` file, it still shows warning. I did not see any warnings and `falloc` was working as expected on previous version.

Whatever the case, even though aria says falloc will not work properly - it does! I set `--file-allocation=falloc` and tried to download 12G file - size was allocated instantly. So I believe, this warning message does not reflect the actual state of things. Please let me know, if you need any other details or tests and I will be happy to provide them.

```
02/28 19:23:34 [WARN] Gaining privilege SeManageVolumePrivilege failed.

02/28 19:23:34 [WARN] --file-allocation=falloc will not work properly.
aria2 version 1.20.0
....
** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC, SFTP
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.8 expat/2.1.0 sqlite3/3.10.2 GMP/6.1.0 c-ares/1.10.0 libssh2/1.6.0
Compiler: mingw-w64 4.0 (stable) / gcc 5.3.1 20151207
  built by   x86_64-pc-linux-gnu
  targetting x86_64-w64-mingw32
  on         Feb 16 2016 00:50:49
System: Windows 7 (Service Pack 1) (x86_64) (6.1)
```

**Comment by clamsawd** [comment]
@haikubox  https://github.com/tatsuhiro-t/aria2/issues/574

**Comment by haikubox** [comment]
@clamsawd , thank you for linking issues. Unfortunately, I have found the old one after I submitted mine. However, something is still looks wrong here: aria displays warning, but still able to use `falloc` properly (see 12G file created instantly - on regular HDD, not SSD). Another thing - why prior version 1.20 aria was able to use falloc without admn permissions and now it does not? Believe running downloader in elevated prompt is a bit of "overhead" (leaving aside Windows security quirks). Just to add - my user **is** administrator, but I still need elevated prompt. I even tried to add my user directly to this permission in GPO editor, but it did not seem to have any effect.

**Comment by tatsuhiro-t** [comment]
The original issue was https://github.com/tatsuhiro-t/aria2/issues/544#issuecomment-176061548

In short, without privilege escalation, explorer shows us that file is allocated, but actually it isn't.  We observed that there is high disk activity, and writing files while downloading was severely degraded.
After several hours of debugging, I found that we needed certain kind of privilege to properly allocate files on NTFS instantly.  And this is the result.
If you don't want privilege escalation, falloc does not work perfectly, it is the same as pre-1.19.0 release.  We want to do this without privilege, but there seems to be no way on Windows.  If you know how to achieve this without privilege, please let us know.

**Comment by haikubox** [comment]
Tatsuhiro, thank you for the explanation. Looks like there is no way around to bypass elevation.
