### ISSUE TITLE
How can i build aria2c with max-connections-per-server more than 16

### ISSUE THREAD

**Issue by eightnoteight** [tatsuhiro-t/aria2#580]
Is it possible to build aria2c with --max-connections-per-server, --split more than 16, i tried to searching in the configure file for such option and also tried searching in source to check if it hard-coded anywhere, but i couldn't find it

**Comment by tatsuhiro-t** [comment]
It is hard coded.  See https://github.com/tatsuhiro-t/aria2/blob/8985d66e71f980e7d2765753800078f47761f1ba/src/OptionHandlerFactory.cc#L422
Change it to whatever value you want, and compile aria2 for yourself.

**Comment by eightnoteight** [comment]
thank you very much, i'm searching with case sensitive flag,
sorry to waste your time.
:100:

**Comment by boly007** [comment]
anyone compiled it for windows with 32 connection? can I have it ? thanks

**Comment by Kyle-Kyle** [comment]
After changing the number 16 to 32 in OptionHandlerFactory.cc as mentioned and rebuilding, the max connection per server is still 16. I wonder whether this configuration is overwritten somewhere else.

**Comment by JafarAkhondali** [comment]
@tatsuhiro-t May i ask why don't you make it dynamic? in our case (Persepolis DM) it's not a good idea to re-compile Aria2 for users.
