### ISSUE TITLE
path to sqlite download changed on s

### ISSUE THREAD

**Issue by eyalfishler** [tatsuhiro-t/aria2#581]
new path:
http://www.sqlite.org/2016/sqlite-autoconf-3100200.tar.gz 

instead of http://www.sqlite.org/2015/sqlite-autoconf-3100200.tar.gz

this is true for all make files that try to download the sqlite gz file.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this.  99e7d98 fixes this bug.
