### ISSUE TITLE
Pause problem for torrent added with magnet

### ISSUE THREAD

**Issue by locchi93** [tatsuhiro-t/aria2#591]
I don't know if this is an issue with Aria2, or i'm doing it wrong.
Problem example:
I have a torrent added by "addTorrent" with the corresponding .torrent file and an other one added by "addUri" and the corresponding magnet link.
Aria2 save the session (save-session=file-path) in a file every 20 sec (save-session-interval=20).
If both are active, like seeding, and I pause (with pause('gid')) the one added with the magnet link, the torrent is paused but in the session file the variable "pause=true" is saved under the other torrent. If now I restart the server where aria2 is running, after boot I have now the torrent added with the .torrent file paused, and the one that I previously paused is now active.

Session file after pausing:
`magnet:?....etc...
 gid=b3248894a54a08f3
/mnt/usbhdd/downloads/1e4ce26ee036d7595218f918cc9642db99e59f01.torrent
 gid=6cbca74e04c76674
 pause=true`

The 'gid' that I use to pause the torrent is the one returned by tellActive for the torrent I want to pause, in this case '30a29ef65731b78d', and, for what I understand, I think it is normal that is not present in the session file. I also have the "force-save" option in the config file.

P.S. aria2 version: 1.20.0

EDIT:
The problem seems to occur only when there is "force-save" in the config file, but I need it to keep seeding after reboot.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this bug.  We've fixed this by the commit 4595aa7.

**Comment by locchi93** [comment]
Thank you for this awesome project!
