### ISSUE TITLE
aria2.tellStatus removes bittorrent key in JSONRPC when status = complete

### ISSUE THREAD

**Issue by regystro** [tatsuhiro-t/aria2#612]
Hi. Using 1.21.0. Don't know if it's a bug or expected behaviour:
bittorrent struct reported by aria2.tellStatus dissapears once the torrent is completed and stopped. That makes impossible to get some useful info with Event Hook on-download-stop script like the name and mode.

Could you keep this info available?

Thank you.

**Comment by tatsuhiro-t** [comment]
It is true that bittorrent key is missing in stopped or removed item.  I agree that it is nice to have for BitTorrent downloads.

**Comment by tatsuhiro-t** [comment]
Fix committed via c9e2223
