### ISSUE TITLE
aria2c does not run under torify

### ISSUE THREAD

**Issue by austin987** [tatsuhiro-t/aria2#613]
Originally mentioned in #153, and while related to it, it really deserves its own bug report.

austin@debian-laptop:~$ torify aria2c http://example.com

04/01 19:31:38 [ERROR] CUID#7 - Download aborted. URI=http://example.com
Exception: [AbstractCommand.cc:345] errorCode=19 URI=http://example.com
  -> [AbstractCommand.cc:783] errorCode=19 CUID#7 - Name resolution for example.com failed:Could not contact DNS servers

04/01 19:31:38 [NOTICE] Download GID#566f2863738d29ad not complete: 

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
566f28|ERR |        n/a|http://example.com

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

Note that wget works:
austin@debian-laptop:~$ torify wget http://example.com
--2016-04-01 19:31:41--  http://example.com/
Resolving example.com (example.com)... 93.184.216.34
Connecting to example.com (example.com)|93.184.216.34|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1270 (1.2K) [text/html]
Saving to: ‘index.html'

index.html                                    100%[=====================================================================================================>]   1.24K  7.89KB/s    in 0.2s    

2016-04-01 19:31:42 (7.89 KB/s) - ‘index.html’ saved [1270/1270]

and if torify is disabled, it works:
austin@debian-laptop:~$ aria2c http://example.com

04/01 19:33:03 [NOTICE] Download complete: /home/austin/index.html

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
52a9d4|OK  |        n/a|/home/austin/index.html

Status Legend:
(OK):download completed.

**Comment by tatsuhiro-t** [comment]
Have you tried --async-dns=false option?

**Comment by balta2ar** [comment]
Thanks a lot! It works indeed with that option.

**Comment by austin987** [comment]
Yes, works here as well, thanks.
