### ISSUE TITLE
No file saved after downloading using release version

### ISSUE THREAD

**Issue by lautis0503** [tatsuhiro-t/aria2#614]
This is Windows 7 SP1 64bit and using release-1.21.0. Both 32bit and 64bit built version cannot save file after downloading, even cannot save the session file.

**Comment by tatsuhiro-t** [comment]
It works for me.  Perhaps, path is not correct or something permission issue?

**Comment by lautis0503** [comment]
When I place it in "E:\Downloads", it works fine. But when I place it in "E:\Tools\aria2", it cannot save any file. So does release-1.20.0. Don't know why.
