### ISSUE TITLE
Error while downloading file

### ISSUE THREAD

**Issue by saifsmailbox98** [tatsuhiro-t/aria2#617]
I am using webui-aria2 @ziahamza
But I tried downloading files of 1 to 2 MBs. It works fine.
But when I tried to download a larger file it failed.
Here is the link of the file http://get.videolan.org/vlc/2.2.2/win64/vlc-2.2.2-win64.exe
And some screenshots:
http://imgur.com/a/wW26v

I am using a 32GB USB stick on a **Raspberry Pi**.

**Comment by tatsuhiro-t** [comment]
What kind of error message did you get when download failed?

**Comment by saifsmailbox98** [comment]
2016-04-08 20:14:07.426175 [ERROR] [FileAllocationCommand.cc:93] CUID#10 - Exception caught while allocating file space.
Exception: [AbstractDiskWriter.cc:515] errNum=95 errorCode=17 fallocate failed. cause: Operation not supported
2016-04-08 20:14:07.427309 [ERROR] [FileAllocationCommand.cc:97] CUID#10 - Download not complete: /media/SAIF32GB/shares/downloads/files/vlc-2.2.2-win64.exe

**Comment by saifsmailbox98** [comment]
```
2016-04-08 20:14:07.426175 [ERROR] [FileAllocationCommand.cc:93] CUID#10 - Exception caught while allocating file space.
Exception: [AbstractDiskWriter.cc:515] errNum=95 errorCode=17 fallocate failed. cause: Operation not supported
2016-04-08 20:14:07.427309 [ERROR] [FileAllocationCommand.cc:97] CUID#10 - Download not complete: /media/SAIF32GB/shares/downloads/files/vlc-2.2.2-win64.exe
```

**Comment by tatsuhiro-t** [comment]
Are you using --file-allocation option?  Probably, you need to set --file-allocation=prealloc, which is safe but slow, or --file-allocation=trunc which is fast, but it could lead to fragmentation.

**Comment by saifsmailbox98** [comment]
I was having
`file-allocation=falloc`
Should I change it to `prealloc`?
Which option would be best in performance, I don't care if it slow.

**Comment by tatsuhiro-t** [comment]
falloc does not work with all file systems.
If you don't care about the slowness, prealloc is the best option, and it is the default.  If disk is formatted as FAT32 or something that does not support sparse file, actually prealloc is the only option that works properly.

**Comment by saifsmailbox98** [comment]
Okay, thank you.

**Comment by saifsmailbox98** [comment]
Also,whenever I have a power cut. The session is not saved.

**Comment by tatsuhiro-t** [comment]
If you have another issue, please create new issue. aria2 has no feature to detect spontaneous power loss.  You'd better to use shorter interval using --save-session-interval.  I think the original issue was fixed, is that correct?
