### ISSUE TITLE
Does aria2c support socks 4/5 proxy now?

### ISSUE THREAD

**Issue by hongyi-zhao** [tatsuhiro-t/aria2#622]
Hi Tatsuhiro,

Does aria2c support socks 4/5 proxy now in its latest git version?

Regards

**Comment by tatsuhiro-t** [comment]
Currently aria2 does not support socks.

**Comment by hongyi-zhao** [comment]
Thanks for your reply.

**Comment by Dingo64** [comment]
Hello,
Does it suppoert socks 4/5 now?

**Comment by luoyanghero** [comment]
Hello,
Does it suppoert socks 4/5 now?

**Comment by evandrix** [comment]
*bump*

**Comment by sky93** [comment]
How about now?

**Comment by Dibbyo456** [comment]
Nope, still don’t. ☹️

**Comment by DRSDavidSoft** [comment]
Just making sure it still doesn't

**Comment by hongyi-zhao** [comment]
I've switched to curl a long time before, therefore, little attention has been paid to this issue.
