### ISSUE TITLE
How can i get the file list of BTtorrent by json-rpc

### ISSUE THREAD

**Issue by xjbeta** [tatsuhiro-t/aria2#623]
#### i tried
`{"jsonrpc": "2.0", "id": "aria2addTorrent", "method":"aria2.addTorrent","params":["base64 of .torrent file", [], {"show-files":"true"}]}`
#### but 
`aria2c ./xxxxxx.torrent -S  `
#### works well

**Comment by tatsuhiro-t** [comment]
Read the manual.

**Comment by tatsuhiro-t** [comment]
For the record, there is no -S counterpart in RPC method.
aria2.tellStatus will return some information contained in .torrent file, and the list of the files.  For those functionality, read the manual. https://aria2.github.io/manual/en/html/aria2c.html#rpc-interface
